package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.Batchparameter;
import com.asi.huanan.service.dao.mybatis.model.BatchparameterExample;

public interface BatchparameterMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table batchparameter
	 *
	 * @mbg.generated Wed Nov 17 11:51:39 CST 2021
	 */
	long countByExample(BatchparameterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table batchparameter
	 *
	 * @mbg.generated Wed Nov 17 11:51:39 CST 2021
	 */
	int deleteByExample(BatchparameterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table batchparameter
	 *
	 * @mbg.generated Wed Nov 17 11:51:39 CST 2021
	 */
	int insert(Batchparameter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table batchparameter
	 *
	 * @mbg.generated Wed Nov 17 11:51:39 CST 2021
	 */
	int insertSelective(Batchparameter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table batchparameter
	 *
	 * @mbg.generated Wed Nov 17 11:51:39 CST 2021
	 */
	List<Batchparameter> selectByExample(BatchparameterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table batchparameter
	 *
	 * @mbg.generated Wed Nov 17 11:51:39 CST 2021
	 */
	int updateByExampleSelective(@Param("record") Batchparameter record,
			@Param("example") BatchparameterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table batchparameter
	 *
	 * @mbg.generated Wed Nov 17 11:51:39 CST 2021
	 */
	int updateByExample(@Param("record") Batchparameter record, @Param("example") BatchparameterExample example);

	// 再保臨分到期通知列印_排程執行_batchparameter table
	@Insert("<script> INSERT INTO batchparameter(taskid, batchid, dataname, datavalue) "
			+ " values(#{record.taskid,jdbcType=VARCHAR}, 'Rin1302P', 'Date1', "
			+ " #{record.date1Value,jdbcType=TIMESTAMP}) " + "</script>")

	int insertBatchFriFacParam1(@Param("record") Batchparameter modelParam);

	// 再保臨分到期通知列印_排程執行_batchparameter table
	@Insert("<script> INSERT INTO batchparameter(taskid, batchid, dataname, datavalue) "
			+ " values(#{record.taskid,jdbcType=VARCHAR}, 'Rin1302P', 'Date2', "
			+ " #{record.date2Value,jdbcType=TIMESTAMP}) " + "</script>")

	int insertBatchFriFacParam2(@Param("record") Batchparameter modelParam);

	// 排程使用，找DateValue起日
	@Select("<script>" + " select datavalue from batchparameter " + " WHERE taskid = #{taskid,jdbcType=VARCHAR} "
			+ " AND dataname = 'Date1' " + "</script>")
	String queryDateValue1(@Param("taskid") String taskid);

	// 排程使用，找DateValue訖日
	@Select("<script>" + " select datavalue from batchparameter " + " WHERE taskid = #{taskid,jdbcType=VARCHAR} "
			+ " AND dataname = 'Date2' " + "</script>")
	String queryDateValue2(@Param("taskid") String taskid);
}