package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.asi.huanan.service.dao.mybatis.model.ComAutonum;
import com.asi.huanan.service.dao.mybatis.model.ComAutonumExample;
import com.asi.huanan.service.dao.mybatis.model.ComAutonumKey;

public interface ComAutonumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    long countByExample(ComAutonumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int deleteByExample(ComAutonumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int deleteByPrimaryKey(ComAutonumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int insert(ComAutonum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int insertSelective(ComAutonum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    List<ComAutonum> selectByExample(ComAutonumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    ComAutonum selectByPrimaryKey(ComAutonumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int updateByExampleSelective(@Param("record") ComAutonum record, @Param("example") ComAutonumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int updateByExample(@Param("record") ComAutonum record, @Param("example") ComAutonumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int updateByPrimaryKeySelective(ComAutonum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_autonum
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    int updateByPrimaryKey(ComAutonum record);


    /**
     * Rin1203_查詢流水號
     * @param numberCode
     * @return
     */
//    @Select("<script>"+
//            "select serial from com_autonum \n "+
//            "where function_id ='1203' and operate_type ='Risk' \n"+
//            "and number_code = #{number_code,jdbcType=VARCHAR}"+
//    		"</script>")
    @Select("<script> select serial from com_autonum \n where function_id ='1203' and operate_type ='Risk' \n and number_code = #{number_code,jdbcType=VARCHAR} </script>")
	int getRiskNoSerial(@Param("number_code") String numberCode);

    /**
     * Rin1203_新增同險後，流水號+1
     * @param numberCode
     * @return
     */

//    @Update("<script>"+
//            "UPDATE com_autonum set serial=serial+1 \n"+
//            "where function_id ='1203' and operate_type ='Risk' and number_code =#{numberCode,jdbcType=VARCHAR}\n"+
//    		"</script>")
    @Update("<script> UPDATE com_autonum set serial=serial+1 \n where function_id ='1203' and operate_type ='Risk' and number_code =#{numberCode,jdbcType=VARCHAR}\n </script>")
   int plusComAutonumSerial(@Param("numberCode") String numberCode);


    /**
     * Rin1203_刪除同險後，流水號-1
     * @param numberCode
     * @return
     */
//    @Update("<script>"+
//            "UPDATE com_autonum set serial=serial-1 \n"+
//            "where function_id ='1203' and operate_type ='Risk' and number_code =#{numberCode,jdbcType=VARCHAR} \n"+
//    		"</script>")
    @Update("<script> UPDATE com_autonum set serial=serial-1 \n where function_id ='1203' and operate_type ='Risk' and number_code =#{numberCode,jdbcType=VARCHAR} \n </script>")
   int minusComAutonumSerial(@Param("numberCode") String numberCode);


    /**
     * Rin1203_若是序號為0,則整筆刪除
     * @param numberCode
     * @return
     */
    @Delete("<script>"+
            "DELETE com_autonum \n"+
            "where function_id='1203' and operate_type='Risk' and number_code=#{numberCode,jdbcType=VARCHAR} \n"+
    		"</script>")
    int deleteOneComAutonumList(@Param("numberCode") String numberCode);


    /**
     * Rin1203_若是無資料，新增一筆序號為0的資料
     * @param numberCode
     * @return
     */
//    @Insert("<script>"+
//    		"insert into com_autonum (company_code ,function_id,operate_type,number_code,num_year ,num_month ,num_day ,serial) \n "+
//    		"values ('','1203','Risk',#{numberCode,jdbcType=VARCHAR},'','','',0)\n"+
//    		"</script>")
    @Insert("<script> insert into com_autonum (company_code ,function_id,operate_type,number_code,num_year ,num_month ,num_day ,serial) \n values ('','1203','Risk',#{numberCode,jdbcType=VARCHAR},'','','',0)\n </script>")
	int insertOneListByNumberCode(@Param("numberCode")String numberCode);


    /**
     * rin1206取BillNoMaxSerial
     * @param num_year
     * @param number_code
     * @return
     */
//    @Select("<script>"+
//    		"select Max(serial) as maxseq from com_autonum "+
//    		" where 1= 1 "+
//    		" and num_year = #{num_year} " +
//    		" and number_code = #{number_code} " +
//    		"</script>")
    @Select("<script> select COALESCE(Max(serial), 0) as maxseq from com_autonum where 1= 1 and num_year = #{num_year} and number_code = #{number_code} </script>")
    int getBillNoMaxSerial(@Param("num_year")String num_year, @Param("number_code")String number_code);

    /**
     * Rin1206_若是無資料，新增一筆序號為0的資料
     * @param numberCode
     * @return
     */
//    @Insert("<script>"+
//    		"insert into com_autonum (company_code ,function_id,operate_type,number_code,num_year ,num_month ,num_day ,serial)  "+
//    		" values ('','1206','ACCT',#{numberCode,jdbcType=VARCHAR}, #{num_year},'','',0) "+
//    		"</script>")
    @Insert("<script> insert into com_autonum (company_code ,function_id,operate_type,number_code,num_year ,num_month ,num_day ,serial) values ('','1206','ACCT',#{numberCode,jdbcType=VARCHAR}, #{num_year},'','',1) </script>")
	int insertNewAutonum(@Param("num_year")String num_year, @Param("numberCode")String numberCode);

    /**
     * rin1206更新updateBillNoSerial
     * @param num_year
     * @param number_code
     * @return
     */
//    @Update("<script>"+
//    		"update com_autonum set serial = #{serial} " +
//    		" Where 1=1 "+
//    		" and function_id = '1206' "+
//    		" and operate_type= 'ACCT' "+
//    		" and number_code= #{number_code} "+
//    		" and num_year= #{num_year} " +
//    		"</script>")
    @Update("<script> update com_autonum set serial = #{serial} Where 1=1 and function_id = '1206' and operate_type= 'ACCT' and number_code= #{number_code} and num_year= #{num_year} </script>")
    int updateBillNoSerial(@Param("serial")int serial,@Param("num_year")String num_year, @Param("number_code")String number_code);

    Integer selectMaxSerial(ComAutonumExample example);

}