package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriCom;
import com.asi.huanan.service.dao.mybatis.model.FriComExample;
import com.asi.huanan.service.dao.mybatis.model.customerize.FricomJoinRicmpf1;

public interface FriComMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    long countByExample(FriComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int deleteByExample(FriComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int deleteByPrimaryKey(String rinComId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int insert(FriCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int insertSelective(FriCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    List<FriCom> selectByExample(FriComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    FriCom selectByPrimaryKey(String rinComId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriCom record, @Param("example") FriComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int updateByExample(@Param("record") FriCom record, @Param("example") FriComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int updateByPrimaryKeySelective(FriCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com
     *
     * @mbg.generated Fri Sep 24 17:54:50 CST 2021
     */
    int updateByPrimaryKey(FriCom record);
    
    
    // =====針對使用自訂SQL=====
    @Select("<script>"+ 
    		"select rin_Com_Id as rinComId, cname, ename, usemrk " + 
    		"from fri_com " + 
    		"where rin_Com_Id like concat(#{rinComId,jdbcType=VARCHAR},'%') " + 
    		"order by rin_Com_Id"+ 
    		"</script>")
 
    List<FricomJoinRicmpf1> queryReiners(@Param("rinComId") String rinComId);
    
    @Select("<script>"+ 
    		"select top 10 (rin_Com_Id ) as rinComId " + 
    		"from fri_com " + 
    		"where rin_Com_Id like concat(#{rinComId,jdbcType=VARCHAR},'%') " + 
    		"order by rin_Com_Id"+ 
    		"</script>")
 
    List<FriCom> autoTenRcid(@Param("rinComId") String rinComId);
    
    
    
    
}