package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriComCredit;
import com.asi.huanan.service.dao.mybatis.model.FriComCreditExample;
import com.asi.huanan.service.dao.mybatis.model.FriComCreditKey;

public interface FriComCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    long countByExample(FriComCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int deleteByExample(FriComCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int deleteByPrimaryKey(FriComCreditKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int insert(FriComCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int insertSelective(FriComCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    List<FriComCredit> selectByExample(FriComCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    FriComCredit selectByPrimaryKey(FriComCreditKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriComCredit record, @Param("example") FriComCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int updateByExample(@Param("record") FriComCredit record, @Param("example") FriComCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int updateByPrimaryKeySelective(FriComCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_com_credit
     *
     * @mbg.generated Sun Sep 26 17:31:48 CST 2021
     */
    int updateByPrimaryKey(FriComCredit record);
    
	// =====針對使用自訂SQL=====
    @Select({"<script>"+ 
    		"select credit_organ as creditOrgan, credit_level as creditLevel , " , 
    		" CONVERT (varchar(12), credit_date ,111) as txtCreditDate " ,
    		" from fri_com_credit " , 
    		" where rin_com_id = #{rinComId,jdbcType=VARCHAR} " , 
    		" order by credit_date desc ",
    		"</script>"})
    
    List<FriComCredit> queryCredit(@Param("rinComId") String rinComId);
}