package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriFacExcludeExample;
import com.asi.huanan.service.dao.mybatis.model.FriFacExcludeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriFacExcludeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    long countByExample(FriFacExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    int deleteByExample(FriFacExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    int deleteByPrimaryKey(FriFacExcludeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    int insert(FriFacExcludeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    int insertSelective(FriFacExcludeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    List<FriFacExcludeKey> selectByExample(FriFacExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") FriFacExcludeKey record, @Param("example") FriFacExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_exclude
     *
     * @mbg.generated Sun Jan 02 18:14:47 CST 2022
     */
    int updateByExample(@Param("record") FriFacExcludeKey record, @Param("example") FriFacExcludeExample example);
}