package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriFacRem;
import com.asi.huanan.service.dao.mybatis.model.FriFacRemExample;
import com.asi.huanan.service.dao.mybatis.model.FriFacRemKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriFacRemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    long countByExample(FriFacRemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int deleteByExample(FriFacRemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int deleteByPrimaryKey(FriFacRemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int insert(FriFacRem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int insertSelective(FriFacRem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    List<FriFacRem> selectByExample(FriFacRemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    FriFacRem selectByPrimaryKey(FriFacRemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int updateByExampleSelective(@Param("record") FriFacRem record, @Param("example") FriFacRemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int updateByExample(@Param("record") FriFacRem record, @Param("example") FriFacRemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int updateByPrimaryKeySelective(FriFacRem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_rem
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    int updateByPrimaryKey(FriFacRem record);
}