package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriFacSamerisk;
import com.asi.huanan.service.dao.mybatis.model.FriFacSameriskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriFacSameriskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    long countByExample(FriFacSameriskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int deleteByExample(FriFacSameriskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int deleteByPrimaryKey(String slipNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int insert(FriFacSamerisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int insertSelective(FriFacSamerisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    List<FriFacSamerisk> selectByExample(FriFacSameriskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    FriFacSamerisk selectByPrimaryKey(String slipNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") FriFacSamerisk record, @Param("example") FriFacSameriskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int updateByExample(@Param("record") FriFacSamerisk record, @Param("example") FriFacSameriskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int updateByPrimaryKeySelective(FriFacSamerisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_samerisk
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    int updateByPrimaryKey(FriFacSamerisk record);
}