package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriFacBroker;
import com.asi.huanan.service.dao.mybatis.model.FriFacBrokerExample;
import com.asi.huanan.service.dao.mybatis.model.FriFacBrokerKey;
import com.asi.huanan.service.dao.mybatis.model.customerize.Rin1303Query3;
import com.asi.huanan.service.dao.mybatis.model.customerize.Rin1303Query4;

public interface FriFacBrokerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    long countByExample(FriFacBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int deleteByExample(FriFacBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int deleteByPrimaryKey(FriFacBrokerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int insert(FriFacBroker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int insertSelective(FriFacBroker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    List<FriFacBroker> selectByExample(FriFacBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    FriFacBroker selectByPrimaryKey(FriFacBrokerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int updateByExampleSelective(@Param("record") FriFacBroker record, @Param("example") FriFacBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int updateByExample(@Param("record") FriFacBroker record, @Param("example") FriFacBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int updateByPrimaryKeySelective(FriFacBroker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_fac_broker
     *
     * @mbg.generated Mon May 23 11:35:16 CST 2022
     */
    int updateByPrimaryKey(FriFacBroker record);
    
    
    @Select("<script>Select  A.slip_no , a.broker_id , a.rin_com_id , " + 
    		"( Select top 1 ename from fri_com B where B.rin_com_id=A.rin_com_id ) as rinComSname " + 
    		", A.share_rate as brokerShareRate " + 
    		"FROM fri_fac_broker A " + 
    		"WHERE A.slip_no = #{slipNo} " + 
    		"AND A.broker_id = #{rinComId} " + 
    		"ORDER BY A.share_rate</script>")
    List<Rin1303Query3> queryRin1303Print3(@Param("slipNo") String slipNo, @Param("rinComId") String rinComId);
    
    
    @Select({"<script>select rin_com_id, sum(share_rate) as rin_com_share "  
    		,", (select top 1 ename from fri_com where rin_com_id=fri_fac_broker.rin_com_id ) as rin_com_name "  
    		,"from fri_fac_broker "
    		,"where slip_no = #{slipNo} "
    		,"and Broker_id = #{brokerId} "
    		,"group by rin_com_id </script>"})
    List<Rin1303Query4> queryRin1303BrokerInfo(@Param("slipNo") String slipNo, @Param("brokerId") String brokerId);
}