package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.asi.huanan.service.dao.mybatis.model.FriKindMapping;
import com.asi.huanan.service.dao.mybatis.model.FriKindMappingExample;

public interface FriKindMappingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fri_kind_mapping
	 * @mbg.generated  Tue Dec 21 17:47:51 CST 2021
	 */
	long countByExample(FriKindMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fri_kind_mapping
	 * @mbg.generated  Tue Dec 21 17:47:51 CST 2021
	 */
	int deleteByExample(FriKindMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fri_kind_mapping
	 * @mbg.generated  Tue Dec 21 17:47:51 CST 2021
	 */
	int insert(FriKindMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fri_kind_mapping
	 * @mbg.generated  Tue Dec 21 17:47:51 CST 2021
	 */
	int insertSelective(FriKindMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fri_kind_mapping
	 * @mbg.generated  Tue Dec 21 17:47:51 CST 2021
	 */
	List<FriKindMapping> selectByExample(FriKindMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fri_kind_mapping
	 * @mbg.generated  Tue Dec 21 17:47:51 CST 2021
	 */
	int updateByExampleSelective(@Param("record") FriKindMapping record,
			@Param("example") FriKindMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fri_kind_mapping
	 * @mbg.generated  Tue Dec 21 17:47:51 CST 2021
	 */
	int updateByExample(@Param("record") FriKindMapping record, @Param("example") FriKindMappingExample example);
	
	
	List<FriKindMapping> selectInsKind(FriKindMappingExample example);
}