package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriMunichArea;
import com.asi.huanan.service.dao.mybatis.model.FriMunichAreaExample;
import com.asi.huanan.vo.DeleteMunichVo;
import com.asi.huanan.vo.Rin1106Vo;

public interface FriMunichAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    long countByExample(FriMunichAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int deleteByExample(FriMunichAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int deleteByPrimaryKey(String naturalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int insert(FriMunichArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int insertSelective(FriMunichArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    List<FriMunichArea> selectByExample(FriMunichAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    FriMunichArea selectByPrimaryKey(String naturalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriMunichArea record, @Param("example") FriMunichAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int updateByExample(@Param("record") FriMunichArea record, @Param("example") FriMunichAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int updateByPrimaryKeySelective(FriMunichArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_munich_area
     *
     * @mbg.generated Thu Oct 28 11:19:29 CST 2021
     */
    int updateByPrimaryKey(FriMunichArea record);
    
    
    @Select("<script>select natural_id as txtnatural_id, city_name as txtcity_name, "
    		+ "munich_id as txtmunich_id, munich_desc as txtmunich_desc "
    		+ "from fri_munich_area</script>")
    
    List<Rin1106Vo> queryAllFor1106();
    
    
    @Delete("<script> delete from fri_munich_area where "
    		+ "<foreach collection =\"record\" item = \"item\" index=\"index\" separator=\"or\">"
    		+ "(natural_id = #{item.txtnatural_id,jdbcType=VARCHAR})"
    		+ "</foreach>"  
    		+ "</script>")
    
    int deleteMunichsByPkList(@Param("record") List<DeleteMunichVo> record);
}