package com.asi.huanan.service.dao.mybatis.mapper;


import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.asi.huanan.service.dao.mybatis.model.FriPolicyProp;
import com.asi.huanan.service.dao.mybatis.model.FriPolicyPropExample;
import com.asi.huanan.service.dao.mybatis.model.FriPolicyPropKey;
import com.asi.huanan.vo.Rin1304FriPolicyPropVOResp;
import com.asi.huanan.vo.Rin1304QueryDdlPropertyListVO;
import com.asi.huanan.vo.Rin1304QueryPolicyPropVO;
import com.asi.huanan.vo.Rin1304VO;

public interface FriPolicyPropMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    long countByExample(FriPolicyPropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int deleteByExample(FriPolicyPropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int deleteByPrimaryKey(FriPolicyPropKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int insert(FriPolicyProp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int insertSelective(FriPolicyProp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    List<FriPolicyProp> selectByExample(FriPolicyPropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    FriPolicyProp selectByPrimaryKey(FriPolicyPropKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriPolicyProp record, @Param("example") FriPolicyPropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByExample(@Param("record") FriPolicyProp record, @Param("example") FriPolicyPropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByPrimaryKeySelective(FriPolicyProp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_prop
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByPrimaryKey(FriPolicyProp record);
    
//    /**
//     * Rin1304_臨分分入，確認查詢，用「保單號碼」和「批單號碼」和「第1層地址序號」查詢第2層
//     * @param policyNo
//     * @param endorseNo
//     * @param numAddrNo
//     * @return
//     */
//    @Select("<script>"
//    		+"Select prop_no,property_name \n"
//    		+ "from fri_policy_prop \n"
//    		+ "WHERE policy_no= #{txtpolicy_no_query,jdbcType=VARCHAR} \n"
//    	    +"AND endorse_no= #{txtendorse_no_query,jdbcType=VARCHAR} \n"
//    	    +" AND addr_no= #{numAddr_No,jdbcType=VARCHAR} \n"
//    		+"</script>")
//    List<Rin1304VOResp> getPolicyTreeData2 (@Param("txtpolicy_no_query") String policyNo,@Param("txtendorse_no_query") String endorseNo,@Param("numAddr_No") String numAddrNo);

    
    
    /**
     * Rin1304_臨分分入，刪除保批單標的物檔
     * @param policyNo
     * @param endorseNo
     * @param addrNo
     * @param propNo
     * @param additionSeq
     * @return
     */
//    @Delete("<script>"
//    		+"delete from  fri_policy_prop \n"   
//    		+"WHERE  policy_no = #{policyNo,jdbcType=VARCHAR} \n"
//    		+"AND endorse_no = #{endorseNo,jdbcType=VARCHAR}\n"
//    		+"<if test=\"addrNo !=null and addrNo !=''\">AND addr_no = #{addrNo,jdbcType=VARCHAR} </if> \n"
//    		+"<if test=\"propNo !=null and propNo !=''\">AND prop_no = #{propNo,jdbcType=VARCHAR}</if>  \n"
//    		+"</script>")
    @Delete("<script> delete from  fri_policy_prop \n WHERE  policy_no = #{policyNo,jdbcType=VARCHAR} \n AND endorse_no = #{endorseNo,jdbcType=VARCHAR}\n <if test=\"addrNo !=null and addrNo !=''\">AND addr_no = #{addrNo,jdbcType=VARCHAR} </if> \n <if test=\"propNo !=null and propNo !=''\">AND prop_no = #{propNo,jdbcType=VARCHAR}</if>  \n </script>")
    int deletePolicyProp (@Param("policyNo") String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo") String addrNo,@Param("propNo") String propN);

    
    /**
     *  Rin1304_臨分分入,用「保單號碼」和「批單號碼」查詢標的物明細檔
     * @param policyNo
     * @param endorseNo
     * @return
     */
//    @Select("<script>"
//    		+"select policy_no as txtpolicy_no,endorse_no as txtendorse_no \n"
//    		+"from fri_policy_prop \n"
//    		+"WHERE policy_no=#{policyNo,jdbcType=VARCHAR} \n"
//    		+"AND  endorse_no=#{endorseNo,jdbcType=VARCHAR}"
//    		+"</script>")
    @Select("<script> select policy_no as policyNo,endorse_no as endorseNo \n from fri_policy_prop \n WHERE policy_no=#{policyNo,jdbcType=VARCHAR} \n AND endorse_no=#{endorseNo,jdbcType=VARCHAR} </script>")
    List<Rin1304VO> queryPolicyPropDtl(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo);

    
    /**
     *  Rin1304_臨分分入,用「保單號碼」和「批單號碼」和「地址序號」查詢標的物明細檔
     * @param policyNo
     * @param endorseNo
     * @return
     */
//    @Select("<script>"
//     	   +"SELECT policy_no as txtpolicy_no,endorse_no as txtendorse_no,addr_no as numaddr_no,prop_no as numprop_no, \n"
//     	   +"float_flag as txtfloatFlag,  property_no as txtproperty_no,property_name  as txtproperty_name ,property_code as txtproperty_code,\n"
//     	   +"amt as numamt,prem as numprem,useprop_code as txtuseprop_code,useprop_name as txtuseprop_name,const_class as txtconst_class,\n"
//     	   +"limit_no as txtlimit_no,spec_term as txtspec_term,ext_term as txtext_term \n"
//     	   +"from fri_policy_prop \n"
//     	   + "WHERE 1 = 1 "  
// 			+ " AND policy_no =#{policyNo,jdbcType=VARCHAR} "
// 			+" AND endorse_no = #{endorseNo,jdbcType=VARCHAR} \r\n"  
//            + "AND addr_no=#{addrNo,jdbcType=VARCHAR} \n "
//            +"AND prop_no=#{propNo,jdbcType=VARCHAR} "
//     	   +"</script>")
    @Select("<script> SELECT policy_no as txtpolicy_no,endorse_no as txtendorse_no,addr_no as numaddr_no,prop_no as numprop_no, \n float_flag as txtfloatFlag, property_no as txtproperty_no,property_name  as txtproperty_name ,property_code as txtproperty_code,\n amt as numamt,prem as numprem,useprop_code as txtuseprop_code,useprop_name as txtuseprop_name,const_class as txtconst_class,\n limit_no as txtlimit_no,spec_term as txtspec_term,ext_term as txtext_term \n from fri_policy_prop \n WHERE 1 = 1  AND policy_no =#{policyNo,jdbcType=VARCHAR}   AND endorse_no = #{endorseNo,jdbcType=VARCHAR} \n AND addr_no=#{addrNo,jdbcType=VARCHAR} \n AND prop_no=#{propNo,jdbcType=VARCHAR} </script>")
    List<Rin1304FriPolicyPropVOResp>  queryPolicyPropDtlResult(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo") String addrNo,@Param("propNo") String propNo);

    
    /**
     * Rin1304C_臨分分入_標的物明細檔下拉選單
     * @return
     */
    @Select("<script> select distinct prop_no as propertyNo, cname as propertyName, ename from prop_name order by prop_no </script>")
	List<Rin1304QueryDdlPropertyListVO> queryDdlPropertyList();

    
    /**
     * Rin1304_臨分分入_新增保批單標的物明細檔 by 續保單號
     * @param policyNo
     * @param endorseNo
     * @param getPolicyNo
     * @return
     */
    @Insert({"<script> "
            ,"Insert into fri_policy_prop "
            ,"(policy_no, endorse_no, addr_no, prop_no, float_flag, property_no, property_name, property_code, amt, prem,"
	        ,"useprop_code, useprop_name, const_class, limit_no, spec_term, ext_term) "
            ,"select DISTINCT #{policyNo,jdbcType=VARCHAR} as policy_no, #{endorseNo,jdbcType=VARCHAR} as endorse_no, A.addr_no, "
	        ,"A.prop_no, A.float_flag, A.property_no, A.property_name, A.property_code , A.amt, A.prem,"
	        ,"A.useprop_code, A.useprop_name, A.const_class, A.limit_no, A.spec_term, A.ext_term "
            ,"from   fri_policy_prop   A"
            ,"where A.policy_no = #{getPolicyNo,jdbcType=VARCHAR} and A.endorse_no = ''"
    		,"</script>"})
	int insertFriPolicyPropForOldPolicy(@Param("policyNo") String policyNo,@Param("endorseNo") String endorseNo,@Param("getPolicyNo") String getPolicyNo);

    /**
     * Rin1304_建立新的自動調整批單(ADJ)
     * @param policyNo
     * @param endorseNo
     * @param policyNoADJ
     * @param endorseNoADJ
     * @return
     */
    @Insert({"<script>"
    	    ,"Insert into  fri_policy_prop "
    		,"(policy_no, endorse_no, addr_no, prop_no, float_flag, property_no, property_name, property_code, amt, prem,"
    		,"useprop_code, useprop_name, const_class, limit_no, spec_term, ext_term) "
    	    ,"select #{policyNoADJ,jdbcType=VARCHAR} as policy_no, #{endorseNoADJ,jdbcType=VARCHAR} as endorse_no, A.addr_no,"
    	    ,"A.prop_no, A.float_flag, A.property_no, A.property_name, A.property_code , A.amt*(-1), A.prem*(-1),"
    	    ,"A.useprop_code, A.useprop_name, A.const_class, A.limit_no, A.spec_term, A.ext_term "
    	    ,"from  fri_policy_prop A"
    	    ,"where A.policy_no = #{policyNo,jdbcType=VARCHAR} and A.endorse_no = #{endorseNo,jdbcType=VARCHAR}"
    		,"</script>"})
	int createADJpolicyProp(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("policyNoADJ") String policyNoADJ,@Param("endorseNoADJ")String endorseNoADJ);
    
    /**
     * Rin1304_反算_取得標的物序號
     * @param policyNo
     * @param endorseNo
     * @param addrNo
     * @return
     */
    @Select({"<script>select  prop_no as propNo from fri_policy_prop where policy_no =#{policyNo,jdbcType=VARCHAR} and endorse_no =#{endorseNo,jdbcType=VARCHAR} and addr_no= #{addrNo,jdbcType=VARCHAR} </script>"})
    List<Rin1304QueryPolicyPropVO> getPropNo (@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo") String addrNo);
    
    
    /**
     * Rin1304_反算_更改標的物明細檔保額/保費
     * @param prem
     * @param amt
     * @param policyNo
     * @param endorseNo
     * @param addrNo
     * @param propNo
     * @return
     */
    @Update({"<script>"
    	     ,"Update fri_policy_prop Set  prem = #{prem,jdbcType=VARCHAR},"				
			 ,"amt = #{amt,jdbcType=VARCHAR}"
			 ,"where policy_no =  #{policyNo,jdbcType=VARCHAR}"
			 ,"and endorse_no =  #{endorseNo,jdbcType=VARCHAR}"
			 ,"and addr_no =  #{addrNo,jdbcType=VARCHAR}"
			 ,"and prop_no =  #{propNo,jdbcType=VARCHAR} "
    	     ,"</script>"})
    int updatePropAmtPrem(@Param("prem")BigDecimal prem,@Param("amt")BigDecimal amt,@Param("policyNo")String policyNo,
    		@Param("endorseNo") String endorseNo,@Param("addrNo") String addrNo,@Param("propNo") String propNo);
//    @Select("<script>"
//    		+"SELECT DISTINCT property_no as txtproperty_no ,property_name as txtproperty_name "
//    		+"FROM fri_policy_prop"
//    		+"</script>")
//	List<Rin1304QueryDdlPropertyListVO> queryDdlPropertyList();
    
    
    /**
     * Rin1304_標的物明細檔_取標的物序號最大值
     * @param policyNo
     * @param endorseNo
     * @param addrNo
     * @return
     */
    @Select({"<script>"
    	,"SELECT max(prop_no)+1 as propNo FROM fri_policy_prop fpp WHERE policy_no =#{policyNo,jdbcType=VARCHAR} "
    	,"AND endorse_no =#{endorseNo,jdbcType=VARCHAR} "
    	,"AND addr_no =#{addrNo,jdbcType=VARCHAR}"
    	,"</script>"})
    List<Rin1304QueryPolicyPropVO> getMaxpropNo(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo") String addrNo);
    
    
    /**
     * Rin1304_臨分分入_修改標的物明細檔地址序號
     * @param addrNo
     * @param policyNo
     * @param endorseNo
     * @param oldAddrNo
     * @return
     */
    @Update({"<script>"
		,"update fri_policy_prop \n"
		,"set addr_no =#{addrNo,jdbcType=VARCHAR}\n"
		,"where policy_no = #{policyNo,jdbcType=VARCHAR}\n"
		,"and endorse_no =  #{endorseNo,jdbcType=VARCHAR}\n"
	    ,"and addr_no =  #{oldAddrNo,jdbcType=VARCHAR} \n"
		,"</script>"})
int updatePolicyPropAddrNo( @Param("addrNo") String addrNo,@Param("policyNo") String policyNo, 
		@Param("endorseNo") String endorseNo , @Param("oldAddrNo") String oldAddrNo);
}