package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriPayAdvice;
import com.asi.huanan.service.dao.mybatis.model.FriPayAdviceExample;
import com.asi.huanan.service.dao.mybatis.model.FriPayAdviceKey;

public interface FriPayAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    long countByExample(FriPayAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int deleteByExample(FriPayAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int deleteByPrimaryKey(FriPayAdviceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int insert(FriPayAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int insertSelective(FriPayAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    List<FriPayAdvice> selectByExample(FriPayAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    FriPayAdvice selectByPrimaryKey(FriPayAdviceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriPayAdvice record, @Param("example") FriPayAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int updateByExample(@Param("record") FriPayAdvice record, @Param("example") FriPayAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int updateByPrimaryKeySelective(FriPayAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_pay_advice
     *
     * @mbg.generated Fri Dec 17 17:40:57 CST 2021
     */
    int updateByPrimaryKey(FriPayAdvice record);
    
    
    @Select({"<script>",
    		" select isnull(sum(risk_losspaid),0) as LossPaid " ,
    		" From fri_pay_advice ",
    		" where treaty_date between #{dateBgn} and #{dateEnd} ",
    		" and treaty_no = #{treatyNo} ",    		
    		"<if test='brokerID != null and brokerID != \"\"'> ",
    			" and broker_id = #{brokerID} ",
    		"</if> ",
    		"<if test='inComId != null and inComId != \"\"'> ",
    			" and rin_com_id = #{inComId}  ",
    		"</if> ",
    		" and insu01 = '03' " ,
    		"</script>"})
    long getLossPaidValue(@Param("treatyNo") String treatyNo, @Param("dateBgn") Date dateBgn, 
    		@Param("dateEnd") Date dateEnd,@Param("brokerID") String brokerID, @Param("inComId") String inComId);
    
    @Select({"<script>",
    		" select  isnull(sum(cashclaim),0) as CashClaim " , 
    		" From fri_pay_advice ",
    		" where trdate between #{dateBgn} and #{dateEnd} ",
    		" and treaty_year = #{treatyYear} " ,
    		" and treaty_no = #{treatyNo} ",    
    		"<if test='brokerID != null and brokerID != \"\"'> ",
    		" and broker_id = #{brokerID} ",
    		"</if> ",
    		"<if test='inComId != null and inComId != \"\"'> ",
    		" and rin_com_id = #{inComId}  ",
    		"</if> ",
    		" and insu01 = '03' " ,   		
    		"</script>"})
    long getCashClaimValue(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo, 
    		@Param("dateBgn") Date dateBgn, @Param("dateEnd") Date dateEnd,@Param("brokerID")  String brokerID, 
    		@Param("inComId") String inComId);
    
}