package com.asi.huanan.service.dao.mybatis.mapper;



import com.asi.huanan.service.dao.mybatis.model.FriPolicyAddition;
import com.asi.huanan.service.dao.mybatis.model.FriPolicyAdditionExample;
import com.asi.huanan.service.dao.mybatis.model.FriPolicyAdditionKey;
import com.asi.huanan.vo.Rin1304FriPolicyAdditionVOResp;
import com.asi.huanan.vo.Rin1304QueryDdlAdditionListVO;
import com.asi.huanan.vo.Rin1304SumAmtPremRespVO;
import com.asi.huanan.vo.Rin1304VO;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface FriPolicyAdditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    long countByExample(FriPolicyAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int deleteByExample(FriPolicyAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int deleteByPrimaryKey(FriPolicyAdditionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int insert(FriPolicyAddition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int insertSelective(FriPolicyAddition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    List<FriPolicyAddition> selectByExample(FriPolicyAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    FriPolicyAddition selectByPrimaryKey(FriPolicyAdditionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriPolicyAddition record, @Param("example") FriPolicyAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByExample(@Param("record") FriPolicyAddition record, @Param("example") FriPolicyAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByPrimaryKeySelective(FriPolicyAddition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_addition
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    int updateByPrimaryKey(FriPolicyAddition record);
    
//    /**
//     * Rin1304_臨分分入，確認查詢，用「保單號碼」和「批單號碼」和「第1層地址序號」和「第2層標的物序號」查詢第3層
//     * @param policyNo
//     * @param endorseNo
//     * @param numAddrNo
//     * @param numpropNo
//     * @return
//     */
//    @Select("<script>"
//    		+"Select addition_seq,addition_name,amt,prem \n"
//    		+"from fri_policy_addition"
//    		+"WHERE policy_no= #{txtpolicy_no_query,jdbcType=VARCHAR}  \n"
//    		+"AND endorse_no= #{txtendorse_no_query,jdbcType=VARCHAR}  \n"
//    		+"AND addr_no= #{numAddr_No,jdbcType=VARCHAR} \n"
//    		+"AND prop_no=#{numprop_no,jdbcType=VARCHAR}"
//    		+"</script>")
//    
//    List<Rin1304VOResp> getPolicyTreeData3 (@Param("txtpolicy_no_query") String policyNo,@Param("txtendorse_no_query") String endorseNo,@Param("numAddr_No") String numAddrNo,@Param("numprop_no") String numpropNo);

    
    /**
     * Rin1304_臨分分入，刪除保批單附加險檔
     * @param policyNo
     * @param endorseNo
     * @param addrNo
     * @param propNo
     * @return
     */
    @Delete({"<script>",
    		" delete from  fri_policy_addition ", 
    		" WHERE  policy_no = #{policyNo,jdbcType=VARCHAR} ",
    		" AND endorse_no = #{endorseNo,jdbcType=VARCHAR} ",
    		"<if test=\"addrNo !=null and addrNo !=''\">AND addr_no = #{addrNo,jdbcType=VARCHAR} </if> ",
    		"<if test=\"propNo !=null and propNo !=''\">AND prop_no = #{propNo,jdbcType=VARCHAR} </if> ",
    		"<if test=\"additionSeq !=null and additionSeq !=''\">AND addition_seq =#{additionSeq,jdbcType=VARCHAR} </if> ",
    		"</script>"})
    int deletePolicyAddition (@Param("policyNo") String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo") String addrNo,@Param("propNo") String propNo,@Param("additionSeq") String additionSeq);

    
    /**
     *  Rin1304_臨分分入,用「保單號碼」和「批單號碼」查詢保批單附加險檔
     * @param policyNo
     * @param endorseNo
     * @return
     */
    @Select({"<script>",
    		" select policy_no as policyNo,endorse_no as endorseNo ",
    		" from fri_policy_addition ",
    		" WHERE policy_no=#{policyNo,jdbcType=VARCHAR} ",
    		" AND  endorse_no=#{endorseNo,jdbcType=VARCHAR} ",
    		"</script>"})
    List<Rin1304VO> queryPolicyAddition(String policyNo, String endorseNo);
    
    
    /**
     *  Rin1304_臨分分入,用「保單號碼」和「批單號碼」和「地址序號」和「標的物序號」查詢保批單附加險檔頁面結果
     * @param policyNo
     * @param endorseNo
     * @return
     */
    @Select({"<script>",
    		" SELECT fpa.policy_no as txtpolicy_no,fpa.endorse_no as txtendorse_no, fpa.addr_no as txtaddr_no, ",
    		" fpa.prop_no as txtprop_no,fpa.addition_seq as txtaddition_seq,fpa.addition_no as txtaddition_no,",
    		" fpa.addition_name as txtaddition_name,fpa.amt as numamt ,fpa.prem as numprem,fpa.prercv_rate as numprercv_rate, ",
    		" fpa.rate as numrate, ",
    		" (fp.coins_rate/100) as coinsRate , ",
    		" fpa.amt/(fp.coins_rate/100) as numcoinamt, ",
    		" ROUND(fpa.prem/(fp.coins_rate/100), 0) as numcoinprem, ",
    		" fpa.limit_rate as numlimit_rate, fpa.limit as numlimit,fpa.limit_year as numlimit_year, fpa.mercno as txtmercno,fpa.deduct_rem as numdeduct_rem  ",
    		" from fri_policy_addition fpa ",
    		" left join fri_policy fp on fp.policy_no=fpa.policy_no AND fp.endorse_no =fpa.endorse_no ",
    		" where fpa.policy_no=#{policyNo,jdbcType=VARCHAR} ",
    		" AND fpa.endorse_no=#{endorseNo,jdbcType=VARCHAR} ",
    		" <if test=\"addrNo !=null and addrNo !=''\"> AND fpa.addr_no = #{addrNo,jdbcType=VARCHAR} </if> ",
    		" <if test=\"propNo !=null and propNo !=''\"> AND fpa.prop_no = #{propNo,jdbcType=VARCHAR} </if>  ",
    		" <if test=\"additionSeq !=null and additionSeq !=''\"> AND fpa.addition_seq=#{additionSeq,jdbcType=VARCHAR} </if>",
    		" <if test=\"additionNo !=null and additionNo !=''\"> AND fpa.addition_no=#{additionNo,jdbcType=VARCHAR} </if>",
    		"</script>"})
    List<Rin1304FriPolicyAdditionVOResp> queryPolicyAdditionResult(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo") String addrNo, @Param("propNo")String propNo,@Param("additionSeq")String additionSeq,@Param("additionNo")String additionNo);


    
    /**
     * Rin1304_臨分分入_附加險明細檔_附加險代號下拉選單
     * @return
     */
    @Select({"<script>",
    		"select distinct converage_no as txtaddition_no, cname as txtaddition_name from converage order by converage_no",
    		"</script>"})
    List<Rin1304QueryDdlAdditionListVO> queryDdlAdditionList();
    
  
    /**
     * Rin1304_臨分分入_更新保批單附加險明細檔
     * @param record
     * @return
     */
//    @Update("<script>"
//    		+"UPDATE fri_policy_addition  SET \n"
//    		+"addition_seq=#{record.additionSeq,jdbcType=VARCHAR},addition_no=#{record.additionNo,jdbcType=VARCHAR},"
//    		+"addition_name=#{record.additionName,jdbcType=VARCHAR}, \n"
//    		+"amt=#{record.amt,jdbcType=VARCHAR},prem=#{record.prem,jdbcType=VARCHAR},"
//    		+"prercv_rate=#{record.prercvRate,jdbcType=VARCHAR},limit=#{record.limit,jdbcType=VARCHAR}, \n"
//    		+"limit_year=#{record.limitYear,jdbcType=VARCHAR},limit_rate=#{record.limitRate,jdbcType=VARCHAR}, \n"
//    		+"Rate=#{record.rate,jdbcType=VARCHAR},deduct_rem=#{record.deductRem,jdbcType=VARCHAR}, \n"
//    		+"mercno=#{record.mercno,jdbcType=VARCHAR}  \n"
//    		+"Where "
//    		+"policy_no = #{record.policyNo,jdbcType=VARCHAR}  \n"
//    		+"and endorse_no= #{record.endorseNo,jdbcType=VARCHAR}  \n"
//    		+"and addr_no=#{record.addrNo,jdbcType=VARCHAR}  \n"
//    		+"and prop_no = #{record.propNo,jdbcType=VARCHAR}  \n"
//    		+"and addition_seq=#{record.additionSeq,jdbcType=VARCHAR} \n"
//    		+"</script>")   
    @Update("<script> UPDATE fri_policy_addition  SET \n addition_seq=#{record.additionSeq,jdbcType=VARCHAR},addition_no=#{record.additionNo,jdbcType=VARCHAR}, addition_name=#{record.additionName,jdbcType=VARCHAR}, \n amt=#{record.amt,jdbcType=VARCHAR},prem=#{record.prem,jdbcType=VARCHAR}, prercv_rate=#{record.prercvRate,jdbcType=VARCHAR},limit=#{record.limit,jdbcType=VARCHAR}, \n limit_year=#{record.limitYear,jdbcType=VARCHAR},limit_rate=#{record.limitRate,jdbcType=VARCHAR}, \n Rate=#{record.rate,jdbcType=VARCHAR},deduct_rem=#{record.deductRem,jdbcType=VARCHAR}, \n mercno=#{record.mercno,jdbcType=VARCHAR} \n Where policy_no = #{record.policyNo,jdbcType=VARCHAR}  \n and endorse_no= #{record.endorseNo,jdbcType=VARCHAR}  \n and addr_no=#{record.addrNo,jdbcType=VARCHAR}  \n and prop_no = #{record.propNo,jdbcType=VARCHAR}  \n and addition_seq=#{record.additionSeq,jdbcType=VARCHAR} \n </script>")
    int updatePolicyAddition (@Param("record") FriPolicyAddition record);

	/**
	 * Rin1304_臨分分入_新增附加險明細檔 by 續保單號
	 * @param policyNo
	 * @param endorseNo
	 * @param getPolicyNo
	 * @return
	 */
	@Insert({"<script>"
		     ,"Insert into  fri_policy_addition "				
		     ,"(policy_no, endorse_no, addr_no, prop_no, addition_seq, addition_no, addition_name, amt, prem, prercv_rate, "
		     ,"limit, limit_year, limit_rate, rate, deduct_rem) "
		     ,"select  DISTINCT #{policyNo,jdbcType=VARCHAR} as policy_no,#{endorseNo,jdbcType=VARCHAR} as endorse_no, A.addr_no,"
			 ,"A.prop_no, A.addition_seq, A.addition_no, A.addition_name, A.amt , A.prem, A.prercv_rate, A.limit, A.limit_year,"
		     ,"A.limit_rate, A.rate, A.deduct_rem "
		     ,"from  fri_policy_addition A"
		     ,"where A.policy_no = #{getPolicyNo,jdbcType=VARCHAR} and A.endorse_no = '' " 
			 ,"</script>"})
	int insertFriPolicyAdditionForOldPolicy(@Param("policyNo") String policyNo,@Param("endorseNo") String endorseNo,@Param("getPolicyNo") String getPolicyNo);

	
	/**
	 * Rin1304_臨分分入_建立產生新調整批單號(ADJ)
	 * @param policyNo
	 * @param endorseNo
	 * @param policyNoADJ
	 * @param endorseNoADJ
	 * @return
	 */
	@Insert({"<script>"
		     ,"Insert into fri_policy_addition 	"			
		     ,"(policy_no, endorse_no, addr_no, prop_no, addition_seq, addition_no, addition_name, amt, prem, prercv_rate, limit, limit_year, limit_rate, rate, deduct_rem, mercno) "
		     ,"select #{policyNoADJ,jdbcType=VARCHAR} as policy_no, #{endorseNoADJ,jdbcType=VARCHAR} as endorse_no, A.addr_no,"
			 ,"A.prop_no, A.addition_seq, A.addition_no, A.addition_name, A.amt*(-1) , A.prem*(-1), A.prercv_rate, A.limit, A.limit_year, A.limit_rate, A.rate, A.deduct_rem, A.mercno" 
			 ,"from  fri_policy_addition  A	"
			 ,"where A.policy_no = #{policyNo,jdbcType=VARCHAR} and A.endorse_no = #{endorseNo,jdbcType=VARCHAR}"	
			 ,"</script>"})
	int createADJpolicyAddition(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("policyNoADJ") String policyNoADJ,@Param("endorseNoADJ")String endorseNoADJ);

	/**
	 * Rin1304_計算附加險明顯保額保費總額
	 * @param policyNo
	 * @param endorseNo
	 * @param addrNo
	 * @param propNo
	 * @return
	 */
	@Select({"<script>" 
		     ,"select sum(amt) as amt,0 as prem,0 as amtTyp,0 as premTyp,0 as amtEar,0 as premEar "
		     ,"from fri_policy_Addition "
		     ,"where policy_no =  #{policyNo,jdbcType=VARCHAR}"
		     ,"and endorse_no =#{endorseNo,jdbcType=VARCHAR}"
			 ,"and addr_no = #{addrNo,jdbcType=VARCHAR} "
			 ,"and prop_no = #{propNo,jdbcType=VARCHAR} "
			 ,"and (addition_no ='OF' or addition_no ='8' or addition_no ='8A' or addition_no ='8B' ) "
			 ,"UNION "
			 ,"select 0 as amt,sum(prem) as prem,0 as amtTyp,0 as premTyp,0 as amtEar,0 as premEar "
			 ,"from fri_policy_Addition "
			 ,"where policy_no =  #{policyNo,jdbcType=VARCHAR}"
			 ,"and endorse_no = #{endorseNo,jdbcType=VARCHAR}"
			 ,"and addr_no =  #{addrNo,jdbcType=VARCHAR} "	
			 ,"and prop_no =  #{propNo,jdbcType=VARCHAR} "
		     ,"UNION "
			 ,"select 0 as amt,0 as prem,sum(amt) as amtTyp, sum(prem) as premTyp,0 as amtEar,0 as premEar "
			 ,"from fri_policy_Addition "
			 ,"where policy_no =  #{policyNo,jdbcType=VARCHAR} "
			 ,"and endorse_no = #{endorseNo,jdbcType=VARCHAR}"
			 ,"and addr_no =  #{addrNo,jdbcType=VARCHAR}"
			 ,"and (addition_no ='3' or addition_no ='83') "
		     ,"UNION"
			 ,"select 0 as amt,0 as prem,0 as amtTyp,0 as premTyp,sum(amt) as amtEar, sum(prem) as premEar "
			 ,"from fri_policy_Addition "
			 ,"where policy_no =  #{policyNo,jdbcType=VARCHAR}"
			 ,"and endorse_no = #{endorseNo,jdbcType=VARCHAR}"
			 ,"and addr_no =  #{addrNo,jdbcType=VARCHAR}"
			 ,"and (addition_no ='2' or addition_no ='82')"
		     ,"</script>"})
	List<Rin1304SumAmtPremRespVO> sumAmtPrem(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo")String addrNo,@Param("propNo") String propNo);

    /**
     * Rin1304_附加險明細檔_取附加險序號最大值
     * @param policyNo
     * @param endorseNo
     * @param addrNo
     * @param propNo
     * @return
     */
    @Select({"<script>" 
    	,"SELECT MAX(addition_seq)+1 AS additionSeq FROM fri_policy_addition "
    			, "WHERE policy_no =#{policyNo,jdbcType=VARCHAR} "
    			, "AND endorse_no =#{endorseNo,jdbcType=VARCHAR} "
    			, "AND addr_no =#{addrNo,jdbcType=VARCHAR} "
    			, "And prop_no =#{propNo,jdbcType=VARCHAR}"
    	,"</script>"})
    List<FriPolicyAdditionKey> getMaxAdditionSeq(@Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo,@Param("addrNo")String addrNo,@Param("propNo") String propNo);

    
    /**
     * Rin1304_臨分分入_修改附加險明細檔地址序號
     * @param addrNo
     * @param policyNo
     * @param endorseNo
     * @param oldAddrNo
     * @return
     */
    @Update({"<script>"
  		,"update fri_policy_addition \n"
  		,"set addr_no =#{addrNo,jdbcType=VARCHAR}\n"
  		,"where policy_no = #{policyNo,jdbcType=VARCHAR}\n"
  		,"and endorse_no =  #{endorseNo,jdbcType=VARCHAR}\n"
  	    ,"and addr_no =  #{oldAddrNo,jdbcType=VARCHAR} \n"
  		,"</script>"})
	int updatePolicyAdditionAddrNo(@Param("addrNo")String addrNo, @Param("policyNo")String policyNo,@Param("endorseNo") String endorseNo, @Param("oldAddrNo")String oldAddrNo);
}