package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriRetainLimit;
import com.asi.huanan.service.dao.mybatis.model.FriRetainLimitExample;
import com.asi.huanan.service.dao.mybatis.model.FriRetainLimitKey;
import com.asi.huanan.vo.Rin1105DeleteRetainVOReq;
import com.asi.huanan.vo.Rin1105VOResp;
import com.asi.huanan.vo.Rin1304QueryLimitVO;

public interface FriRetainLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    long countByExample(FriRetainLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int deleteByExample(FriRetainLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int deleteByPrimaryKey(FriRetainLimitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int insert(FriRetainLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int insertSelective(FriRetainLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    List<FriRetainLimit> selectByExample(FriRetainLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    FriRetainLimit selectByPrimaryKey(FriRetainLimitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriRetainLimit record, @Param("example") FriRetainLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int updateByExample(@Param("record") FriRetainLimit record, @Param("example") FriRetainLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int updateByPrimaryKeySelective(FriRetainLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_retain_limit
     *
     * @mbg.generated Wed Oct 27 16:48:44 CST 2021
     */
    int updateByPrimaryKey(FriRetainLimit record);
    
    
    @Select("<script> select treaty_year as txttreaty_year, limit_id as txtlimit_id, "
    		+ "limit_amount as numlimit_amount "
    		+ "from fri_retain_limit "
    		+ "where treaty_year like concat(#{treatyYear,jdbcType=VARCHAR},'%')"
    		+ "and limit_id like concat(#{limitId,jdbcType=VARCHAR},'%')"
    		+ "</script>")
    
    List<Rin1105VOResp> queryRetainList(@Param("treatyYear") String treatyYear, @Param("limitId") String limitId);
    
    
    @Delete("<script> delete from fri_retain_limit where "
    		+ "<foreach collection =\"record\" item = \"item\" index=\"index\" separator=\"or\">"
    		+ "(treaty_year = #{item.txttreaty_year,jdbcType=VARCHAR} and limit_id = #{item.txtlimit_id,jdbcType=VARCHAR} )"
    		+ "</foreach>"  
    		+ "</script>")
    
    int deleteRetainsByPkList(@Param("record") List<Rin1105DeleteRetainVOReq> record);
    
    /**
     * Rin1304_保批單明細畫面_查詢保單限額、限額代號、限額
     * @param policyYear
     * @param propCode
     * @param constClass
     * @return
     */
    @Select({"<script>"
    	    ,"select distinct limit_id as limitId,limit_amount as limitAmount from fri_retain_limit "
    	    ,"where treaty_year = #{policyYear,jdbcType=VARCHAR}"
    	    ,"and limit_id = "
    	    ,"<choose>"
    	    ,"<when test=\"constClass != null and( constClass == '0'.toString() or constClass== '1'.toString())\">"
            ,"  (select special1_limit from fri_use_limit where use_prop_id = #{propCode,jdbcType=VARCHAR})"
            ,"</when>"
            ,"<when test=\"constClass != null and constClass == '2'.toString()\">"
            ," (select special2_limit from fri_use_limit where use_prop_id = #{propCode,jdbcType=VARCHAR})"
            ,"</when>"
            ,"<when test=\"constClass != null and constClass == '3'.toString()\">"
            ," (select first_limit from fri_use_limit where use_prop_id = #{propCode,jdbcType=VARCHAR})"
            ,"</when>"
            ,"<when test=\"constClass!= null and constClass == '5'.toString()\">"
            ," (select second_limit from fri_use_limit where use_prop_id = #{propCode,jdbcType=VARCHAR})"
            ,"</when>"
            ,"<when test=\"constClass != null and constClass == '6'.toString()\">"
            ," (select third_limit from fri_use_limit where use_prop_id =#{propCode,jdbcType=VARCHAR})"
            ,"</when>"
            ,"<when test=\"constClass != null and constClass == '7'.toString()\">"
            ," (select outside_limit from fri_use_limit where use_prop_id = #{propCode,jdbcType=VARCHAR})"
            ,"</when>"
    		,"</choose>"	 
    		, "</script>"})
    List<Rin1304QueryLimitVO> queryLimit (@Param("policyYear") String policyYear,@Param("propCode") String propCode,@Param("constClass") String constClass);
}