package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriRisk;
import com.asi.huanan.service.dao.mybatis.model.FriRiskExample;
import com.asi.huanan.service.dao.mybatis.model.customerize.FricomJoinRicmpf1;
import com.asi.huanan.vo.Rin1107Vo;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface FriRiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    long countByExample(FriRiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int deleteByExample(FriRiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int deleteByPrimaryKey(String riskNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int insert(FriRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int insertSelective(FriRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    List<FriRisk> selectByExample(FriRiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    FriRisk selectByPrimaryKey(String riskNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriRisk record, @Param("example") FriRiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int updateByExample(@Param("record") FriRisk record, @Param("example") FriRiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int updateByPrimaryKeySelective(FriRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_risk
     *
     * @mbg.generated Thu Sep 30 11:37:36 CST 2021
     */
    int updateByPrimaryKey(FriRisk record);
    
    
 // =====針對使用自訂SQL=====
    
    @Select("<script>"+ 
    		"select risk_no as txtrisk_no_1, risk_name as txtrisk_name, area_code as txtarea_code " + 
    		"from fri_risk " + 
    		"where risk_no like concat(#{riskNo,jdbcType=VARCHAR},'%') " + 
    		"order by risk_no"+ 
    		"</script>")
 
    List<Rin1107Vo> queryRiskList(@Param("riskNo") String riskNo);
    
    
    @Insert("<script> insert into fri_risk (risk_no, risk_name, area_code) "
    		+ "values(#{record.riskNo,jdbcType=VARCHAR},#{record.riskName,jdbcType=VARCHAR},#{record.areaCode,jdbcType=VARCHAR} )"
    		+ "</script>")
    
    
    int insertByPk(@Param("record") FriRisk record);
    
    
    @Delete("<script> delete from FRI_RISK where RISK_NO in"
    		+ "<foreach collection =\"pkList\" item = \"risk_no\" index=\"index\" open=\"(\" close=\")\" separator=\",\">"
    		+ "#{risk_no}"
    		+ "</foreach></script>")
    
    int deletePkList(@Param("pkList") String[] pkList);
    
}