package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriTreaty;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyExample;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyKey;
import com.asi.huanan.vo.Rin1102QueryTreatysVOReq;
import com.asi.huanan.vo.Rin1102VOResp;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface FriTreatyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    long countByExample(FriTreatyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int deleteByExample(FriTreatyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int deleteByPrimaryKey(FriTreatyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int insert(FriTreaty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int insertSelective(FriTreaty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    List<FriTreaty> selectByExample(FriTreatyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    FriTreaty selectByPrimaryKey(FriTreatyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriTreaty record, @Param("example") FriTreatyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int updateByExample(@Param("record") FriTreaty record, @Param("example") FriTreatyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int updateByPrimaryKeySelective(FriTreaty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty
     *
     * @mbg.generated Thu Nov 04 11:24:27 CST 2021
     */
    int updateByPrimaryKey(FriTreaty record);
    
    @Select("<script>select treaty_year as txttreaty_year, treaty_no as txttreaty_no, treaty_name as txttreaty_name "
    		+ "from fri_treaty "
    		+ "where treaty_year like concat(#{record.treatyYear,jdbcType=VARCHAR},'%') "
    		+ "and treaty_no like concat(#{record.treatyNo,jdbcType=VARCHAR},'%') "
    		+ "order by treaty_year, treaty_no "
    		+ "</script>")
    
    List<Rin1102VOResp> queryTreatys(@Param("record") Rin1102QueryTreatysVOReq record);
    
    @Delete("<script> delete from fri_treaty "
    		+ "where treaty_year = #{treatyYear,jdbcType=VARCHAR} "
    		+ "and treaty_no = #{treatyNo,jdbcType=VARCHAR}</script>")
    
    int deleteByYearNo(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo);
    
}