package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriTreatyRincom;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyRincomExample;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyRincomKey;
import com.asi.huanan.vo.Rin1102AQueryOneTreatyVOReq;
import com.asi.huanan.vo.Rin1102ARincomVOResp;

public interface FriTreatyRincomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    long countByExample(FriTreatyRincomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int deleteByExample(FriTreatyRincomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int deleteByPrimaryKey(FriTreatyRincomKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int insert(FriTreatyRincom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int insertSelective(FriTreatyRincom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    List<FriTreatyRincom> selectByExample(FriTreatyRincomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    FriTreatyRincom selectByPrimaryKey(FriTreatyRincomKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriTreatyRincom record, @Param("example") FriTreatyRincomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int updateByExample(@Param("record") FriTreatyRincom record, @Param("example") FriTreatyRincomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int updateByPrimaryKeySelective(FriTreatyRincom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_rincom
     *
     * @mbg.generated Wed Nov 03 10:11:06 CST 2021
     */
    int updateByPrimaryKey(FriTreatyRincom record);
    
    @Select("<script>select rin_com_id as txtrin_com_id1, rin_com_seq as numrin_com_seq, "
    		+ "rin_com_sname as txtrin_com_sname1, rin_com_share as numrin_com_share1, "
    		+ "rin_com_tax as numrin_com_tax "
    		+ "from fri_treaty_rincom "
    		+ "where treaty_year = #{record.treatyYear,jdbcType=VARCHAR} "
    		+ "and treaty_no = #{record.treatyNo,jdbcType=VARCHAR}</script>")
    
    List<Rin1102ARincomVOResp> queryTreatyRincoms(@Param("record") Rin1102AQueryOneTreatyVOReq record);
    
    @Delete("<script> delete from fri_treaty_rincom "
    		+ "where treaty_year = #{treatyYear,jdbcType=VARCHAR} "
    		+ "and treaty_no = #{treatyNo,jdbcType=VARCHAR}</script>")
    
    int deleteByYearNo(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo);
}