package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriTemparea;
import com.asi.huanan.service.dao.mybatis.model.FriTempareaExample;
import com.asi.huanan.vo.Rin1203Vo;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface FriTempareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    long countByExample(FriTempareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int deleteByExample(FriTempareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int deleteByPrimaryKey(String areaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int insert(FriTemparea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int insertSelective(FriTemparea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    List<FriTemparea> selectByExample(FriTempareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    FriTemparea selectByPrimaryKey(String areaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriTemparea record, @Param("example") FriTempareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int updateByExample(@Param("record") FriTemparea record, @Param("example") FriTempareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int updateByPrimaryKeySelective(FriTemparea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_temparea
     *
     * @mbg.generated Tue Nov 23 14:51:29 CST 2021
     */
    int updateByPrimaryKey(FriTemparea record);
    
    
    /**
     * Rin1203_同險設定，用地段代號和範圍查詢地段代號
     * @param txtarea_code
     * @param risk_flag
     * @return
     */
    @Select("<script>select area_code as txtarea_code , proc_count \n" + 
    		"from fri_temparea a \n" + 
    		"WHERE \n"+
    		"a.area_code like concat(#{areaCode,jdbcType=VARCHAR},'%') \n" + 
    		"<if test=\"riskFlag !=null and riskFlag!='' \"> and a.proc_count = #{riskFlag,jdbcType=VARCHAR}</if>"+ 
    		"order by area_code \n" + 
    		"</script>")
    List<Rin1203Vo> queryTemparea(@Param("areaCode") String areaCode,@Param("riskFlag") String riskFlag);


  
    /**Rin1203_同險設定，當處理狀態為N的時候，暫存表proc_count =0
     * @param proc_count
     * @param txtarea_code
     * @return
     */
//    @Update("<script>"+
//   		 "update fri_temparea set proc_count = #{procCount,jdbcType=INTEGER} \n" + 
//   		 " where area_code = #{areaCode,jdbcType=VARCHAR} \n" + 
//            "</script>")
    @Update("<script> update fri_temparea set proc_count = #{procCount,jdbcType=INTEGER} \n where area_code = #{areaCode,jdbcType=VARCHAR} \n </script>")
    int updateTemparea(@Param("procCount") int procCount,@Param("areaCode") String areaCode);
}