package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriTreatyCalRecord;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyCalRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriTreatyCalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    long countByExample(FriTreatyCalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int deleteByExample(FriTreatyCalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int deleteByPrimaryKey(String programId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int insert(FriTreatyCalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int insertSelective(FriTreatyCalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    List<FriTreatyCalRecord> selectByExample(FriTreatyCalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    FriTreatyCalRecord selectByPrimaryKey(String programId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriTreatyCalRecord record, @Param("example") FriTreatyCalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int updateByExample(@Param("record") FriTreatyCalRecord record, @Param("example") FriTreatyCalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int updateByPrimaryKeySelective(FriTreatyCalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_cal_record
     *
     * @mbg.generated Wed Dec 01 17:39:03 CST 2021
     */
    int updateByPrimaryKey(FriTreatyCalRecord record);
}