package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.asi.huanan.service.dao.mybatis.model.FriTreatyComm;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyCommExample;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyCommKey;
import com.asi.huanan.vo.Rin1103DeleteTreatyVOReq;
import com.asi.huanan.vo.Rin1103InsertTreatyCommVOReq;
import com.asi.huanan.vo.Rin1103VOResp;
import com.asi.huanan.vo.Rin1103UpdateTreatyCommVOReq;


public interface FriTreatyCommMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    long countByExample(FriTreatyCommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int deleteByExample(FriTreatyCommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int deleteByPrimaryKey(FriTreatyCommKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int insert(FriTreatyComm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int insertSelective(FriTreatyComm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    List<FriTreatyComm> selectByExample(FriTreatyCommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    FriTreatyComm selectByPrimaryKey(FriTreatyCommKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriTreatyComm record, @Param("example") FriTreatyCommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int updateByExample(@Param("record") FriTreatyComm record, @Param("example") FriTreatyCommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int updateByPrimaryKeySelective(FriTreatyComm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_comm
     *
     * @mbg.generated Fri Oct 15 11:57:17 CST 2021
     */
    int updateByPrimaryKey(FriTreatyComm record);
    
    
    // =====針對使用自訂SQL=====
    
    @Select("<script> select serial, treaty_year as txttreaty_year, treaty_no as txttreaty_no, "
    		+ "comm_type as txtcomm_type, upper_limit as numupper_limit, lower_limit as numlower_limit, "
    		+ "comm_rate as numcomm_rate "
    		+ "from fri_treaty_comm "
    		+ "where treaty_year like concat(#{treatyYear,jdbcType=VARCHAR},'%')"
    		+ "and treaty_no like concat(#{treatyNo,jdbcType=VARCHAR},'%')"
    		+ "</script>")
    
    List<Rin1103VOResp> queryTreatyList(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo);
    
    
    @Select("<script> select serial, treaty_year as treatyYear, treaty_no as treatyNo, "
    		+ "comm_type as commType, upper_limit as upperLimit, lower_limit as lowerLimit, "
    		+ "comm_rate as commRate "
    		+ "from fri_treaty_comm "
    		+ "where treaty_year = #{treatyYear,jdbcType=VARCHAR} "
    		+ "and treaty_no = #{treatyNo,jdbcType=VARCHAR} "
    		+ "and comm_type = #{commType,jdbcType=VARCHAR}"
    		+ "</script>")
    
    List<FriTreatyComm> checkInsertUpLow(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo, @Param("commType") String commType);
    
    @Select("<script> select serial, treaty_year as treatyYear, treaty_no as treatyNo, "
    		+ "comm_type as commType, upper_limit as upperLimit, lower_limit as lowerLimit, "
    		+ "comm_rate as commRate "
    		+ "from fri_treaty_comm "
    		+ "where treaty_year = #{treatyYear,jdbcType=VARCHAR} "
    		+ "and treaty_no = #{treatyNo,jdbcType=VARCHAR} "
    		+ "and comm_type = #{commType,jdbcType=VARCHAR} "
    		+ "and serial != #{serial,jdbcType=SMALLINT}"
    		+ "</script>")
    
    List<FriTreatyComm> checkUpdateUpLow(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo, @Param("commType") String commType, @Param("serial") short serial);
    
    
    @Update("<script> update fri_treaty_comm "
    		+ "set treaty_year = #{record.txttreaty_year,jdbcType=VARCHAR}, treaty_no = #{record.txttreaty_no,jdbcType=VARCHAR}, "
    		+ "comm_type = #{record.txtcomm_type,jdbcType=VARCHAR}, upper_limit = #{record.numupper_limit,jdbcType=DECIMAL}, "
    		+ "lower_limit = #{record.numlower_limit,jdbcType=DECIMAL},comm_rate = #{record.numcomm_rate,jdbcType=DECIMAL} "
    		+ "where treaty_year = #{record.conditionYear,jdbcType=VARCHAR} and treaty_no = #{record.conditionNo,jdbcType=VARCHAR} "
    		+ "and comm_type = #{record.conditionType,jdbcType=VARCHAR} and serial = #{record.serial,jdbcType=SMALLINT} "
    		+ "</script>")
    
    int updateByOldPk(@Param("record") Rin1103UpdateTreatyCommVOReq record);
    
    @Delete("<script> delete from fri_treaty_comm where "
    		+ "<foreach collection =\"record\" item = \"item\" index=\"index\" separator=\"or\">"
    		+ "(treaty_year = #{item.txttreaty_year,jdbcType=VARCHAR} and treaty_no = #{item.txttreaty_no,jdbcType=VARCHAR} and "
    		+ "comm_type = #{item.txtcomm_type,jdbcType=VARCHAR} and serial = #{item.serial,jdbcType=SMALLINT})"
    		+ "</foreach>"  
    		+ "</script>")
    
    int deleteTreadysByPkList(@Param("record") List<Rin1103DeleteTreatyVOReq> record);
    
    @Options(useGeneratedKeys = true, keyProperty = "serial")
    @Insert("<script>insert into fri_treaty_comm (treaty_year, treaty_no, comm_type, upper_limit, lower_limit, comm_rate) "
    		+ "values (#{record.txttreaty_year,jdbcType=VARCHAR}, #{record.txttreaty_no,jdbcType=VARCHAR}, #{record.txtcomm_type,jdbcType=VARCHAR} ,"
    		+ " #{record.numupper_limit,jdbcType=DECIMAL}, #{record.numlower_limit,jdbcType=DECIMAL},  #{record.numcomm_rate,jdbcType=DECIMAL}) "
    		+ "</script>")
    
    int insertTreadyReturnSerial(@Param("record") Rin1103InsertTreatyCommVOReq record);
    
    
    
}