package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriTreatyShareOrder;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyShareOrderExample;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyShareOrderKey;
import com.asi.huanan.vo.DeleteTreatyShareOrderVo;
import com.asi.huanan.vo.Rin1108Vo;

public interface FriTreatyShareOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    long countByExample(FriTreatyShareOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int deleteByExample(FriTreatyShareOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int deleteByPrimaryKey(FriTreatyShareOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int insert(FriTreatyShareOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int insertSelective(FriTreatyShareOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    List<FriTreatyShareOrder> selectByExample(FriTreatyShareOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    FriTreatyShareOrder selectByPrimaryKey(FriTreatyShareOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriTreatyShareOrder record, @Param("example") FriTreatyShareOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int updateByExample(@Param("record") FriTreatyShareOrder record, @Param("example") FriTreatyShareOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int updateByPrimaryKeySelective(FriTreatyShareOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_share_order
     *
     * @mbg.generated Thu Oct 28 14:51:39 CST 2021
     */
    int updateByPrimaryKey(FriTreatyShareOrder record);
    
    
    
    @Select("<script>select treaty_year as txttreaty_year, policy_type as txtpolicy_type, "
    		+ "share_order as numshare_order, treaty_no as txttreaty_no "
    		+ "from fri_treaty_share_order "
    		+ "where treaty_year like concat(#{treatyYear,jdbcType=VARCHAR},'%') "
    		+ "and policy_type like concat(#{policyType,jdbcType=VARCHAR},'%')"
    		+ "</script>")
    
    List<Rin1108Vo> queryTreatyShareOrderList(@Param("treatyYear") String treatyYear, @Param("policyType") String policyType);
    
    
    @Delete("<script> delete from fri_treaty_share_order where "
    		+ "<foreach collection =\"record\" item = \"item\" index=\"index\" separator=\"or\">"
    		+ "(treaty_year = #{item.txttreaty_year,jdbcType=VARCHAR} and policy_type = #{item.txtpolicy_type,jdbcType=VARCHAR} and "
    		+ "share_order = #{item.numshare_order,jdbcType=SMALLINT})"
    		+ "</foreach>"  
    		+ "</script>")    
    
    int deleteTreadyShareOrdersByPkList(@Param("record") List<DeleteTreatyShareOrderVo> record);
    
    
    
}