package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.asi.huanan.service.dao.mybatis.model.FriTreatyBroker;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyBrokerExample;
import com.asi.huanan.service.dao.mybatis.model.FriTreatyBrokerKey;
import com.asi.huanan.vo.Rin1102AQueryOneTreatyVOReq;
import com.asi.huanan.vo.Rin1102ABrokerVOResp;

public interface FriTreatyBrokerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    long countByExample(FriTreatyBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int deleteByExample(FriTreatyBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int deleteByPrimaryKey(FriTreatyBrokerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int insert(FriTreatyBroker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int insertSelective(FriTreatyBroker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    List<FriTreatyBroker> selectByExample(FriTreatyBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    FriTreatyBroker selectByPrimaryKey(FriTreatyBrokerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriTreatyBroker record, @Param("example") FriTreatyBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int updateByExample(@Param("record") FriTreatyBroker record, @Param("example") FriTreatyBrokerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int updateByPrimaryKeySelective(FriTreatyBroker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_treaty_broker
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    int updateByPrimaryKey(FriTreatyBroker record);
    
//    @Select("<script>"  +
//    		"select treaty_year as treatyYear, treaty_no as treatyNo,broker_id as brokerId, rin_com_id as rinComId,"
//    		+ "broker_sname as brokerSname, rin_com_sname as rinComSname, rin_com_share as rinComShare "
//    		+ " from fri_treaty_broker "  +
//    		" where treaty_year = #{treatyYear} "  +
//    		" and treaty_no = #{treatyNo} "  +
//    		" and broker_id = #{brokerId} " + 
//    		"</script>")
    @Select("<script> select treaty_year as treatyYear, treaty_no as treatyNo,broker_id as brokerId, rin_com_id as rinComId, broker_sname as brokerSname, rin_com_sname as rinComSname, rin_com_share as rinComShare from fri_treaty_broker where treaty_year = #{treatyYear} and treaty_no = #{treatyNo} and broker_id = #{brokerId} </script>")
    List<FriTreatyBroker> queryRin1206BrokerInfo(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo, @Param("brokerId") String brokerId);
    
    @Select("<script>select broker_id as txtBroker_id, broker_sname as txtBroker_sname, "
    		+ "rin_com_id as txtrin_com_id2, rin_com_sname as txtrin_com_sname2, "
    		+ "rin_com_share as numrin_com_share2 "
    		+ "from fri_treaty_broker "
    		+ "where treaty_year = #{record.treatyYear,jdbcType=VARCHAR} "
    		+ "and treaty_no = #{record.treatyNo,jdbcType=VARCHAR}</script>")
    
    List<Rin1102ABrokerVOResp> queryTreatyBrokers(@Param("record") Rin1102AQueryOneTreatyVOReq record);
    
    @Delete("<script> delete from fri_treaty_broker "
    		+ "where treaty_year = #{treatyYear,jdbcType=VARCHAR} "
    		+ "and treaty_no = #{treatyNo,jdbcType=VARCHAR}</script>")
    
    int deleteByYearNo(@Param("treatyYear") String treatyYear, @Param("treatyNo") String treatyNo);
    
}