package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.FriUseLimit;
import com.asi.huanan.service.dao.mybatis.model.FriUseLimitExample;
import com.asi.huanan.vo.DeleteTreatyVo;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface FriUseLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    long countByExample(FriUseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int deleteByExample(FriUseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int deleteByPrimaryKey(String usePropId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int insert(FriUseLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int insertSelective(FriUseLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    List<FriUseLimit> selectByExample(FriUseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    FriUseLimit selectByPrimaryKey(String usePropId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriUseLimit record, @Param("example") FriUseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int updateByExample(@Param("record") FriUseLimit record, @Param("example") FriUseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int updateByPrimaryKeySelective(FriUseLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_use_limit
     *
     * @mbg.generated Tue Oct 26 08:32:14 CST 2021
     */
    int updateByPrimaryKey(FriUseLimit record);

    
 // =====針對使用自訂SQL=====
    
 // 「使用性質代號」搜尋
    @Select("<script>"+ 
    		" select use_prop_id usePropId, special1_limit special1Limit, special2_limit special2Limit, first_limit firstLimit, " + 
    		" second_limit secondLimit, third_limit thirdLimit, outside_limit outsideLimit, use_prop_name usePropName " +
    		" from fri_use_limit " + 
    		" where use_prop_id like concat(#{usePropId,jdbcType=VARCHAR},'%') " + 
    		"</script>")
    
    List<FriUseLimit> queryByUsePropId(@Param("usePropId") String usePropId);

 // 新增自留限額資料
    @Insert("<script> INSERT INTO fri_use_limit (use_prop_id,special1_limit,special2_limit, " +
    		" first_limit,second_limit,third_limit,outside_limit,use_prop_name) " +
    		" values(#{record.usePropId,jdbcType=VARCHAR},#{record.special1Limit,jdbcType=VARCHAR},#{record.special2Limit,jdbcType=VARCHAR}, " +
    		" #{record.firstLimit,jdbcType=VARCHAR},#{record.secondLimit,jdbcType=VARCHAR},#{record.thirdLimit,jdbcType=VARCHAR}, " +
    		" #{record.outsideLimit,jdbcType=VARCHAR},#{record.usePropName,jdbcType=VARCHAR}) " +
    		"</script>")
    
    int insertByPk(@Param("record") FriUseLimit model);

 // 刪除自留限額資料
    @Delete("<script> delete from fri_use_limit where "
    		+ "<foreach collection =\"record\" item = \"item\" index=\"index\" separator=\"or\">"
    		+ " use_prop_id = #{item.usePropId,jdbcType=VARCHAR}"
    		+ "</foreach></script>")
    
	int deleteFriUseLimit(@Param("record") List<FriUseLimit> record);
}