package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.PropName;
import com.asi.huanan.service.dao.mybatis.model.PropNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prop_name
     *
     * @mbg.generated Mon Dec 20 15:13:26 CST 2021
     */
    long countByExample(PropNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prop_name
     *
     * @mbg.generated Mon Dec 20 15:13:26 CST 2021
     */
    int deleteByExample(PropNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prop_name
     *
     * @mbg.generated Mon Dec 20 15:13:26 CST 2021
     */
    int insert(PropName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prop_name
     *
     * @mbg.generated Mon Dec 20 15:13:26 CST 2021
     */
    int insertSelective(PropName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prop_name
     *
     * @mbg.generated Mon Dec 20 15:13:26 CST 2021
     */
    List<PropName> selectByExample(PropNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prop_name
     *
     * @mbg.generated Mon Dec 20 15:13:26 CST 2021
     */
    int updateByExampleSelective(@Param("record") PropName record, @Param("example") PropNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prop_name
     *
     * @mbg.generated Mon Dec 20 15:13:26 CST 2021
     */
    int updateByExample(@Param("record") PropName record, @Param("example") PropNameExample example);
}