package com.asi.huanan.service.dao.mybatis.mapper;

import com.asi.huanan.service.dao.mybatis.model.Ricmpf1;
import com.asi.huanan.service.dao.mybatis.model.Ricmpf1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ricmpf1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ricmpf1
     *
     * @mbg.generated Sun Sep 26 17:15:40 CST 2021
     */
    long countByExample(Ricmpf1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ricmpf1
     *
     * @mbg.generated Sun Sep 26 17:15:40 CST 2021
     */
    int deleteByExample(Ricmpf1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ricmpf1
     *
     * @mbg.generated Sun Sep 26 17:15:40 CST 2021
     */
    int insert(Ricmpf1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ricmpf1
     *
     * @mbg.generated Sun Sep 26 17:15:40 CST 2021
     */
    int insertSelective(Ricmpf1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ricmpf1
     *
     * @mbg.generated Sun Sep 26 17:15:40 CST 2021
     */
    List<Ricmpf1> selectByExample(Ricmpf1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ricmpf1
     *
     * @mbg.generated Sun Sep 26 17:15:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") Ricmpf1 record, @Param("example") Ricmpf1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ricmpf1
     *
     * @mbg.generated Sun Sep 26 17:15:40 CST 2021
     */
    int updateByExample(@Param("record") Ricmpf1 record, @Param("example") Ricmpf1Example example);
}