package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.asi.huanan.service.dao.mybatis.model.Rin120603;
import com.asi.huanan.service.dao.mybatis.model.Rin120603Example;
import com.asi.huanan.vo.Rin1206AmountDataVO;

public interface Rin120603Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120603
     *
     * @mbg.generated Mon Dec 20 14:03:43 CST 2021
     */
    long countByExample(Rin120603Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120603
     *
     * @mbg.generated Mon Dec 20 14:03:43 CST 2021
     */
    int deleteByExample(Rin120603Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120603
     *
     * @mbg.generated Mon Dec 20 14:03:43 CST 2021
     */
    int insert(Rin120603 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120603
     *
     * @mbg.generated Mon Dec 20 14:03:43 CST 2021
     */
    int insertSelective(Rin120603 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120603
     *
     * @mbg.generated Mon Dec 20 14:03:43 CST 2021
     */
    List<Rin120603> selectByExample(Rin120603Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120603
     *
     * @mbg.generated Mon Dec 20 14:03:43 CST 2021
     */
    int updateByExampleSelective(@Param("record") Rin120603 record, @Param("example") Rin120603Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120603
     *
     * @mbg.generated Mon Dec 20 14:03:43 CST 2021
     */
    int updateByExample(@Param("record") Rin120603 record, @Param("example") Rin120603Example example);
    /**
     * rin1206rinComId by rptId
     * @param rptid
     * @return
     */
//    @Select("<script>"+
//    		"SELECT distinct rin_com_id from rin120603\r\n" + 
//    		"where rptid = #{rptid}" + 
//    		"</script>")
    @Select("<script> SELECT distinct rin_com_id from rin120603\r\n where rptid = #{rptid} </script>")
    List<String> queryRinComIDByrptId(@Param("rptid") Long rptid);
 
    /**
     * rin1206查各項費率
     * @param rptid
     * @return
     */
//    @Select("<script>"+
//    		"SELECT rin_com_id, SUM(share_prem) AS riprem,  SUM(comm) AS comm, SUM(busstax) AS businesstax, "+
//    		"0 AS stamptax,  0 AS handlingFee, 0 AS agent,SUM(loss) AS ripaid "+
//    		"FROM  rin120603 "+
//    		"WHERE rptid = #{rptid} " +
//    		"GROUP BY rin_com_id "+
//    		"ORDER BY rin_com_id "+
//    		"</script>")
    @Select("<script> SELECT rin_com_id, SUM(share_prem) AS riprem,  SUM(comm) AS comm, SUM(busstax) AS businesstax, 0 AS stamptax, 0 AS handlingFee, 0 AS agent,SUM(loss) AS ripaid FROM  rin120603 WHERE rptid = #{rptid} GROUP BY rin_com_id ORDER BY rin_com_id </script>")
    List<Rin1206AmountDataVO> queryAmountData(@Param("rptid") String rptid);
    
    //Rin120603 truncate table
    @Update("<script>"+
    		" update Rin120603 set Bill_no = #{billNo} " +
    		" WHERE rptid = #{rptid}"+
    		" and rin_com_id = #{sBroker}"+
    		"</script>")
    int updateBillNo(@Param("rptid")Long rptid, @Param("billNo")String billNo, @Param("sBroker")String sBroker);
    
    @Update("<script>"+
    		"TRUNCATE TABLE Rin120603"+
    		"</script>")
    void truncateTable();
    
    
}