package com.asi.huanan.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.asi.huanan.service.dao.mybatis.model.Rin120602;
import com.asi.huanan.service.dao.mybatis.model.Rin120602Example;

public interface Rin120602Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120602
     *
     * @mbg.generated Mon Dec 20 14:01:22 CST 2021
     */
    long countByExample(Rin120602Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120602
     *
     * @mbg.generated Mon Dec 20 14:01:22 CST 2021
     */
    int deleteByExample(Rin120602Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120602
     *
     * @mbg.generated Mon Dec 20 14:01:22 CST 2021
     */
    int insert(Rin120602 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120602
     *
     * @mbg.generated Mon Dec 20 14:01:22 CST 2021
     */
    int insertSelective(Rin120602 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120602
     *
     * @mbg.generated Mon Dec 20 14:01:22 CST 2021
     */
    List<Rin120602> selectByExample(Rin120602Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120602
     *
     * @mbg.generated Mon Dec 20 14:01:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") Rin120602 record, @Param("example") Rin120602Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIN120602
     *
     * @mbg.generated Mon Dec 20 14:01:22 CST 2021
     */
    int updateByExample(@Param("record") Rin120602 record, @Param("example") Rin120602Example example);
    
    //query Top1
//    @Select("<script>"+
//    		"Select top 1 treaty_prem as treatyPrem, seq FROM Rin120602 "+
//    		"where rptid = #{rptid} " +
//    		"</script>")
    @Select("<script> Select top 1 treaty_prem as treatyPrem, seq FROM Rin120602 where rptid = #{rptid} </script>")
    List<Rin120602> queryTop1(@Param("rptid") Long rptid);
    
    //update Bill_no
    @Update("<script>"+
    		" update Rin120602 set Bill_no = 'SET' " +
    		" WHERE rptid = #{rptid}"+
    		"</script>")
    int updateBillNo(@Param("rptid") Long rptid);
    
    //Rin120602 truncate table
    @Update("<script>"+
    		"TRUNCATE TABLE Rin120602"+
    		"</script>")
    void truncateTable();

    
}