package com.asi.mechanism.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SerialNumber {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERIAL_NUMBER.CREATE_DATE
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERIAL_NUMBER.DATE_STR
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    private String dateStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERIAL_NUMBER.RDN_NO
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    private BigDecimal rdnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERIAL_NUMBER.SERIAL_LEN
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    private BigDecimal serialLen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERIAL_NUMBER.PREP_NAME
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    private String prepName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERIAL_NUMBER.CREATE_DATE
     *
     * @return the value of SERIAL_NUMBER.CREATE_DATE
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERIAL_NUMBER.CREATE_DATE
     *
     * @param createDate the value for SERIAL_NUMBER.CREATE_DATE
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERIAL_NUMBER.DATE_STR
     *
     * @return the value of SERIAL_NUMBER.DATE_STR
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public String getDateStr() {
        return dateStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERIAL_NUMBER.DATE_STR
     *
     * @param dateStr the value for SERIAL_NUMBER.DATE_STR
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public void setDateStr(String dateStr) {
        this.dateStr = dateStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERIAL_NUMBER.RDN_NO
     *
     * @return the value of SERIAL_NUMBER.RDN_NO
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public BigDecimal getRdnNo() {
        return rdnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERIAL_NUMBER.RDN_NO
     *
     * @param rdnNo the value for SERIAL_NUMBER.RDN_NO
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public void setRdnNo(BigDecimal rdnNo) {
        this.rdnNo = rdnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERIAL_NUMBER.SERIAL_LEN
     *
     * @return the value of SERIAL_NUMBER.SERIAL_LEN
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public BigDecimal getSerialLen() {
        return serialLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERIAL_NUMBER.SERIAL_LEN
     *
     * @param serialLen the value for SERIAL_NUMBER.SERIAL_LEN
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public void setSerialLen(BigDecimal serialLen) {
        this.serialLen = serialLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERIAL_NUMBER.PREP_NAME
     *
     * @return the value of SERIAL_NUMBER.PREP_NAME
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public String getPrepName() {
        return prepName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERIAL_NUMBER.PREP_NAME
     *
     * @param prepName the value for SERIAL_NUMBER.PREP_NAME
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    public void setPrepName(String prepName) {
        this.prepName = prepName;
    }
}