package com.asi.mechanism.service.dao.mybatis.model;

import java.util.Date;

public class SysAccessRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.acc_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private String accUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.acc_log
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private String accLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.acc_msg
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private String accMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.acc_time
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private Date accTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.crt_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private String crtUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.crt_date
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private Date crtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.entry_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private String entryUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access_record.entry_date
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.acc_userid
     *
     * @return the value of sys_access_record.acc_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public String getAccUserid() {
        return accUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.acc_userid
     *
     * @param accUserid the value for sys_access_record.acc_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setAccUserid(String accUserid) {
        this.accUserid = accUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.acc_log
     *
     * @return the value of sys_access_record.acc_log
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public String getAccLog() {
        return accLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.acc_log
     *
     * @param accLog the value for sys_access_record.acc_log
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setAccLog(String accLog) {
        this.accLog = accLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.acc_msg
     *
     * @return the value of sys_access_record.acc_msg
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public String getAccMsg() {
        return accMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.acc_msg
     *
     * @param accMsg the value for sys_access_record.acc_msg
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setAccMsg(String accMsg) {
        this.accMsg = accMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.acc_time
     *
     * @return the value of sys_access_record.acc_time
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public Date getAccTime() {
        return accTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.acc_time
     *
     * @param accTime the value for sys_access_record.acc_time
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setAccTime(Date accTime) {
        this.accTime = accTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.crt_userid
     *
     * @return the value of sys_access_record.crt_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public String getCrtUserid() {
        return crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.crt_userid
     *
     * @param crtUserid the value for sys_access_record.crt_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setCrtUserid(String crtUserid) {
        this.crtUserid = crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.crt_date
     *
     * @return the value of sys_access_record.crt_date
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.crt_date
     *
     * @param crtDate the value for sys_access_record.crt_date
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.entry_userid
     *
     * @return the value of sys_access_record.entry_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public String getEntryUserid() {
        return entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.entry_userid
     *
     * @param entryUserid the value for sys_access_record.entry_userid
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setEntryUserid(String entryUserid) {
        this.entryUserid = entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_record.entry_date
     *
     * @return the value of sys_access_record.entry_date
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_record.entry_date
     *
     * @param entryDate the value for sys_access_record.entry_date
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}