package com.asi.mechanism.service.dao.mybatis.model;

import java.util.Date;

public class SysAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String akaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.user_name
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.deptid
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.cipher
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String cipher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.status
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.mail
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.error
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private Integer error;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.areaid
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.enable_mark
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String enableMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.crt_aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String crtAkaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.crt_date
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private Date crtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.entry_aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private String entryAkaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.entry_date
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.aka_id
     *
     * @return the value of sys_account.aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getAkaId() {
        return akaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.aka_id
     *
     * @param akaId the value for sys_account.aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setAkaId(String akaId) {
        this.akaId = akaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.user_name
     *
     * @return the value of sys_account.user_name
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.user_name
     *
     * @param userName the value for sys_account.user_name
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.deptid
     *
     * @return the value of sys_account.deptid
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.deptid
     *
     * @param deptid the value for sys_account.deptid
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.cipher
     *
     * @return the value of sys_account.cipher
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getCipher() {
        return cipher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.cipher
     *
     * @param cipher the value for sys_account.cipher
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setCipher(String cipher) {
        this.cipher = cipher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.status
     *
     * @return the value of sys_account.status
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.status
     *
     * @param status the value for sys_account.status
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.mail
     *
     * @return the value of sys_account.mail
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.mail
     *
     * @param mail the value for sys_account.mail
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.error
     *
     * @return the value of sys_account.error
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public Integer getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.error
     *
     * @param error the value for sys_account.error
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setError(Integer error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.areaid
     *
     * @return the value of sys_account.areaid
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.areaid
     *
     * @param areaid the value for sys_account.areaid
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.enable_mark
     *
     * @return the value of sys_account.enable_mark
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getEnableMark() {
        return enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.enable_mark
     *
     * @param enableMark the value for sys_account.enable_mark
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setEnableMark(String enableMark) {
        this.enableMark = enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.crt_aka_id
     *
     * @return the value of sys_account.crt_aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getCrtAkaId() {
        return crtAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.crt_aka_id
     *
     * @param crtAkaId the value for sys_account.crt_aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setCrtAkaId(String crtAkaId) {
        this.crtAkaId = crtAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.crt_date
     *
     * @return the value of sys_account.crt_date
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.crt_date
     *
     * @param crtDate the value for sys_account.crt_date
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.entry_aka_id
     *
     * @return the value of sys_account.entry_aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public String getEntryAkaId() {
        return entryAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.entry_aka_id
     *
     * @param entryAkaId the value for sys_account.entry_aka_id
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setEntryAkaId(String entryAkaId) {
        this.entryAkaId = entryAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.entry_date
     *
     * @return the value of sys_account.entry_date
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.entry_date
     *
     * @param entryDate the value for sys_account.entry_date
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}