package com.asi.mechanism.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysFunctionRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.USER_ROLE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.FUNCTION_UI_BUTTON_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private BigDecimal functionUiButtonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.FUNCTION_UI_FIELD_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private BigDecimal functionUiFieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.MENU_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private BigDecimal menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.ENABLE_MARK
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private String enableMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.CRT_USERID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private String crtUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.CRT_DATE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private Date crtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.ENTRY_USERID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private String entryUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FUNCTION_ROLE.ENTRY_DATE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.USER_ROLE
     *
     * @return the value of SYS_FUNCTION_ROLE.USER_ROLE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.USER_ROLE
     *
     * @param userRole the value for SYS_FUNCTION_ROLE.USER_ROLE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.FUNCTION_UI_BUTTON_ID
     *
     * @return the value of SYS_FUNCTION_ROLE.FUNCTION_UI_BUTTON_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public BigDecimal getFunctionUiButtonId() {
        return functionUiButtonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.FUNCTION_UI_BUTTON_ID
     *
     * @param functionUiButtonId the value for SYS_FUNCTION_ROLE.FUNCTION_UI_BUTTON_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setFunctionUiButtonId(BigDecimal functionUiButtonId) {
        this.functionUiButtonId = functionUiButtonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.FUNCTION_UI_FIELD_ID
     *
     * @return the value of SYS_FUNCTION_ROLE.FUNCTION_UI_FIELD_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public BigDecimal getFunctionUiFieldId() {
        return functionUiFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.FUNCTION_UI_FIELD_ID
     *
     * @param functionUiFieldId the value for SYS_FUNCTION_ROLE.FUNCTION_UI_FIELD_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setFunctionUiFieldId(BigDecimal functionUiFieldId) {
        this.functionUiFieldId = functionUiFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.MENU_ID
     *
     * @return the value of SYS_FUNCTION_ROLE.MENU_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public BigDecimal getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.MENU_ID
     *
     * @param menuId the value for SYS_FUNCTION_ROLE.MENU_ID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setMenuId(BigDecimal menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.ENABLE_MARK
     *
     * @return the value of SYS_FUNCTION_ROLE.ENABLE_MARK
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public String getEnableMark() {
        return enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.ENABLE_MARK
     *
     * @param enableMark the value for SYS_FUNCTION_ROLE.ENABLE_MARK
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setEnableMark(String enableMark) {
        this.enableMark = enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.CRT_USERID
     *
     * @return the value of SYS_FUNCTION_ROLE.CRT_USERID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public String getCrtUserid() {
        return crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.CRT_USERID
     *
     * @param crtUserid the value for SYS_FUNCTION_ROLE.CRT_USERID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setCrtUserid(String crtUserid) {
        this.crtUserid = crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.CRT_DATE
     *
     * @return the value of SYS_FUNCTION_ROLE.CRT_DATE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.CRT_DATE
     *
     * @param crtDate the value for SYS_FUNCTION_ROLE.CRT_DATE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.ENTRY_USERID
     *
     * @return the value of SYS_FUNCTION_ROLE.ENTRY_USERID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public String getEntryUserid() {
        return entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.ENTRY_USERID
     *
     * @param entryUserid the value for SYS_FUNCTION_ROLE.ENTRY_USERID
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setEntryUserid(String entryUserid) {
        this.entryUserid = entryUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FUNCTION_ROLE.ENTRY_DATE
     *
     * @return the value of SYS_FUNCTION_ROLE.ENTRY_DATE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FUNCTION_ROLE.ENTRY_DATE
     *
     * @param entryDate the value for SYS_FUNCTION_ROLE.ENTRY_DATE
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}