package com.asi.mechanism.service.dao.mybatis.model;

import java.math.BigDecimal;

public class SysFuncUiFieldKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func_ui_field.menu_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private BigDecimal menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func_ui_field.field_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String fieldId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func_ui_field.menu_id
     *
     * @return the value of sys_func_ui_field.menu_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public BigDecimal getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func_ui_field.menu_id
     *
     * @param menuId the value for sys_func_ui_field.menu_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setMenuId(BigDecimal menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func_ui_field.field_id
     *
     * @return the value of sys_func_ui_field.field_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func_ui_field.field_id
     *
     * @param fieldId the value for sys_func_ui_field.field_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }
}