package com.asi.mechanism.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysMenuRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.user_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.menu_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private BigDecimal menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.enable_mark
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String enableMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.crt_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String crtAkaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.crt_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private Date crtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.entry_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String entryAkaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.entry_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.user_role
     *
     * @return the value of sys_menu_role.user_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.user_role
     *
     * @param userRole the value for sys_menu_role.user_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.menu_id
     *
     * @return the value of sys_menu_role.menu_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public BigDecimal getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.menu_id
     *
     * @param menuId the value for sys_menu_role.menu_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setMenuId(BigDecimal menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.enable_mark
     *
     * @return the value of sys_menu_role.enable_mark
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getEnableMark() {
        return enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.enable_mark
     *
     * @param enableMark the value for sys_menu_role.enable_mark
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setEnableMark(String enableMark) {
        this.enableMark = enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.crt_aka_id
     *
     * @return the value of sys_menu_role.crt_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getCrtAkaId() {
        return crtAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.crt_aka_id
     *
     * @param crtAkaId the value for sys_menu_role.crt_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setCrtAkaId(String crtAkaId) {
        this.crtAkaId = crtAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.crt_date
     *
     * @return the value of sys_menu_role.crt_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.crt_date
     *
     * @param crtDate the value for sys_menu_role.crt_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.entry_aka_id
     *
     * @return the value of sys_menu_role.entry_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getEntryAkaId() {
        return entryAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.entry_aka_id
     *
     * @param entryAkaId the value for sys_menu_role.entry_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setEntryAkaId(String entryAkaId) {
        this.entryAkaId = entryAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.entry_date
     *
     * @return the value of sys_menu_role.entry_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.entry_date
     *
     * @param entryDate the value for sys_menu_role.entry_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}