package com.asi.mechanism.service.dao.mybatis.model;

import java.util.Date;

public class SysUserPersonal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String akaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.page_bg
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String pageBg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.crt_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String crtAkaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.crt_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private Date crtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.entry_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private String entryAkaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_personal.entry_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.aka_id
     *
     * @return the value of sys_user_personal.aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getAkaId() {
        return akaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.aka_id
     *
     * @param akaId the value for sys_user_personal.aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setAkaId(String akaId) {
        this.akaId = akaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.page_bg
     *
     * @return the value of sys_user_personal.page_bg
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getPageBg() {
        return pageBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.page_bg
     *
     * @param pageBg the value for sys_user_personal.page_bg
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setPageBg(String pageBg) {
        this.pageBg = pageBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.crt_aka_id
     *
     * @return the value of sys_user_personal.crt_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getCrtAkaId() {
        return crtAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.crt_aka_id
     *
     * @param crtAkaId the value for sys_user_personal.crt_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setCrtAkaId(String crtAkaId) {
        this.crtAkaId = crtAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.crt_date
     *
     * @return the value of sys_user_personal.crt_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.crt_date
     *
     * @param crtDate the value for sys_user_personal.crt_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.entry_aka_id
     *
     * @return the value of sys_user_personal.entry_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public String getEntryAkaId() {
        return entryAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.entry_aka_id
     *
     * @param entryAkaId the value for sys_user_personal.entry_aka_id
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setEntryAkaId(String entryAkaId) {
        this.entryAkaId = entryAkaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_personal.entry_date
     *
     * @return the value of sys_user_personal.entry_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_personal.entry_date
     *
     * @param entryDate the value for sys_user_personal.entry_date
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}