spring:
   #此設定檔之設定可視為sit、uat、prod為同一環境，因均使用k8s或ocp等雲端平台，可使用環境變數切換設定
   config:
    activate:
      on-profile: k8s
   datasource:
      first:
         url: ${DB1_URL}
         username: ${DB1_USERNAME}
         password: ${DB1_PASSWORD}
         driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
         hikari:
            minimum-idle: 10
            maximum-pool-size: 25
            auto-commit: true
            idle-timeout: 35000
            pool-name: ExpendHikariCP
            max-lifetime: 288000000
            connection-timeout: 60000
            connection-test-query: SELECT 1
            keepaliveTime: 30000
      second:
         url: ${DB2_URL}
         username: ${DB2_USERNAME}
         password: ${DB2_PASSWORD}
         driver-class-name: com.informix.jdbc.IfxDriver
         hikari:
            minimum-idle: 10
            maximum-pool-size: 25
            auto-commit: true
            idle-timeout: 235000
            pool-name: ExpendHikariCP2
            max-lifetime: 288000000
            connection-timeout: 120000
            connection-test-query: select count(*) from (select FIRST 1 owner_id from tapo)
            keepaliveTime: 990000
      third:
         url: 'jdbc:sqlite::memory:'
         #url: 'jdbc:sqlite:litedb.db'
         username: 
         password: 
         driver-class-name: org.sqlite.JDBC
         hikari:
            minimum-idle: 10
            maximum-pool-size: 25
            auto-commit: true
            idle-timeout: 35000
            pool-name: ExpendHikariCP3
            max-lifetime: 288000000
            connection-timeout: 30000
            connection-test-query: select 1
            keepaliveTime: 30000
#   devtools:
#      livereload:
#         port:  35731
environments:
   security:
      #CORS開關，注意正式環境需關閉，true:關閉CORS阻擋的問題
      allowCors:
         switcher: ${ALLOW_CORS}
         #switcher: false
   project:
      name: qrysys
      url: ${PROJECT_DOMAIN}
      protocol: ${PROTOCOL}
      serviceType: frontend
      #authorization的內容均為空，則專案將會自我產生token並自我檢查token
      authorization:
         server: 
            domain: 
            authen: 
            checktoken: 
            refreshtoken: 
            refreshtokenchecktime: 
            #種類:空-須加密密碼、ldap-無須加密密碼
            type: 
         #server: 
         #   domain: ${AUTH_DOMAIN}
         #   #domain: http://asiauthah-south-china.apps.ocp45.asgard.com.tw
         #   authen: /authorization/authen
         #   checktoken: /authorization/checktoken
         #   refreshtoken: /authorization/authen/refresh
         v   refreshtokenchecktime: /authorization/authen/refresh/checktime
         #   #種類:空-須加密密碼、ldap-無須加密密碼
         #   type: ldap
server: 
   port: 10127
authentication:
  #category: tradition
  category: spring_security
  tradition:
    verify:
      type: db_access
      #type: webservice
ldap:
  base:
    dn:
    - dc=asgard,dc=test,dc=com
    - ou=Users_Java,dc=asgard,dc=test,dc=com
    server:
      domainName: asgard.test.com
  factory: com.sun.jndi.ldap.LdapCtxFactory
  urls: ldap://192.168.5.209:389/