package com.asi.huanan.service.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BatchqueueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public BatchqueueExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskidIsNull() {
            addCriterion("TaskID is null");
            return (Criteria) this;
        }

        public Criteria andTaskidIsNotNull() {
            addCriterion("TaskID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskidEqualTo(String value) {
            addCriterion("TaskID =", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotEqualTo(String value) {
            addCriterion("TaskID <>", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThan(String value) {
            addCriterion("TaskID >", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThanOrEqualTo(String value) {
            addCriterion("TaskID >=", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLessThan(String value) {
            addCriterion("TaskID <", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLessThanOrEqualTo(String value) {
            addCriterion("TaskID <=", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLike(String value) {
            addCriterion("TaskID like", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotLike(String value) {
            addCriterion("TaskID not like", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidIn(List<String> values) {
            addCriterion("TaskID in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotIn(List<String> values) {
            addCriterion("TaskID not in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidBetween(String value1, String value2) {
            addCriterion("TaskID between", value1, value2, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotBetween(String value1, String value2) {
            addCriterion("TaskID not between", value1, value2, "taskid");
            return (Criteria) this;
        }

        public Criteria andBatchidIsNull() {
            addCriterion("BatchID is null");
            return (Criteria) this;
        }

        public Criteria andBatchidIsNotNull() {
            addCriterion("BatchID is not null");
            return (Criteria) this;
        }

        public Criteria andBatchidEqualTo(String value) {
            addCriterion("BatchID =", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotEqualTo(String value) {
            addCriterion("BatchID <>", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidGreaterThan(String value) {
            addCriterion("BatchID >", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidGreaterThanOrEqualTo(String value) {
            addCriterion("BatchID >=", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidLessThan(String value) {
            addCriterion("BatchID <", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidLessThanOrEqualTo(String value) {
            addCriterion("BatchID <=", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidLike(String value) {
            addCriterion("BatchID like", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotLike(String value) {
            addCriterion("BatchID not like", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidIn(List<String> values) {
            addCriterion("BatchID in", values, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotIn(List<String> values) {
            addCriterion("BatchID not in", values, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidBetween(String value1, String value2) {
            addCriterion("BatchID between", value1, value2, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotBetween(String value1, String value2) {
            addCriterion("BatchID not between", value1, value2, "batchid");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIsNull() {
            addCriterion("SubmitTime is null");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIsNotNull() {
            addCriterion("SubmitTime is not null");
            return (Criteria) this;
        }

        public Criteria andSubmittimeEqualTo(Date value) {
            addCriterion("SubmitTime =", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotEqualTo(Date value) {
            addCriterion("SubmitTime <>", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeGreaterThan(Date value) {
            addCriterion("SubmitTime >", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SubmitTime >=", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeLessThan(Date value) {
            addCriterion("SubmitTime <", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeLessThanOrEqualTo(Date value) {
            addCriterion("SubmitTime <=", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIn(List<Date> values) {
            addCriterion("SubmitTime in", values, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotIn(List<Date> values) {
            addCriterion("SubmitTime not in", values, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeBetween(Date value1, Date value2) {
            addCriterion("SubmitTime between", value1, value2, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotBetween(Date value1, Date value2) {
            addCriterion("SubmitTime not between", value1, value2, "submittime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("StartTime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("StartTime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("StartTime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("StartTime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("StartTime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("StartTime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("StartTime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("StartTime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("StartTime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("StartTime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("StartTime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("StartTime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("EndTime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("EndTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("EndTime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("EndTime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("EndTime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("EndTime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("EndTime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("EndTime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("EndTime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("EndTime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("EndTime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("EndTime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIsNull() {
            addCriterion("ProcessStatus is null");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIsNotNull() {
            addCriterion("ProcessStatus is not null");
            return (Criteria) this;
        }

        public Criteria andProcessstatusEqualTo(Byte value) {
            addCriterion("ProcessStatus =", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotEqualTo(Byte value) {
            addCriterion("ProcessStatus <>", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusGreaterThan(Byte value) {
            addCriterion("ProcessStatus >", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("ProcessStatus >=", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusLessThan(Byte value) {
            addCriterion("ProcessStatus <", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusLessThanOrEqualTo(Byte value) {
            addCriterion("ProcessStatus <=", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIn(List<Byte> values) {
            addCriterion("ProcessStatus in", values, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotIn(List<Byte> values) {
            addCriterion("ProcessStatus not in", values, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusBetween(Byte value1, Byte value2) {
            addCriterion("ProcessStatus between", value1, value2, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotBetween(Byte value1, Byte value2) {
            addCriterion("ProcessStatus not between", value1, value2, "processstatus");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("Account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("Account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("Account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("Account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("Account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("Account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("Account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("Account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("Account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("Account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("Account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("Account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("Account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("Account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidIsNull() {
            addCriterion("ProcessControlID is null");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidIsNotNull() {
            addCriterion("ProcessControlID is not null");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidEqualTo(String value) {
            addCriterion("ProcessControlID =", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidNotEqualTo(String value) {
            addCriterion("ProcessControlID <>", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidGreaterThan(String value) {
            addCriterion("ProcessControlID >", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidGreaterThanOrEqualTo(String value) {
            addCriterion("ProcessControlID >=", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidLessThan(String value) {
            addCriterion("ProcessControlID <", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidLessThanOrEqualTo(String value) {
            addCriterion("ProcessControlID <=", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidLike(String value) {
            addCriterion("ProcessControlID like", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidNotLike(String value) {
            addCriterion("ProcessControlID not like", value, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidIn(List<String> values) {
            addCriterion("ProcessControlID in", values, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidNotIn(List<String> values) {
            addCriterion("ProcessControlID not in", values, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidBetween(String value1, String value2) {
            addCriterion("ProcessControlID between", value1, value2, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andProcesscontrolidNotBetween(String value1, String value2) {
            addCriterion("ProcessControlID not between", value1, value2, "processcontrolid");
            return (Criteria) this;
        }

        public Criteria andExitcodeIsNull() {
            addCriterion("ExitCode is null");
            return (Criteria) this;
        }

        public Criteria andExitcodeIsNotNull() {
            addCriterion("ExitCode is not null");
            return (Criteria) this;
        }

        public Criteria andExitcodeEqualTo(String value) {
            addCriterion("ExitCode =", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeNotEqualTo(String value) {
            addCriterion("ExitCode <>", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeGreaterThan(String value) {
            addCriterion("ExitCode >", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ExitCode >=", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeLessThan(String value) {
            addCriterion("ExitCode <", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeLessThanOrEqualTo(String value) {
            addCriterion("ExitCode <=", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeLike(String value) {
            addCriterion("ExitCode like", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeNotLike(String value) {
            addCriterion("ExitCode not like", value, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeIn(List<String> values) {
            addCriterion("ExitCode in", values, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeNotIn(List<String> values) {
            addCriterion("ExitCode not in", values, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeBetween(String value1, String value2) {
            addCriterion("ExitCode between", value1, value2, "exitcode");
            return (Criteria) this;
        }

        public Criteria andExitcodeNotBetween(String value1, String value2) {
            addCriterion("ExitCode not between", value1, value2, "exitcode");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathIsNull() {
            addCriterion("BatchReprotAccessPath is null");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathIsNotNull() {
            addCriterion("BatchReprotAccessPath is not null");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathEqualTo(String value) {
            addCriterion("BatchReprotAccessPath =", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathNotEqualTo(String value) {
            addCriterion("BatchReprotAccessPath <>", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathGreaterThan(String value) {
            addCriterion("BatchReprotAccessPath >", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathGreaterThanOrEqualTo(String value) {
            addCriterion("BatchReprotAccessPath >=", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathLessThan(String value) {
            addCriterion("BatchReprotAccessPath <", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathLessThanOrEqualTo(String value) {
            addCriterion("BatchReprotAccessPath <=", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathLike(String value) {
            addCriterion("BatchReprotAccessPath like", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathNotLike(String value) {
            addCriterion("BatchReprotAccessPath not like", value, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathIn(List<String> values) {
            addCriterion("BatchReprotAccessPath in", values, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathNotIn(List<String> values) {
            addCriterion("BatchReprotAccessPath not in", values, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathBetween(String value1, String value2) {
            addCriterion("BatchReprotAccessPath between", value1, value2, "batchreprotaccesspath");
            return (Criteria) this;
        }

        public Criteria andBatchreprotaccesspathNotBetween(String value1, String value2) {
            addCriterion("BatchReprotAccessPath not between", value1, value2, "batchreprotaccesspath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table batchqueue
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 06 15:20:23 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table batchqueue
     *
     * @mbg.generated Mon Dec 06 15:20:23 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}