package com.asi.huanan.service.dao.mybatis.model;

public class ComAutonumKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_autonum.company_code
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_autonum.function_id
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    private String functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_autonum.operate_type
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_autonum.number_code
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    private String numberCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_autonum.num_year
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    private String numYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_autonum.num_month
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    private String numMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_autonum.num_day
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    private String numDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_autonum.company_code
     *
     * @return the value of com_autonum.company_code
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_autonum.company_code
     *
     * @param companyCode the value for com_autonum.company_code
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_autonum.function_id
     *
     * @return the value of com_autonum.function_id
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_autonum.function_id
     *
     * @param functionId the value for com_autonum.function_id
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_autonum.operate_type
     *
     * @return the value of com_autonum.operate_type
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_autonum.operate_type
     *
     * @param operateType the value for com_autonum.operate_type
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_autonum.number_code
     *
     * @return the value of com_autonum.number_code
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public String getNumberCode() {
        return numberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_autonum.number_code
     *
     * @param numberCode the value for com_autonum.number_code
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public void setNumberCode(String numberCode) {
        this.numberCode = numberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_autonum.num_year
     *
     * @return the value of com_autonum.num_year
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public String getNumYear() {
        return numYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_autonum.num_year
     *
     * @param numYear the value for com_autonum.num_year
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public void setNumYear(String numYear) {
        this.numYear = numYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_autonum.num_month
     *
     * @return the value of com_autonum.num_month
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public String getNumMonth() {
        return numMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_autonum.num_month
     *
     * @param numMonth the value for com_autonum.num_month
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public void setNumMonth(String numMonth) {
        this.numMonth = numMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_autonum.num_day
     *
     * @return the value of com_autonum.num_day
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public String getNumDay() {
        return numDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_autonum.num_day
     *
     * @param numDay the value for com_autonum.num_day
     *
     * @mbg.generated Wed Nov 24 14:30:27 CST 2021
     */
    public void setNumDay(String numDay) {
        this.numDay = numDay;
    }
}