package com.asi.huanan.service.dao.mybatis.model;

public class FriAccountingKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_accounting.bill_no
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    private String billNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_accounting.rin_com_id
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    private String rinComId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_accounting.amend_seq
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    private Short amendSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_accounting.broker_id
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    private String brokerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_accounting.rin_com_id_OLD
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    private String rinComIdOld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_accounting.broker_id_OLD
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    private String brokerIdOld;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_accounting.bill_no
     *
     * @return the value of fri_accounting.bill_no
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_accounting.bill_no
     *
     * @param billNo the value for fri_accounting.bill_no
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_accounting.rin_com_id
     *
     * @return the value of fri_accounting.rin_com_id
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public String getRinComId() {
        return rinComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_accounting.rin_com_id
     *
     * @param rinComId the value for fri_accounting.rin_com_id
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public void setRinComId(String rinComId) {
        this.rinComId = rinComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_accounting.amend_seq
     *
     * @return the value of fri_accounting.amend_seq
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public Short getAmendSeq() {
        return amendSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_accounting.amend_seq
     *
     * @param amendSeq the value for fri_accounting.amend_seq
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public void setAmendSeq(Short amendSeq) {
        this.amendSeq = amendSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_accounting.broker_id
     *
     * @return the value of fri_accounting.broker_id
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public String getBrokerId() {
        return brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_accounting.broker_id
     *
     * @param brokerId the value for fri_accounting.broker_id
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public void setBrokerId(String brokerId) {
        this.brokerId = brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_accounting.rin_com_id_OLD
     *
     * @return the value of fri_accounting.rin_com_id_OLD
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public String getRinComIdOld() {
        return rinComIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_accounting.rin_com_id_OLD
     *
     * @param rinComIdOld the value for fri_accounting.rin_com_id_OLD
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public void setRinComIdOld(String rinComIdOld) {
        this.rinComIdOld = rinComIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_accounting.broker_id_OLD
     *
     * @return the value of fri_accounting.broker_id_OLD
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public String getBrokerIdOld() {
        return brokerIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_accounting.broker_id_OLD
     *
     * @param brokerIdOld the value for fri_accounting.broker_id_OLD
     *
     * @mbg.generated Wed Dec 01 10:33:52 CST 2021
     */
    public void setBrokerIdOld(String brokerIdOld) {
        this.brokerIdOld = brokerIdOld;
    }
}