package com.asi.huanan.service.dao.mybatis.model;

public class FriFacSamerisk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.slip_no
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String slipNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.samerisk20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String samerisk20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.policy20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String policy20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_samerisk.endorse20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    private String endorse20;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.slip_no
     *
     * @return the value of fri_fac_samerisk.slip_no
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSlipNo() {
        return slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.slip_no
     *
     * @param slipNo the value for fri_fac_samerisk.slip_no
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSlipNo(String slipNo) {
        this.slipNo = slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk1
     *
     * @return the value of fri_fac_samerisk.samerisk1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk1() {
        return samerisk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk1
     *
     * @param samerisk1 the value for fri_fac_samerisk.samerisk1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk1(String samerisk1) {
        this.samerisk1 = samerisk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk2
     *
     * @return the value of fri_fac_samerisk.samerisk2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk2() {
        return samerisk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk2
     *
     * @param samerisk2 the value for fri_fac_samerisk.samerisk2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk2(String samerisk2) {
        this.samerisk2 = samerisk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk3
     *
     * @return the value of fri_fac_samerisk.samerisk3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk3() {
        return samerisk3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk3
     *
     * @param samerisk3 the value for fri_fac_samerisk.samerisk3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk3(String samerisk3) {
        this.samerisk3 = samerisk3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk4
     *
     * @return the value of fri_fac_samerisk.samerisk4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk4() {
        return samerisk4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk4
     *
     * @param samerisk4 the value for fri_fac_samerisk.samerisk4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk4(String samerisk4) {
        this.samerisk4 = samerisk4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk5
     *
     * @return the value of fri_fac_samerisk.samerisk5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk5() {
        return samerisk5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk5
     *
     * @param samerisk5 the value for fri_fac_samerisk.samerisk5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk5(String samerisk5) {
        this.samerisk5 = samerisk5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk6
     *
     * @return the value of fri_fac_samerisk.samerisk6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk6() {
        return samerisk6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk6
     *
     * @param samerisk6 the value for fri_fac_samerisk.samerisk6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk6(String samerisk6) {
        this.samerisk6 = samerisk6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk7
     *
     * @return the value of fri_fac_samerisk.samerisk7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk7() {
        return samerisk7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk7
     *
     * @param samerisk7 the value for fri_fac_samerisk.samerisk7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk7(String samerisk7) {
        this.samerisk7 = samerisk7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk8
     *
     * @return the value of fri_fac_samerisk.samerisk8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk8() {
        return samerisk8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk8
     *
     * @param samerisk8 the value for fri_fac_samerisk.samerisk8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk8(String samerisk8) {
        this.samerisk8 = samerisk8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk9
     *
     * @return the value of fri_fac_samerisk.samerisk9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk9() {
        return samerisk9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk9
     *
     * @param samerisk9 the value for fri_fac_samerisk.samerisk9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk9(String samerisk9) {
        this.samerisk9 = samerisk9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk10
     *
     * @return the value of fri_fac_samerisk.samerisk10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk10() {
        return samerisk10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk10
     *
     * @param samerisk10 the value for fri_fac_samerisk.samerisk10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk10(String samerisk10) {
        this.samerisk10 = samerisk10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk11
     *
     * @return the value of fri_fac_samerisk.samerisk11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk11() {
        return samerisk11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk11
     *
     * @param samerisk11 the value for fri_fac_samerisk.samerisk11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk11(String samerisk11) {
        this.samerisk11 = samerisk11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk12
     *
     * @return the value of fri_fac_samerisk.samerisk12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk12() {
        return samerisk12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk12
     *
     * @param samerisk12 the value for fri_fac_samerisk.samerisk12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk12(String samerisk12) {
        this.samerisk12 = samerisk12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk13
     *
     * @return the value of fri_fac_samerisk.samerisk13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk13() {
        return samerisk13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk13
     *
     * @param samerisk13 the value for fri_fac_samerisk.samerisk13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk13(String samerisk13) {
        this.samerisk13 = samerisk13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk14
     *
     * @return the value of fri_fac_samerisk.samerisk14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk14() {
        return samerisk14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk14
     *
     * @param samerisk14 the value for fri_fac_samerisk.samerisk14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk14(String samerisk14) {
        this.samerisk14 = samerisk14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy1
     *
     * @return the value of fri_fac_samerisk.policy1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy1() {
        return policy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy1
     *
     * @param policy1 the value for fri_fac_samerisk.policy1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy1(String policy1) {
        this.policy1 = policy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy2
     *
     * @return the value of fri_fac_samerisk.policy2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy2() {
        return policy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy2
     *
     * @param policy2 the value for fri_fac_samerisk.policy2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy2(String policy2) {
        this.policy2 = policy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy3
     *
     * @return the value of fri_fac_samerisk.policy3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy3() {
        return policy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy3
     *
     * @param policy3 the value for fri_fac_samerisk.policy3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy3(String policy3) {
        this.policy3 = policy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy4
     *
     * @return the value of fri_fac_samerisk.policy4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy4() {
        return policy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy4
     *
     * @param policy4 the value for fri_fac_samerisk.policy4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy4(String policy4) {
        this.policy4 = policy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy5
     *
     * @return the value of fri_fac_samerisk.policy5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy5() {
        return policy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy5
     *
     * @param policy5 the value for fri_fac_samerisk.policy5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy5(String policy5) {
        this.policy5 = policy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy6
     *
     * @return the value of fri_fac_samerisk.policy6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy6() {
        return policy6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy6
     *
     * @param policy6 the value for fri_fac_samerisk.policy6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy6(String policy6) {
        this.policy6 = policy6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy7
     *
     * @return the value of fri_fac_samerisk.policy7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy7() {
        return policy7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy7
     *
     * @param policy7 the value for fri_fac_samerisk.policy7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy7(String policy7) {
        this.policy7 = policy7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy8
     *
     * @return the value of fri_fac_samerisk.policy8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy8() {
        return policy8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy8
     *
     * @param policy8 the value for fri_fac_samerisk.policy8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy8(String policy8) {
        this.policy8 = policy8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy9
     *
     * @return the value of fri_fac_samerisk.policy9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy9() {
        return policy9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy9
     *
     * @param policy9 the value for fri_fac_samerisk.policy9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy9(String policy9) {
        this.policy9 = policy9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy10
     *
     * @return the value of fri_fac_samerisk.policy10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy10() {
        return policy10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy10
     *
     * @param policy10 the value for fri_fac_samerisk.policy10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy10(String policy10) {
        this.policy10 = policy10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse1
     *
     * @return the value of fri_fac_samerisk.endorse1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse1() {
        return endorse1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse1
     *
     * @param endorse1 the value for fri_fac_samerisk.endorse1
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse1(String endorse1) {
        this.endorse1 = endorse1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse2
     *
     * @return the value of fri_fac_samerisk.endorse2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse2() {
        return endorse2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse2
     *
     * @param endorse2 the value for fri_fac_samerisk.endorse2
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse2(String endorse2) {
        this.endorse2 = endorse2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse3
     *
     * @return the value of fri_fac_samerisk.endorse3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse3() {
        return endorse3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse3
     *
     * @param endorse3 the value for fri_fac_samerisk.endorse3
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse3(String endorse3) {
        this.endorse3 = endorse3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse4
     *
     * @return the value of fri_fac_samerisk.endorse4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse4() {
        return endorse4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse4
     *
     * @param endorse4 the value for fri_fac_samerisk.endorse4
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse4(String endorse4) {
        this.endorse4 = endorse4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse5
     *
     * @return the value of fri_fac_samerisk.endorse5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse5() {
        return endorse5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse5
     *
     * @param endorse5 the value for fri_fac_samerisk.endorse5
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse5(String endorse5) {
        this.endorse5 = endorse5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse6
     *
     * @return the value of fri_fac_samerisk.endorse6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse6() {
        return endorse6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse6
     *
     * @param endorse6 the value for fri_fac_samerisk.endorse6
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse6(String endorse6) {
        this.endorse6 = endorse6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse7
     *
     * @return the value of fri_fac_samerisk.endorse7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse7() {
        return endorse7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse7
     *
     * @param endorse7 the value for fri_fac_samerisk.endorse7
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse7(String endorse7) {
        this.endorse7 = endorse7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse8
     *
     * @return the value of fri_fac_samerisk.endorse8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse8() {
        return endorse8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse8
     *
     * @param endorse8 the value for fri_fac_samerisk.endorse8
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse8(String endorse8) {
        this.endorse8 = endorse8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse9
     *
     * @return the value of fri_fac_samerisk.endorse9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse9() {
        return endorse9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse9
     *
     * @param endorse9 the value for fri_fac_samerisk.endorse9
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse9(String endorse9) {
        this.endorse9 = endorse9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse10
     *
     * @return the value of fri_fac_samerisk.endorse10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse10() {
        return endorse10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse10
     *
     * @param endorse10 the value for fri_fac_samerisk.endorse10
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse10(String endorse10) {
        this.endorse10 = endorse10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk15
     *
     * @return the value of fri_fac_samerisk.samerisk15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk15() {
        return samerisk15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk15
     *
     * @param samerisk15 the value for fri_fac_samerisk.samerisk15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk15(String samerisk15) {
        this.samerisk15 = samerisk15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk16
     *
     * @return the value of fri_fac_samerisk.samerisk16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk16() {
        return samerisk16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk16
     *
     * @param samerisk16 the value for fri_fac_samerisk.samerisk16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk16(String samerisk16) {
        this.samerisk16 = samerisk16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk17
     *
     * @return the value of fri_fac_samerisk.samerisk17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk17() {
        return samerisk17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk17
     *
     * @param samerisk17 the value for fri_fac_samerisk.samerisk17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk17(String samerisk17) {
        this.samerisk17 = samerisk17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk18
     *
     * @return the value of fri_fac_samerisk.samerisk18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk18() {
        return samerisk18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk18
     *
     * @param samerisk18 the value for fri_fac_samerisk.samerisk18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk18(String samerisk18) {
        this.samerisk18 = samerisk18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk19
     *
     * @return the value of fri_fac_samerisk.samerisk19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk19() {
        return samerisk19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk19
     *
     * @param samerisk19 the value for fri_fac_samerisk.samerisk19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk19(String samerisk19) {
        this.samerisk19 = samerisk19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.samerisk20
     *
     * @return the value of fri_fac_samerisk.samerisk20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getSamerisk20() {
        return samerisk20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.samerisk20
     *
     * @param samerisk20 the value for fri_fac_samerisk.samerisk20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setSamerisk20(String samerisk20) {
        this.samerisk20 = samerisk20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy11
     *
     * @return the value of fri_fac_samerisk.policy11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy11() {
        return policy11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy11
     *
     * @param policy11 the value for fri_fac_samerisk.policy11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy11(String policy11) {
        this.policy11 = policy11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy12
     *
     * @return the value of fri_fac_samerisk.policy12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy12() {
        return policy12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy12
     *
     * @param policy12 the value for fri_fac_samerisk.policy12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy12(String policy12) {
        this.policy12 = policy12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy13
     *
     * @return the value of fri_fac_samerisk.policy13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy13() {
        return policy13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy13
     *
     * @param policy13 the value for fri_fac_samerisk.policy13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy13(String policy13) {
        this.policy13 = policy13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy14
     *
     * @return the value of fri_fac_samerisk.policy14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy14() {
        return policy14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy14
     *
     * @param policy14 the value for fri_fac_samerisk.policy14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy14(String policy14) {
        this.policy14 = policy14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy15
     *
     * @return the value of fri_fac_samerisk.policy15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy15() {
        return policy15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy15
     *
     * @param policy15 the value for fri_fac_samerisk.policy15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy15(String policy15) {
        this.policy15 = policy15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy16
     *
     * @return the value of fri_fac_samerisk.policy16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy16() {
        return policy16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy16
     *
     * @param policy16 the value for fri_fac_samerisk.policy16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy16(String policy16) {
        this.policy16 = policy16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy17
     *
     * @return the value of fri_fac_samerisk.policy17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy17() {
        return policy17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy17
     *
     * @param policy17 the value for fri_fac_samerisk.policy17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy17(String policy17) {
        this.policy17 = policy17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy18
     *
     * @return the value of fri_fac_samerisk.policy18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy18() {
        return policy18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy18
     *
     * @param policy18 the value for fri_fac_samerisk.policy18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy18(String policy18) {
        this.policy18 = policy18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy19
     *
     * @return the value of fri_fac_samerisk.policy19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy19() {
        return policy19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy19
     *
     * @param policy19 the value for fri_fac_samerisk.policy19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy19(String policy19) {
        this.policy19 = policy19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.policy20
     *
     * @return the value of fri_fac_samerisk.policy20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getPolicy20() {
        return policy20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.policy20
     *
     * @param policy20 the value for fri_fac_samerisk.policy20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setPolicy20(String policy20) {
        this.policy20 = policy20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse11
     *
     * @return the value of fri_fac_samerisk.endorse11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse11() {
        return endorse11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse11
     *
     * @param endorse11 the value for fri_fac_samerisk.endorse11
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse11(String endorse11) {
        this.endorse11 = endorse11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse12
     *
     * @return the value of fri_fac_samerisk.endorse12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse12() {
        return endorse12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse12
     *
     * @param endorse12 the value for fri_fac_samerisk.endorse12
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse12(String endorse12) {
        this.endorse12 = endorse12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse13
     *
     * @return the value of fri_fac_samerisk.endorse13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse13() {
        return endorse13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse13
     *
     * @param endorse13 the value for fri_fac_samerisk.endorse13
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse13(String endorse13) {
        this.endorse13 = endorse13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse14
     *
     * @return the value of fri_fac_samerisk.endorse14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse14() {
        return endorse14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse14
     *
     * @param endorse14 the value for fri_fac_samerisk.endorse14
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse14(String endorse14) {
        this.endorse14 = endorse14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse15
     *
     * @return the value of fri_fac_samerisk.endorse15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse15() {
        return endorse15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse15
     *
     * @param endorse15 the value for fri_fac_samerisk.endorse15
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse15(String endorse15) {
        this.endorse15 = endorse15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse16
     *
     * @return the value of fri_fac_samerisk.endorse16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse16() {
        return endorse16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse16
     *
     * @param endorse16 the value for fri_fac_samerisk.endorse16
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse16(String endorse16) {
        this.endorse16 = endorse16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse17
     *
     * @return the value of fri_fac_samerisk.endorse17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse17() {
        return endorse17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse17
     *
     * @param endorse17 the value for fri_fac_samerisk.endorse17
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse17(String endorse17) {
        this.endorse17 = endorse17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse18
     *
     * @return the value of fri_fac_samerisk.endorse18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse18() {
        return endorse18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse18
     *
     * @param endorse18 the value for fri_fac_samerisk.endorse18
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse18(String endorse18) {
        this.endorse18 = endorse18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse19
     *
     * @return the value of fri_fac_samerisk.endorse19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse19() {
        return endorse19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse19
     *
     * @param endorse19 the value for fri_fac_samerisk.endorse19
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse19(String endorse19) {
        this.endorse19 = endorse19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_samerisk.endorse20
     *
     * @return the value of fri_fac_samerisk.endorse20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public String getEndorse20() {
        return endorse20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_samerisk.endorse20
     *
     * @param endorse20 the value for fri_fac_samerisk.endorse20
     *
     * @mbg.generated Mon Jan 03 11:08:54 CST 2022
     */
    public void setEndorse20(String endorse20) {
        this.endorse20 = endorse20;
    }
}