package com.asi.huanan.service.dao.mybatis.model;

public class FriFacRateKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_rate.slip_no
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    private String slipNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac_rate.content
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_rate.slip_no
     *
     * @return the value of fri_fac_rate.slip_no
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    public String getSlipNo() {
        return slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_rate.slip_no
     *
     * @param slipNo the value for fri_fac_rate.slip_no
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    public void setSlipNo(String slipNo) {
        this.slipNo = slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac_rate.content
     *
     * @return the value of fri_fac_rate.content
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac_rate.content
     *
     * @param content the value for fri_fac_rate.content
     *
     * @mbg.generated Sun Jan 02 18:01:01 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }
}