package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class FriFac {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.slip_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String slipNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.slip_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String slipType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.cession_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String cessionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.pre_slip_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String preSlipNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.pre_cession_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String preCessionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.treaty_year
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String treatyYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.treaty_date
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Date treatyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.cession_name
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String cessionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.risk_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String riskNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.treaty_dbgn
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Date treatyDbgn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.treaty_dend
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Date treatyDend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.days
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Short days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.risk_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String riskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.deduct_desc
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String deductDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.policy_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String policyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.insurant
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String insurant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.address
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.use_prop
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String useProp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.construct
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String construct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.coverage
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String coverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.treaty_dprt
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Date treatyDprt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.acct_flag
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String acctFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.acct_dprt
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Date acctDprt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.limit_rate
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private BigDecimal limitRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.limit
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Long limit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.fac_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String facType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.excess_bgn
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Long excessBgn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.excess_limit
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Long excessLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.TreatySet
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String treatyset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.currency
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.currencyExchangeRate
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private BigDecimal currencyexchangerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.policy_no_seq
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String policyNoSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.LastUpdateDateTime
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private Date lastupdatedatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.LastUpdateAccount
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String lastupdateaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.LOG_seq
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String logSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_fac.mkovse
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    private String mkovse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.slip_no
     *
     * @return the value of fri_fac.slip_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getSlipNo() {
        return slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.slip_no
     *
     * @param slipNo the value for fri_fac.slip_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setSlipNo(String slipNo) {
        this.slipNo = slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.slip_type
     *
     * @return the value of fri_fac.slip_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getSlipType() {
        return slipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.slip_type
     *
     * @param slipType the value for fri_fac.slip_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setSlipType(String slipType) {
        this.slipType = slipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.cession_no
     *
     * @return the value of fri_fac.cession_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getCessionNo() {
        return cessionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.cession_no
     *
     * @param cessionNo the value for fri_fac.cession_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setCessionNo(String cessionNo) {
        this.cessionNo = cessionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.pre_slip_no
     *
     * @return the value of fri_fac.pre_slip_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getPreSlipNo() {
        return preSlipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.pre_slip_no
     *
     * @param preSlipNo the value for fri_fac.pre_slip_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setPreSlipNo(String preSlipNo) {
        this.preSlipNo = preSlipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.pre_cession_no
     *
     * @return the value of fri_fac.pre_cession_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getPreCessionNo() {
        return preCessionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.pre_cession_no
     *
     * @param preCessionNo the value for fri_fac.pre_cession_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setPreCessionNo(String preCessionNo) {
        this.preCessionNo = preCessionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.treaty_year
     *
     * @return the value of fri_fac.treaty_year
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getTreatyYear() {
        return treatyYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.treaty_year
     *
     * @param treatyYear the value for fri_fac.treaty_year
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setTreatyYear(String treatyYear) {
        this.treatyYear = treatyYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.treaty_date
     *
     * @return the value of fri_fac.treaty_date
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Date getTreatyDate() {
        return treatyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.treaty_date
     *
     * @param treatyDate the value for fri_fac.treaty_date
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setTreatyDate(Date treatyDate) {
        this.treatyDate = treatyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.cession_name
     *
     * @return the value of fri_fac.cession_name
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getCessionName() {
        return cessionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.cession_name
     *
     * @param cessionName the value for fri_fac.cession_name
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setCessionName(String cessionName) {
        this.cessionName = cessionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.risk_no
     *
     * @return the value of fri_fac.risk_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getRiskNo() {
        return riskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.risk_no
     *
     * @param riskNo the value for fri_fac.risk_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setRiskNo(String riskNo) {
        this.riskNo = riskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.treaty_dbgn
     *
     * @return the value of fri_fac.treaty_dbgn
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Date getTreatyDbgn() {
        return treatyDbgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.treaty_dbgn
     *
     * @param treatyDbgn the value for fri_fac.treaty_dbgn
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setTreatyDbgn(Date treatyDbgn) {
        this.treatyDbgn = treatyDbgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.treaty_dend
     *
     * @return the value of fri_fac.treaty_dend
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Date getTreatyDend() {
        return treatyDend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.treaty_dend
     *
     * @param treatyDend the value for fri_fac.treaty_dend
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setTreatyDend(Date treatyDend) {
        this.treatyDend = treatyDend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.days
     *
     * @return the value of fri_fac.days
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Short getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.days
     *
     * @param days the value for fri_fac.days
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setDays(Short days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.risk_type
     *
     * @return the value of fri_fac.risk_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getRiskType() {
        return riskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.risk_type
     *
     * @param riskType the value for fri_fac.risk_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setRiskType(String riskType) {
        this.riskType = riskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.deduct_desc
     *
     * @return the value of fri_fac.deduct_desc
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getDeductDesc() {
        return deductDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.deduct_desc
     *
     * @param deductDesc the value for fri_fac.deduct_desc
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setDeductDesc(String deductDesc) {
        this.deductDesc = deductDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.policy_no
     *
     * @return the value of fri_fac.policy_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.policy_no
     *
     * @param policyNo the value for fri_fac.policy_no
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.insurant
     *
     * @return the value of fri_fac.insurant
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getInsurant() {
        return insurant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.insurant
     *
     * @param insurant the value for fri_fac.insurant
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setInsurant(String insurant) {
        this.insurant = insurant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.address
     *
     * @return the value of fri_fac.address
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.address
     *
     * @param address the value for fri_fac.address
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.use_prop
     *
     * @return the value of fri_fac.use_prop
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getUseProp() {
        return useProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.use_prop
     *
     * @param useProp the value for fri_fac.use_prop
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setUseProp(String useProp) {
        this.useProp = useProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.construct
     *
     * @return the value of fri_fac.construct
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getConstruct() {
        return construct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.construct
     *
     * @param construct the value for fri_fac.construct
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setConstruct(String construct) {
        this.construct = construct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.coverage
     *
     * @return the value of fri_fac.coverage
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.coverage
     *
     * @param coverage the value for fri_fac.coverage
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setCoverage(String coverage) {
        this.coverage = coverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.treaty_dprt
     *
     * @return the value of fri_fac.treaty_dprt
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Date getTreatyDprt() {
        return treatyDprt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.treaty_dprt
     *
     * @param treatyDprt the value for fri_fac.treaty_dprt
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setTreatyDprt(Date treatyDprt) {
        this.treatyDprt = treatyDprt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.acct_flag
     *
     * @return the value of fri_fac.acct_flag
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getAcctFlag() {
        return acctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.acct_flag
     *
     * @param acctFlag the value for fri_fac.acct_flag
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setAcctFlag(String acctFlag) {
        this.acctFlag = acctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.acct_dprt
     *
     * @return the value of fri_fac.acct_dprt
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Date getAcctDprt() {
        return acctDprt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.acct_dprt
     *
     * @param acctDprt the value for fri_fac.acct_dprt
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setAcctDprt(Date acctDprt) {
        this.acctDprt = acctDprt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.limit_rate
     *
     * @return the value of fri_fac.limit_rate
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public BigDecimal getLimitRate() {
        return limitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.limit_rate
     *
     * @param limitRate the value for fri_fac.limit_rate
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setLimitRate(BigDecimal limitRate) {
        this.limitRate = limitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.limit
     *
     * @return the value of fri_fac.limit
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Long getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.limit
     *
     * @param limit the value for fri_fac.limit
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setLimit(Long limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.fac_type
     *
     * @return the value of fri_fac.fac_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getFacType() {
        return facType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.fac_type
     *
     * @param facType the value for fri_fac.fac_type
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setFacType(String facType) {
        this.facType = facType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.excess_bgn
     *
     * @return the value of fri_fac.excess_bgn
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Long getExcessBgn() {
        return excessBgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.excess_bgn
     *
     * @param excessBgn the value for fri_fac.excess_bgn
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setExcessBgn(Long excessBgn) {
        this.excessBgn = excessBgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.excess_limit
     *
     * @return the value of fri_fac.excess_limit
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Long getExcessLimit() {
        return excessLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.excess_limit
     *
     * @param excessLimit the value for fri_fac.excess_limit
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setExcessLimit(Long excessLimit) {
        this.excessLimit = excessLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.TreatySet
     *
     * @return the value of fri_fac.TreatySet
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getTreatyset() {
        return treatyset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.TreatySet
     *
     * @param treatyset the value for fri_fac.TreatySet
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setTreatyset(String treatyset) {
        this.treatyset = treatyset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.currency
     *
     * @return the value of fri_fac.currency
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.currency
     *
     * @param currency the value for fri_fac.currency
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.currencyExchangeRate
     *
     * @return the value of fri_fac.currencyExchangeRate
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public BigDecimal getCurrencyexchangerate() {
        return currencyexchangerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.currencyExchangeRate
     *
     * @param currencyexchangerate the value for fri_fac.currencyExchangeRate
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setCurrencyexchangerate(BigDecimal currencyexchangerate) {
        this.currencyexchangerate = currencyexchangerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.policy_no_seq
     *
     * @return the value of fri_fac.policy_no_seq
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getPolicyNoSeq() {
        return policyNoSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.policy_no_seq
     *
     * @param policyNoSeq the value for fri_fac.policy_no_seq
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setPolicyNoSeq(String policyNoSeq) {
        this.policyNoSeq = policyNoSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.LastUpdateDateTime
     *
     * @return the value of fri_fac.LastUpdateDateTime
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public Date getLastupdatedatetime() {
        return lastupdatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.LastUpdateDateTime
     *
     * @param lastupdatedatetime the value for fri_fac.LastUpdateDateTime
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setLastupdatedatetime(Date lastupdatedatetime) {
        this.lastupdatedatetime = lastupdatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.LastUpdateAccount
     *
     * @return the value of fri_fac.LastUpdateAccount
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getLastupdateaccount() {
        return lastupdateaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.LastUpdateAccount
     *
     * @param lastupdateaccount the value for fri_fac.LastUpdateAccount
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setLastupdateaccount(String lastupdateaccount) {
        this.lastupdateaccount = lastupdateaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.LOG_seq
     *
     * @return the value of fri_fac.LOG_seq
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getLogSeq() {
        return logSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.LOG_seq
     *
     * @param logSeq the value for fri_fac.LOG_seq
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setLogSeq(String logSeq) {
        this.logSeq = logSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_fac.mkovse
     *
     * @return the value of fri_fac.mkovse
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public String getMkovse() {
        return mkovse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_fac.mkovse
     *
     * @param mkovse the value for fri_fac.mkovse
     *
     * @mbg.generated Mon Nov 29 10:45:41 CST 2021
     */
    public void setMkovse(String mkovse) {
        this.mkovse = mkovse;
    }
}