package com.asi.huanan.service.dao.mybatis.model;

public class FriPolicyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy.policy_no
     *
     * @mbg.generated Mon Nov 08 11:43:23 CST 2021
     */
    private String policyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy.endorse_no
     *
     * @mbg.generated Mon Nov 08 11:43:23 CST 2021
     */
    private String endorseNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy.policy_no
     *
     * @return the value of fri_policy.policy_no
     *
     * @mbg.generated Mon Nov 08 11:43:23 CST 2021
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy.policy_no
     *
     * @param policyNo the value for fri_policy.policy_no
     *
     * @mbg.generated Mon Nov 08 11:43:23 CST 2021
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy.endorse_no
     *
     * @return the value of fri_policy.endorse_no
     *
     * @mbg.generated Mon Nov 08 11:43:23 CST 2021
     */
    public String getEndorseNo() {
        return endorseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy.endorse_no
     *
     * @param endorseNo the value for fri_policy.endorse_no
     *
     * @mbg.generated Mon Nov 08 11:43:23 CST 2021
     */
    public void setEndorseNo(String endorseNo) {
        this.endorseNo = endorseNo;
    }
}