package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class FriPolicyDtl extends FriPolicyDtlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.addr_no_ori
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Short addrNoOri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.risk_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String riskNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.amt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long amt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.prem
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long prem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.prop_addr
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String propAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.zip_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.area_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.useprop_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String usepropCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.useprop_name
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String usepropName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.const_class
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String constClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.limit_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String limitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.limit
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long limit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.amt_flt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long amtFlt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.prem_flt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long premFlt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.amt_fix
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long amtFix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.prem_fix
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long premFix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.amt_typ
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long amtTyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.prem_typ
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long premTyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.amt_ear
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long amtEar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.prem_ear
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long premEar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.risk_flag
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String riskFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.risk_name
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String riskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.limit_rate
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private BigDecimal limitRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.limit_ori
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Long limitOri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.flor_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Integer florNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.policy_dbgn
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Date policyDbgn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.policy_dend
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private Date policyDend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.end_reason
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String endReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_dtl.mercno
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    private String mercno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.addr_no_ori
     *
     * @return the value of fri_policy_dtl.addr_no_ori
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Short getAddrNoOri() {
        return addrNoOri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.addr_no_ori
     *
     * @param addrNoOri the value for fri_policy_dtl.addr_no_ori
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setAddrNoOri(Short addrNoOri) {
        this.addrNoOri = addrNoOri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.risk_no
     *
     * @return the value of fri_policy_dtl.risk_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getRiskNo() {
        return riskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.risk_no
     *
     * @param riskNo the value for fri_policy_dtl.risk_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setRiskNo(String riskNo) {
        this.riskNo = riskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.amt
     *
     * @return the value of fri_policy_dtl.amt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.amt
     *
     * @param amt the value for fri_policy_dtl.amt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setAmt(Long amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.prem
     *
     * @return the value of fri_policy_dtl.prem
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getPrem() {
        return prem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.prem
     *
     * @param prem the value for fri_policy_dtl.prem
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPrem(Long prem) {
        this.prem = prem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.prop_addr
     *
     * @return the value of fri_policy_dtl.prop_addr
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getPropAddr() {
        return propAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.prop_addr
     *
     * @param propAddr the value for fri_policy_dtl.prop_addr
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPropAddr(String propAddr) {
        this.propAddr = propAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.zip_code
     *
     * @return the value of fri_policy_dtl.zip_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.zip_code
     *
     * @param zipCode the value for fri_policy_dtl.zip_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.area_code
     *
     * @return the value of fri_policy_dtl.area_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.area_code
     *
     * @param areaCode the value for fri_policy_dtl.area_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.useprop_code
     *
     * @return the value of fri_policy_dtl.useprop_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getUsepropCode() {
        return usepropCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.useprop_code
     *
     * @param usepropCode the value for fri_policy_dtl.useprop_code
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setUsepropCode(String usepropCode) {
        this.usepropCode = usepropCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.useprop_name
     *
     * @return the value of fri_policy_dtl.useprop_name
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getUsepropName() {
        return usepropName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.useprop_name
     *
     * @param usepropName the value for fri_policy_dtl.useprop_name
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setUsepropName(String usepropName) {
        this.usepropName = usepropName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.const_class
     *
     * @return the value of fri_policy_dtl.const_class
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getConstClass() {
        return constClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.const_class
     *
     * @param constClass the value for fri_policy_dtl.const_class
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setConstClass(String constClass) {
        this.constClass = constClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.limit_no
     *
     * @return the value of fri_policy_dtl.limit_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getLimitNo() {
        return limitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.limit_no
     *
     * @param limitNo the value for fri_policy_dtl.limit_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setLimitNo(String limitNo) {
        this.limitNo = limitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.limit
     *
     * @return the value of fri_policy_dtl.limit
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.limit
     *
     * @param limit the value for fri_policy_dtl.limit
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setLimit(Long limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.amt_flt
     *
     * @return the value of fri_policy_dtl.amt_flt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getAmtFlt() {
        return amtFlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.amt_flt
     *
     * @param amtFlt the value for fri_policy_dtl.amt_flt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setAmtFlt(Long amtFlt) {
        this.amtFlt = amtFlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.prem_flt
     *
     * @return the value of fri_policy_dtl.prem_flt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getPremFlt() {
        return premFlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.prem_flt
     *
     * @param premFlt the value for fri_policy_dtl.prem_flt
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPremFlt(Long premFlt) {
        this.premFlt = premFlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.amt_fix
     *
     * @return the value of fri_policy_dtl.amt_fix
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getAmtFix() {
        return amtFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.amt_fix
     *
     * @param amtFix the value for fri_policy_dtl.amt_fix
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setAmtFix(Long amtFix) {
        this.amtFix = amtFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.prem_fix
     *
     * @return the value of fri_policy_dtl.prem_fix
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getPremFix() {
        return premFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.prem_fix
     *
     * @param premFix the value for fri_policy_dtl.prem_fix
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPremFix(Long premFix) {
        this.premFix = premFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.amt_typ
     *
     * @return the value of fri_policy_dtl.amt_typ
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getAmtTyp() {
        return amtTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.amt_typ
     *
     * @param amtTyp the value for fri_policy_dtl.amt_typ
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setAmtTyp(Long amtTyp) {
        this.amtTyp = amtTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.prem_typ
     *
     * @return the value of fri_policy_dtl.prem_typ
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getPremTyp() {
        return premTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.prem_typ
     *
     * @param premTyp the value for fri_policy_dtl.prem_typ
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPremTyp(Long premTyp) {
        this.premTyp = premTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.amt_ear
     *
     * @return the value of fri_policy_dtl.amt_ear
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getAmtEar() {
        return amtEar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.amt_ear
     *
     * @param amtEar the value for fri_policy_dtl.amt_ear
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setAmtEar(Long amtEar) {
        this.amtEar = amtEar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.prem_ear
     *
     * @return the value of fri_policy_dtl.prem_ear
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getPremEar() {
        return premEar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.prem_ear
     *
     * @param premEar the value for fri_policy_dtl.prem_ear
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPremEar(Long premEar) {
        this.premEar = premEar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.risk_flag
     *
     * @return the value of fri_policy_dtl.risk_flag
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getRiskFlag() {
        return riskFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.risk_flag
     *
     * @param riskFlag the value for fri_policy_dtl.risk_flag
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setRiskFlag(String riskFlag) {
        this.riskFlag = riskFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.risk_name
     *
     * @return the value of fri_policy_dtl.risk_name
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getRiskName() {
        return riskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.risk_name
     *
     * @param riskName the value for fri_policy_dtl.risk_name
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setRiskName(String riskName) {
        this.riskName = riskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.limit_rate
     *
     * @return the value of fri_policy_dtl.limit_rate
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public BigDecimal getLimitRate() {
        return limitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.limit_rate
     *
     * @param limitRate the value for fri_policy_dtl.limit_rate
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setLimitRate(BigDecimal limitRate) {
        this.limitRate = limitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.limit_ori
     *
     * @return the value of fri_policy_dtl.limit_ori
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Long getLimitOri() {
        return limitOri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.limit_ori
     *
     * @param limitOri the value for fri_policy_dtl.limit_ori
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setLimitOri(Long limitOri) {
        this.limitOri = limitOri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.flor_no
     *
     * @return the value of fri_policy_dtl.flor_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Integer getFlorNo() {
        return florNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.flor_no
     *
     * @param florNo the value for fri_policy_dtl.flor_no
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setFlorNo(Integer florNo) {
        this.florNo = florNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.policy_dbgn
     *
     * @return the value of fri_policy_dtl.policy_dbgn
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Date getPolicyDbgn() {
        return policyDbgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.policy_dbgn
     *
     * @param policyDbgn the value for fri_policy_dtl.policy_dbgn
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPolicyDbgn(Date policyDbgn) {
        this.policyDbgn = policyDbgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.policy_dend
     *
     * @return the value of fri_policy_dtl.policy_dend
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Date getPolicyDend() {
        return policyDend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.policy_dend
     *
     * @param policyDend the value for fri_policy_dtl.policy_dend
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setPolicyDend(Date policyDend) {
        this.policyDend = policyDend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.end_reason
     *
     * @return the value of fri_policy_dtl.end_reason
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getEndReason() {
        return endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.end_reason
     *
     * @param endReason the value for fri_policy_dtl.end_reason
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setEndReason(String endReason) {
        this.endReason = endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_dtl.mercno
     *
     * @return the value of fri_policy_dtl.mercno
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getMercno() {
        return mercno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_dtl.mercno
     *
     * @param mercno the value for fri_policy_dtl.mercno
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setMercno(String mercno) {
        this.mercno = mercno;
    }
}