package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FriPolicyDtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public FriPolicyDtlExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPolicyNoIsNull() {
            addCriterion("policy_no is null");
            return (Criteria) this;
        }

        public Criteria andPolicyNoIsNotNull() {
            addCriterion("policy_no is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyNoEqualTo(String value) {
            addCriterion("policy_no =", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotEqualTo(String value) {
            addCriterion("policy_no <>", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoGreaterThan(String value) {
            addCriterion("policy_no >", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoGreaterThanOrEqualTo(String value) {
            addCriterion("policy_no >=", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLessThan(String value) {
            addCriterion("policy_no <", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLessThanOrEqualTo(String value) {
            addCriterion("policy_no <=", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoLike(String value) {
            addCriterion("policy_no like", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotLike(String value) {
            addCriterion("policy_no not like", value, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoIn(List<String> values) {
            addCriterion("policy_no in", values, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotIn(List<String> values) {
            addCriterion("policy_no not in", values, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoBetween(String value1, String value2) {
            addCriterion("policy_no between", value1, value2, "policyNo");
            return (Criteria) this;
        }

        public Criteria andPolicyNoNotBetween(String value1, String value2) {
            addCriterion("policy_no not between", value1, value2, "policyNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoIsNull() {
            addCriterion("endorse_no is null");
            return (Criteria) this;
        }

        public Criteria andEndorseNoIsNotNull() {
            addCriterion("endorse_no is not null");
            return (Criteria) this;
        }

        public Criteria andEndorseNoEqualTo(String value) {
            addCriterion("endorse_no =", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoNotEqualTo(String value) {
            addCriterion("endorse_no <>", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoGreaterThan(String value) {
            addCriterion("endorse_no >", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoGreaterThanOrEqualTo(String value) {
            addCriterion("endorse_no >=", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoLessThan(String value) {
            addCriterion("endorse_no <", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoLessThanOrEqualTo(String value) {
            addCriterion("endorse_no <=", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoLike(String value) {
            addCriterion("endorse_no like", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoNotLike(String value) {
            addCriterion("endorse_no not like", value, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoIn(List<String> values) {
            addCriterion("endorse_no in", values, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoNotIn(List<String> values) {
            addCriterion("endorse_no not in", values, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoBetween(String value1, String value2) {
            addCriterion("endorse_no between", value1, value2, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andEndorseNoNotBetween(String value1, String value2) {
            addCriterion("endorse_no not between", value1, value2, "endorseNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoIsNull() {
            addCriterion("addr_no is null");
            return (Criteria) this;
        }

        public Criteria andAddrNoIsNotNull() {
            addCriterion("addr_no is not null");
            return (Criteria) this;
        }

        public Criteria andAddrNoEqualTo(Short value) {
            addCriterion("addr_no =", value, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoNotEqualTo(Short value) {
            addCriterion("addr_no <>", value, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoGreaterThan(Short value) {
            addCriterion("addr_no >", value, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoGreaterThanOrEqualTo(Short value) {
            addCriterion("addr_no >=", value, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoLessThan(Short value) {
            addCriterion("addr_no <", value, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoLessThanOrEqualTo(Short value) {
            addCriterion("addr_no <=", value, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoIn(List<Short> values) {
            addCriterion("addr_no in", values, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoNotIn(List<Short> values) {
            addCriterion("addr_no not in", values, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoBetween(Short value1, Short value2) {
            addCriterion("addr_no between", value1, value2, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoNotBetween(Short value1, Short value2) {
            addCriterion("addr_no not between", value1, value2, "addrNo");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriIsNull() {
            addCriterion("addr_no_ori is null");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriIsNotNull() {
            addCriterion("addr_no_ori is not null");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriEqualTo(Short value) {
            addCriterion("addr_no_ori =", value, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriNotEqualTo(Short value) {
            addCriterion("addr_no_ori <>", value, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriGreaterThan(Short value) {
            addCriterion("addr_no_ori >", value, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriGreaterThanOrEqualTo(Short value) {
            addCriterion("addr_no_ori >=", value, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriLessThan(Short value) {
            addCriterion("addr_no_ori <", value, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriLessThanOrEqualTo(Short value) {
            addCriterion("addr_no_ori <=", value, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriIn(List<Short> values) {
            addCriterion("addr_no_ori in", values, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriNotIn(List<Short> values) {
            addCriterion("addr_no_ori not in", values, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriBetween(Short value1, Short value2) {
            addCriterion("addr_no_ori between", value1, value2, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andAddrNoOriNotBetween(Short value1, Short value2) {
            addCriterion("addr_no_ori not between", value1, value2, "addrNoOri");
            return (Criteria) this;
        }

        public Criteria andRiskNoIsNull() {
            addCriterion("risk_no is null");
            return (Criteria) this;
        }

        public Criteria andRiskNoIsNotNull() {
            addCriterion("risk_no is not null");
            return (Criteria) this;
        }

        public Criteria andRiskNoEqualTo(String value) {
            addCriterion("risk_no =", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoNotEqualTo(String value) {
            addCriterion("risk_no <>", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoGreaterThan(String value) {
            addCriterion("risk_no >", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoGreaterThanOrEqualTo(String value) {
            addCriterion("risk_no >=", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoLessThan(String value) {
            addCriterion("risk_no <", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoLessThanOrEqualTo(String value) {
            addCriterion("risk_no <=", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoLike(String value) {
            addCriterion("risk_no like", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoNotLike(String value) {
            addCriterion("risk_no not like", value, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoIn(List<String> values) {
            addCriterion("risk_no in", values, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoNotIn(List<String> values) {
            addCriterion("risk_no not in", values, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoBetween(String value1, String value2) {
            addCriterion("risk_no between", value1, value2, "riskNo");
            return (Criteria) this;
        }

        public Criteria andRiskNoNotBetween(String value1, String value2) {
            addCriterion("risk_no not between", value1, value2, "riskNo");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("amt is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("amt is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(Long value) {
            addCriterion("amt =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(Long value) {
            addCriterion("amt <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(Long value) {
            addCriterion("amt >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("amt >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(Long value) {
            addCriterion("amt <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(Long value) {
            addCriterion("amt <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<Long> values) {
            addCriterion("amt in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<Long> values) {
            addCriterion("amt not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(Long value1, Long value2) {
            addCriterion("amt between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(Long value1, Long value2) {
            addCriterion("amt not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andPremIsNull() {
            addCriterion("prem is null");
            return (Criteria) this;
        }

        public Criteria andPremIsNotNull() {
            addCriterion("prem is not null");
            return (Criteria) this;
        }

        public Criteria andPremEqualTo(Long value) {
            addCriterion("prem =", value, "prem");
            return (Criteria) this;
        }

        public Criteria andPremNotEqualTo(Long value) {
            addCriterion("prem <>", value, "prem");
            return (Criteria) this;
        }

        public Criteria andPremGreaterThan(Long value) {
            addCriterion("prem >", value, "prem");
            return (Criteria) this;
        }

        public Criteria andPremGreaterThanOrEqualTo(Long value) {
            addCriterion("prem >=", value, "prem");
            return (Criteria) this;
        }

        public Criteria andPremLessThan(Long value) {
            addCriterion("prem <", value, "prem");
            return (Criteria) this;
        }

        public Criteria andPremLessThanOrEqualTo(Long value) {
            addCriterion("prem <=", value, "prem");
            return (Criteria) this;
        }

        public Criteria andPremIn(List<Long> values) {
            addCriterion("prem in", values, "prem");
            return (Criteria) this;
        }

        public Criteria andPremNotIn(List<Long> values) {
            addCriterion("prem not in", values, "prem");
            return (Criteria) this;
        }

        public Criteria andPremBetween(Long value1, Long value2) {
            addCriterion("prem between", value1, value2, "prem");
            return (Criteria) this;
        }

        public Criteria andPremNotBetween(Long value1, Long value2) {
            addCriterion("prem not between", value1, value2, "prem");
            return (Criteria) this;
        }

        public Criteria andPropAddrIsNull() {
            addCriterion("prop_addr is null");
            return (Criteria) this;
        }

        public Criteria andPropAddrIsNotNull() {
            addCriterion("prop_addr is not null");
            return (Criteria) this;
        }

        public Criteria andPropAddrEqualTo(String value) {
            addCriterion("prop_addr =", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrNotEqualTo(String value) {
            addCriterion("prop_addr <>", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrGreaterThan(String value) {
            addCriterion("prop_addr >", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrGreaterThanOrEqualTo(String value) {
            addCriterion("prop_addr >=", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrLessThan(String value) {
            addCriterion("prop_addr <", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrLessThanOrEqualTo(String value) {
            addCriterion("prop_addr <=", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrLike(String value) {
            addCriterion("prop_addr like", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrNotLike(String value) {
            addCriterion("prop_addr not like", value, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrIn(List<String> values) {
            addCriterion("prop_addr in", values, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrNotIn(List<String> values) {
            addCriterion("prop_addr not in", values, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrBetween(String value1, String value2) {
            addCriterion("prop_addr between", value1, value2, "propAddr");
            return (Criteria) this;
        }

        public Criteria andPropAddrNotBetween(String value1, String value2) {
            addCriterion("prop_addr not between", value1, value2, "propAddr");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNull() {
            addCriterion("zip_code is null");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNotNull() {
            addCriterion("zip_code is not null");
            return (Criteria) this;
        }

        public Criteria andZipCodeEqualTo(String value) {
            addCriterion("zip_code =", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotEqualTo(String value) {
            addCriterion("zip_code <>", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThan(String value) {
            addCriterion("zip_code >", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("zip_code >=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThan(String value) {
            addCriterion("zip_code <", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThanOrEqualTo(String value) {
            addCriterion("zip_code <=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLike(String value) {
            addCriterion("zip_code like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotLike(String value) {
            addCriterion("zip_code not like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeIn(List<String> values) {
            addCriterion("zip_code in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotIn(List<String> values) {
            addCriterion("zip_code not in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeBetween(String value1, String value2) {
            addCriterion("zip_code between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotBetween(String value1, String value2) {
            addCriterion("zip_code not between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNull() {
            addCriterion("area_code is null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNotNull() {
            addCriterion("area_code is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeEqualTo(String value) {
            addCriterion("area_code =", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotEqualTo(String value) {
            addCriterion("area_code <>", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThan(String value) {
            addCriterion("area_code >", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("area_code >=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThan(String value) {
            addCriterion("area_code <", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThanOrEqualTo(String value) {
            addCriterion("area_code <=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLike(String value) {
            addCriterion("area_code like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotLike(String value) {
            addCriterion("area_code not like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIn(List<String> values) {
            addCriterion("area_code in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotIn(List<String> values) {
            addCriterion("area_code not in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeBetween(String value1, String value2) {
            addCriterion("area_code between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotBetween(String value1, String value2) {
            addCriterion("area_code not between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeIsNull() {
            addCriterion("useprop_code is null");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeIsNotNull() {
            addCriterion("useprop_code is not null");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeEqualTo(String value) {
            addCriterion("useprop_code =", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeNotEqualTo(String value) {
            addCriterion("useprop_code <>", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeGreaterThan(String value) {
            addCriterion("useprop_code >", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeGreaterThanOrEqualTo(String value) {
            addCriterion("useprop_code >=", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeLessThan(String value) {
            addCriterion("useprop_code <", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeLessThanOrEqualTo(String value) {
            addCriterion("useprop_code <=", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeLike(String value) {
            addCriterion("useprop_code like", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeNotLike(String value) {
            addCriterion("useprop_code not like", value, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeIn(List<String> values) {
            addCriterion("useprop_code in", values, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeNotIn(List<String> values) {
            addCriterion("useprop_code not in", values, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeBetween(String value1, String value2) {
            addCriterion("useprop_code between", value1, value2, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropCodeNotBetween(String value1, String value2) {
            addCriterion("useprop_code not between", value1, value2, "usepropCode");
            return (Criteria) this;
        }

        public Criteria andUsepropNameIsNull() {
            addCriterion("useprop_name is null");
            return (Criteria) this;
        }

        public Criteria andUsepropNameIsNotNull() {
            addCriterion("useprop_name is not null");
            return (Criteria) this;
        }

        public Criteria andUsepropNameEqualTo(String value) {
            addCriterion("useprop_name =", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameNotEqualTo(String value) {
            addCriterion("useprop_name <>", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameGreaterThan(String value) {
            addCriterion("useprop_name >", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameGreaterThanOrEqualTo(String value) {
            addCriterion("useprop_name >=", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameLessThan(String value) {
            addCriterion("useprop_name <", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameLessThanOrEqualTo(String value) {
            addCriterion("useprop_name <=", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameLike(String value) {
            addCriterion("useprop_name like", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameNotLike(String value) {
            addCriterion("useprop_name not like", value, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameIn(List<String> values) {
            addCriterion("useprop_name in", values, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameNotIn(List<String> values) {
            addCriterion("useprop_name not in", values, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameBetween(String value1, String value2) {
            addCriterion("useprop_name between", value1, value2, "usepropName");
            return (Criteria) this;
        }

        public Criteria andUsepropNameNotBetween(String value1, String value2) {
            addCriterion("useprop_name not between", value1, value2, "usepropName");
            return (Criteria) this;
        }

        public Criteria andConstClassIsNull() {
            addCriterion("const_class is null");
            return (Criteria) this;
        }

        public Criteria andConstClassIsNotNull() {
            addCriterion("const_class is not null");
            return (Criteria) this;
        }

        public Criteria andConstClassEqualTo(String value) {
            addCriterion("const_class =", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassNotEqualTo(String value) {
            addCriterion("const_class <>", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassGreaterThan(String value) {
            addCriterion("const_class >", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassGreaterThanOrEqualTo(String value) {
            addCriterion("const_class >=", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassLessThan(String value) {
            addCriterion("const_class <", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassLessThanOrEqualTo(String value) {
            addCriterion("const_class <=", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassLike(String value) {
            addCriterion("const_class like", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassNotLike(String value) {
            addCriterion("const_class not like", value, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassIn(List<String> values) {
            addCriterion("const_class in", values, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassNotIn(List<String> values) {
            addCriterion("const_class not in", values, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassBetween(String value1, String value2) {
            addCriterion("const_class between", value1, value2, "constClass");
            return (Criteria) this;
        }

        public Criteria andConstClassNotBetween(String value1, String value2) {
            addCriterion("const_class not between", value1, value2, "constClass");
            return (Criteria) this;
        }

        public Criteria andLimitNoIsNull() {
            addCriterion("limit_no is null");
            return (Criteria) this;
        }

        public Criteria andLimitNoIsNotNull() {
            addCriterion("limit_no is not null");
            return (Criteria) this;
        }

        public Criteria andLimitNoEqualTo(String value) {
            addCriterion("limit_no =", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoNotEqualTo(String value) {
            addCriterion("limit_no <>", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoGreaterThan(String value) {
            addCriterion("limit_no >", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoGreaterThanOrEqualTo(String value) {
            addCriterion("limit_no >=", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoLessThan(String value) {
            addCriterion("limit_no <", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoLessThanOrEqualTo(String value) {
            addCriterion("limit_no <=", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoLike(String value) {
            addCriterion("limit_no like", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoNotLike(String value) {
            addCriterion("limit_no not like", value, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoIn(List<String> values) {
            addCriterion("limit_no in", values, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoNotIn(List<String> values) {
            addCriterion("limit_no not in", values, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoBetween(String value1, String value2) {
            addCriterion("limit_no between", value1, value2, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitNoNotBetween(String value1, String value2) {
            addCriterion("limit_no not between", value1, value2, "limitNo");
            return (Criteria) this;
        }

        public Criteria andLimitIsNull() {
            addCriterion("limit is null");
            return (Criteria) this;
        }

        public Criteria andLimitIsNotNull() {
            addCriterion("limit is not null");
            return (Criteria) this;
        }

        public Criteria andLimitEqualTo(Long value) {
            addCriterion("limit =", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotEqualTo(Long value) {
            addCriterion("limit <>", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitGreaterThan(Long value) {
            addCriterion("limit >", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitGreaterThanOrEqualTo(Long value) {
            addCriterion("limit >=", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitLessThan(Long value) {
            addCriterion("limit <", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitLessThanOrEqualTo(Long value) {
            addCriterion("limit <=", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitIn(List<Long> values) {
            addCriterion("limit in", values, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotIn(List<Long> values) {
            addCriterion("limit not in", values, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitBetween(Long value1, Long value2) {
            addCriterion("limit between", value1, value2, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotBetween(Long value1, Long value2) {
            addCriterion("limit not between", value1, value2, "limit");
            return (Criteria) this;
        }

        public Criteria andAmtFltIsNull() {
            addCriterion("amt_flt is null");
            return (Criteria) this;
        }

        public Criteria andAmtFltIsNotNull() {
            addCriterion("amt_flt is not null");
            return (Criteria) this;
        }

        public Criteria andAmtFltEqualTo(Long value) {
            addCriterion("amt_flt =", value, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltNotEqualTo(Long value) {
            addCriterion("amt_flt <>", value, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltGreaterThan(Long value) {
            addCriterion("amt_flt >", value, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltGreaterThanOrEqualTo(Long value) {
            addCriterion("amt_flt >=", value, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltLessThan(Long value) {
            addCriterion("amt_flt <", value, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltLessThanOrEqualTo(Long value) {
            addCriterion("amt_flt <=", value, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltIn(List<Long> values) {
            addCriterion("amt_flt in", values, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltNotIn(List<Long> values) {
            addCriterion("amt_flt not in", values, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltBetween(Long value1, Long value2) {
            addCriterion("amt_flt between", value1, value2, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFltNotBetween(Long value1, Long value2) {
            addCriterion("amt_flt not between", value1, value2, "amtFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltIsNull() {
            addCriterion("prem_flt is null");
            return (Criteria) this;
        }

        public Criteria andPremFltIsNotNull() {
            addCriterion("prem_flt is not null");
            return (Criteria) this;
        }

        public Criteria andPremFltEqualTo(Long value) {
            addCriterion("prem_flt =", value, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltNotEqualTo(Long value) {
            addCriterion("prem_flt <>", value, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltGreaterThan(Long value) {
            addCriterion("prem_flt >", value, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltGreaterThanOrEqualTo(Long value) {
            addCriterion("prem_flt >=", value, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltLessThan(Long value) {
            addCriterion("prem_flt <", value, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltLessThanOrEqualTo(Long value) {
            addCriterion("prem_flt <=", value, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltIn(List<Long> values) {
            addCriterion("prem_flt in", values, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltNotIn(List<Long> values) {
            addCriterion("prem_flt not in", values, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltBetween(Long value1, Long value2) {
            addCriterion("prem_flt between", value1, value2, "premFlt");
            return (Criteria) this;
        }

        public Criteria andPremFltNotBetween(Long value1, Long value2) {
            addCriterion("prem_flt not between", value1, value2, "premFlt");
            return (Criteria) this;
        }

        public Criteria andAmtFixIsNull() {
            addCriterion("amt_fix is null");
            return (Criteria) this;
        }

        public Criteria andAmtFixIsNotNull() {
            addCriterion("amt_fix is not null");
            return (Criteria) this;
        }

        public Criteria andAmtFixEqualTo(Long value) {
            addCriterion("amt_fix =", value, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixNotEqualTo(Long value) {
            addCriterion("amt_fix <>", value, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixGreaterThan(Long value) {
            addCriterion("amt_fix >", value, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixGreaterThanOrEqualTo(Long value) {
            addCriterion("amt_fix >=", value, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixLessThan(Long value) {
            addCriterion("amt_fix <", value, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixLessThanOrEqualTo(Long value) {
            addCriterion("amt_fix <=", value, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixIn(List<Long> values) {
            addCriterion("amt_fix in", values, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixNotIn(List<Long> values) {
            addCriterion("amt_fix not in", values, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixBetween(Long value1, Long value2) {
            addCriterion("amt_fix between", value1, value2, "amtFix");
            return (Criteria) this;
        }

        public Criteria andAmtFixNotBetween(Long value1, Long value2) {
            addCriterion("amt_fix not between", value1, value2, "amtFix");
            return (Criteria) this;
        }

        public Criteria andPremFixIsNull() {
            addCriterion("prem_fix is null");
            return (Criteria) this;
        }

        public Criteria andPremFixIsNotNull() {
            addCriterion("prem_fix is not null");
            return (Criteria) this;
        }

        public Criteria andPremFixEqualTo(Long value) {
            addCriterion("prem_fix =", value, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixNotEqualTo(Long value) {
            addCriterion("prem_fix <>", value, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixGreaterThan(Long value) {
            addCriterion("prem_fix >", value, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixGreaterThanOrEqualTo(Long value) {
            addCriterion("prem_fix >=", value, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixLessThan(Long value) {
            addCriterion("prem_fix <", value, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixLessThanOrEqualTo(Long value) {
            addCriterion("prem_fix <=", value, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixIn(List<Long> values) {
            addCriterion("prem_fix in", values, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixNotIn(List<Long> values) {
            addCriterion("prem_fix not in", values, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixBetween(Long value1, Long value2) {
            addCriterion("prem_fix between", value1, value2, "premFix");
            return (Criteria) this;
        }

        public Criteria andPremFixNotBetween(Long value1, Long value2) {
            addCriterion("prem_fix not between", value1, value2, "premFix");
            return (Criteria) this;
        }

        public Criteria andAmtTypIsNull() {
            addCriterion("amt_typ is null");
            return (Criteria) this;
        }

        public Criteria andAmtTypIsNotNull() {
            addCriterion("amt_typ is not null");
            return (Criteria) this;
        }

        public Criteria andAmtTypEqualTo(Long value) {
            addCriterion("amt_typ =", value, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypNotEqualTo(Long value) {
            addCriterion("amt_typ <>", value, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypGreaterThan(Long value) {
            addCriterion("amt_typ >", value, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypGreaterThanOrEqualTo(Long value) {
            addCriterion("amt_typ >=", value, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypLessThan(Long value) {
            addCriterion("amt_typ <", value, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypLessThanOrEqualTo(Long value) {
            addCriterion("amt_typ <=", value, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypIn(List<Long> values) {
            addCriterion("amt_typ in", values, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypNotIn(List<Long> values) {
            addCriterion("amt_typ not in", values, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypBetween(Long value1, Long value2) {
            addCriterion("amt_typ between", value1, value2, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andAmtTypNotBetween(Long value1, Long value2) {
            addCriterion("amt_typ not between", value1, value2, "amtTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypIsNull() {
            addCriterion("prem_typ is null");
            return (Criteria) this;
        }

        public Criteria andPremTypIsNotNull() {
            addCriterion("prem_typ is not null");
            return (Criteria) this;
        }

        public Criteria andPremTypEqualTo(Long value) {
            addCriterion("prem_typ =", value, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypNotEqualTo(Long value) {
            addCriterion("prem_typ <>", value, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypGreaterThan(Long value) {
            addCriterion("prem_typ >", value, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypGreaterThanOrEqualTo(Long value) {
            addCriterion("prem_typ >=", value, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypLessThan(Long value) {
            addCriterion("prem_typ <", value, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypLessThanOrEqualTo(Long value) {
            addCriterion("prem_typ <=", value, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypIn(List<Long> values) {
            addCriterion("prem_typ in", values, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypNotIn(List<Long> values) {
            addCriterion("prem_typ not in", values, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypBetween(Long value1, Long value2) {
            addCriterion("prem_typ between", value1, value2, "premTyp");
            return (Criteria) this;
        }

        public Criteria andPremTypNotBetween(Long value1, Long value2) {
            addCriterion("prem_typ not between", value1, value2, "premTyp");
            return (Criteria) this;
        }

        public Criteria andAmtEarIsNull() {
            addCriterion("amt_ear is null");
            return (Criteria) this;
        }

        public Criteria andAmtEarIsNotNull() {
            addCriterion("amt_ear is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEarEqualTo(Long value) {
            addCriterion("amt_ear =", value, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarNotEqualTo(Long value) {
            addCriterion("amt_ear <>", value, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarGreaterThan(Long value) {
            addCriterion("amt_ear >", value, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarGreaterThanOrEqualTo(Long value) {
            addCriterion("amt_ear >=", value, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarLessThan(Long value) {
            addCriterion("amt_ear <", value, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarLessThanOrEqualTo(Long value) {
            addCriterion("amt_ear <=", value, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarIn(List<Long> values) {
            addCriterion("amt_ear in", values, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarNotIn(List<Long> values) {
            addCriterion("amt_ear not in", values, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarBetween(Long value1, Long value2) {
            addCriterion("amt_ear between", value1, value2, "amtEar");
            return (Criteria) this;
        }

        public Criteria andAmtEarNotBetween(Long value1, Long value2) {
            addCriterion("amt_ear not between", value1, value2, "amtEar");
            return (Criteria) this;
        }

        public Criteria andPremEarIsNull() {
            addCriterion("prem_ear is null");
            return (Criteria) this;
        }

        public Criteria andPremEarIsNotNull() {
            addCriterion("prem_ear is not null");
            return (Criteria) this;
        }

        public Criteria andPremEarEqualTo(Long value) {
            addCriterion("prem_ear =", value, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarNotEqualTo(Long value) {
            addCriterion("prem_ear <>", value, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarGreaterThan(Long value) {
            addCriterion("prem_ear >", value, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarGreaterThanOrEqualTo(Long value) {
            addCriterion("prem_ear >=", value, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarLessThan(Long value) {
            addCriterion("prem_ear <", value, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarLessThanOrEqualTo(Long value) {
            addCriterion("prem_ear <=", value, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarIn(List<Long> values) {
            addCriterion("prem_ear in", values, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarNotIn(List<Long> values) {
            addCriterion("prem_ear not in", values, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarBetween(Long value1, Long value2) {
            addCriterion("prem_ear between", value1, value2, "premEar");
            return (Criteria) this;
        }

        public Criteria andPremEarNotBetween(Long value1, Long value2) {
            addCriterion("prem_ear not between", value1, value2, "premEar");
            return (Criteria) this;
        }

        public Criteria andRiskFlagIsNull() {
            addCriterion("risk_flag is null");
            return (Criteria) this;
        }

        public Criteria andRiskFlagIsNotNull() {
            addCriterion("risk_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRiskFlagEqualTo(String value) {
            addCriterion("risk_flag =", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagNotEqualTo(String value) {
            addCriterion("risk_flag <>", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagGreaterThan(String value) {
            addCriterion("risk_flag >", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagGreaterThanOrEqualTo(String value) {
            addCriterion("risk_flag >=", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagLessThan(String value) {
            addCriterion("risk_flag <", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagLessThanOrEqualTo(String value) {
            addCriterion("risk_flag <=", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagLike(String value) {
            addCriterion("risk_flag like", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagNotLike(String value) {
            addCriterion("risk_flag not like", value, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagIn(List<String> values) {
            addCriterion("risk_flag in", values, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagNotIn(List<String> values) {
            addCriterion("risk_flag not in", values, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagBetween(String value1, String value2) {
            addCriterion("risk_flag between", value1, value2, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskFlagNotBetween(String value1, String value2) {
            addCriterion("risk_flag not between", value1, value2, "riskFlag");
            return (Criteria) this;
        }

        public Criteria andRiskNameIsNull() {
            addCriterion("risk_name is null");
            return (Criteria) this;
        }

        public Criteria andRiskNameIsNotNull() {
            addCriterion("risk_name is not null");
            return (Criteria) this;
        }

        public Criteria andRiskNameEqualTo(String value) {
            addCriterion("risk_name =", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameNotEqualTo(String value) {
            addCriterion("risk_name <>", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameGreaterThan(String value) {
            addCriterion("risk_name >", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameGreaterThanOrEqualTo(String value) {
            addCriterion("risk_name >=", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameLessThan(String value) {
            addCriterion("risk_name <", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameLessThanOrEqualTo(String value) {
            addCriterion("risk_name <=", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameLike(String value) {
            addCriterion("risk_name like", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameNotLike(String value) {
            addCriterion("risk_name not like", value, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameIn(List<String> values) {
            addCriterion("risk_name in", values, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameNotIn(List<String> values) {
            addCriterion("risk_name not in", values, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameBetween(String value1, String value2) {
            addCriterion("risk_name between", value1, value2, "riskName");
            return (Criteria) this;
        }

        public Criteria andRiskNameNotBetween(String value1, String value2) {
            addCriterion("risk_name not between", value1, value2, "riskName");
            return (Criteria) this;
        }

        public Criteria andLimitRateIsNull() {
            addCriterion("limit_rate is null");
            return (Criteria) this;
        }

        public Criteria andLimitRateIsNotNull() {
            addCriterion("limit_rate is not null");
            return (Criteria) this;
        }

        public Criteria andLimitRateEqualTo(BigDecimal value) {
            addCriterion("limit_rate =", value, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateNotEqualTo(BigDecimal value) {
            addCriterion("limit_rate <>", value, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateGreaterThan(BigDecimal value) {
            addCriterion("limit_rate >", value, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("limit_rate >=", value, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateLessThan(BigDecimal value) {
            addCriterion("limit_rate <", value, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("limit_rate <=", value, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateIn(List<BigDecimal> values) {
            addCriterion("limit_rate in", values, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateNotIn(List<BigDecimal> values) {
            addCriterion("limit_rate not in", values, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("limit_rate between", value1, value2, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("limit_rate not between", value1, value2, "limitRate");
            return (Criteria) this;
        }

        public Criteria andLimitOriIsNull() {
            addCriterion("limit_ori is null");
            return (Criteria) this;
        }

        public Criteria andLimitOriIsNotNull() {
            addCriterion("limit_ori is not null");
            return (Criteria) this;
        }

        public Criteria andLimitOriEqualTo(Long value) {
            addCriterion("limit_ori =", value, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriNotEqualTo(Long value) {
            addCriterion("limit_ori <>", value, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriGreaterThan(Long value) {
            addCriterion("limit_ori >", value, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriGreaterThanOrEqualTo(Long value) {
            addCriterion("limit_ori >=", value, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriLessThan(Long value) {
            addCriterion("limit_ori <", value, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriLessThanOrEqualTo(Long value) {
            addCriterion("limit_ori <=", value, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriIn(List<Long> values) {
            addCriterion("limit_ori in", values, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriNotIn(List<Long> values) {
            addCriterion("limit_ori not in", values, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriBetween(Long value1, Long value2) {
            addCriterion("limit_ori between", value1, value2, "limitOri");
            return (Criteria) this;
        }

        public Criteria andLimitOriNotBetween(Long value1, Long value2) {
            addCriterion("limit_ori not between", value1, value2, "limitOri");
            return (Criteria) this;
        }

        public Criteria andFlorNoIsNull() {
            addCriterion("flor_no is null");
            return (Criteria) this;
        }

        public Criteria andFlorNoIsNotNull() {
            addCriterion("flor_no is not null");
            return (Criteria) this;
        }

        public Criteria andFlorNoEqualTo(Integer value) {
            addCriterion("flor_no =", value, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoNotEqualTo(Integer value) {
            addCriterion("flor_no <>", value, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoGreaterThan(Integer value) {
            addCriterion("flor_no >", value, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("flor_no >=", value, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoLessThan(Integer value) {
            addCriterion("flor_no <", value, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoLessThanOrEqualTo(Integer value) {
            addCriterion("flor_no <=", value, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoIn(List<Integer> values) {
            addCriterion("flor_no in", values, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoNotIn(List<Integer> values) {
            addCriterion("flor_no not in", values, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoBetween(Integer value1, Integer value2) {
            addCriterion("flor_no between", value1, value2, "florNo");
            return (Criteria) this;
        }

        public Criteria andFlorNoNotBetween(Integer value1, Integer value2) {
            addCriterion("flor_no not between", value1, value2, "florNo");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnIsNull() {
            addCriterion("policy_dbgn is null");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnIsNotNull() {
            addCriterion("policy_dbgn is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnEqualTo(Date value) {
            addCriterion("policy_dbgn =", value, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnNotEqualTo(Date value) {
            addCriterion("policy_dbgn <>", value, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnGreaterThan(Date value) {
            addCriterion("policy_dbgn >", value, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnGreaterThanOrEqualTo(Date value) {
            addCriterion("policy_dbgn >=", value, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnLessThan(Date value) {
            addCriterion("policy_dbgn <", value, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnLessThanOrEqualTo(Date value) {
            addCriterion("policy_dbgn <=", value, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnIn(List<Date> values) {
            addCriterion("policy_dbgn in", values, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnNotIn(List<Date> values) {
            addCriterion("policy_dbgn not in", values, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnBetween(Date value1, Date value2) {
            addCriterion("policy_dbgn between", value1, value2, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDbgnNotBetween(Date value1, Date value2) {
            addCriterion("policy_dbgn not between", value1, value2, "policyDbgn");
            return (Criteria) this;
        }

        public Criteria andPolicyDendIsNull() {
            addCriterion("policy_dend is null");
            return (Criteria) this;
        }

        public Criteria andPolicyDendIsNotNull() {
            addCriterion("policy_dend is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyDendEqualTo(Date value) {
            addCriterion("policy_dend =", value, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendNotEqualTo(Date value) {
            addCriterion("policy_dend <>", value, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendGreaterThan(Date value) {
            addCriterion("policy_dend >", value, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendGreaterThanOrEqualTo(Date value) {
            addCriterion("policy_dend >=", value, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendLessThan(Date value) {
            addCriterion("policy_dend <", value, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendLessThanOrEqualTo(Date value) {
            addCriterion("policy_dend <=", value, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendIn(List<Date> values) {
            addCriterion("policy_dend in", values, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendNotIn(List<Date> values) {
            addCriterion("policy_dend not in", values, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendBetween(Date value1, Date value2) {
            addCriterion("policy_dend between", value1, value2, "policyDend");
            return (Criteria) this;
        }

        public Criteria andPolicyDendNotBetween(Date value1, Date value2) {
            addCriterion("policy_dend not between", value1, value2, "policyDend");
            return (Criteria) this;
        }

        public Criteria andEndReasonIsNull() {
            addCriterion("end_reason is null");
            return (Criteria) this;
        }

        public Criteria andEndReasonIsNotNull() {
            addCriterion("end_reason is not null");
            return (Criteria) this;
        }

        public Criteria andEndReasonEqualTo(String value) {
            addCriterion("end_reason =", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonNotEqualTo(String value) {
            addCriterion("end_reason <>", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonGreaterThan(String value) {
            addCriterion("end_reason >", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonGreaterThanOrEqualTo(String value) {
            addCriterion("end_reason >=", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonLessThan(String value) {
            addCriterion("end_reason <", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonLessThanOrEqualTo(String value) {
            addCriterion("end_reason <=", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonLike(String value) {
            addCriterion("end_reason like", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonNotLike(String value) {
            addCriterion("end_reason not like", value, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonIn(List<String> values) {
            addCriterion("end_reason in", values, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonNotIn(List<String> values) {
            addCriterion("end_reason not in", values, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonBetween(String value1, String value2) {
            addCriterion("end_reason between", value1, value2, "endReason");
            return (Criteria) this;
        }

        public Criteria andEndReasonNotBetween(String value1, String value2) {
            addCriterion("end_reason not between", value1, value2, "endReason");
            return (Criteria) this;
        }

        public Criteria andMercnoIsNull() {
            addCriterion("mercno is null");
            return (Criteria) this;
        }

        public Criteria andMercnoIsNotNull() {
            addCriterion("mercno is not null");
            return (Criteria) this;
        }

        public Criteria andMercnoEqualTo(String value) {
            addCriterion("mercno =", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoNotEqualTo(String value) {
            addCriterion("mercno <>", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoGreaterThan(String value) {
            addCriterion("mercno >", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoGreaterThanOrEqualTo(String value) {
            addCriterion("mercno >=", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoLessThan(String value) {
            addCriterion("mercno <", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoLessThanOrEqualTo(String value) {
            addCriterion("mercno <=", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoLike(String value) {
            addCriterion("mercno like", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoNotLike(String value) {
            addCriterion("mercno not like", value, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoIn(List<String> values) {
            addCriterion("mercno in", values, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoNotIn(List<String> values) {
            addCriterion("mercno not in", values, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoBetween(String value1, String value2) {
            addCriterion("mercno between", value1, value2, "mercno");
            return (Criteria) this;
        }

        public Criteria andMercnoNotBetween(String value1, String value2) {
            addCriterion("mercno not between", value1, value2, "mercno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 09 10:42:31 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fri_policy_dtl
     *
     * @mbg.generated Tue Nov 09 10:42:31 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}