package com.asi.huanan.service.dao.mybatis.model;

public class FriPolicyProp extends FriPolicyPropKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.float_flag
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String floatFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.property_no
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String propertyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.property_name
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String propertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.property_code
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String propertyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.amt
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private Long amt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.prem
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private Long prem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.useprop_code
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String usepropCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.useprop_name
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String usepropName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.const_class
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String constClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.limit_no
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String limitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.spec_term
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String specTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_policy_prop.ext_term
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    private String extTerm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.float_flag
     *
     * @return the value of fri_policy_prop.float_flag
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getFloatFlag() {
        return floatFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.float_flag
     *
     * @param floatFlag the value for fri_policy_prop.float_flag
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setFloatFlag(String floatFlag) {
        this.floatFlag = floatFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.property_no
     *
     * @return the value of fri_policy_prop.property_no
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getPropertyNo() {
        return propertyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.property_no
     *
     * @param propertyNo the value for fri_policy_prop.property_no
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setPropertyNo(String propertyNo) {
        this.propertyNo = propertyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.property_name
     *
     * @return the value of fri_policy_prop.property_name
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.property_name
     *
     * @param propertyName the value for fri_policy_prop.property_name
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.property_code
     *
     * @return the value of fri_policy_prop.property_code
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.property_code
     *
     * @param propertyCode the value for fri_policy_prop.property_code
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.amt
     *
     * @return the value of fri_policy_prop.amt
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public Long getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.amt
     *
     * @param amt the value for fri_policy_prop.amt
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setAmt(Long amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.prem
     *
     * @return the value of fri_policy_prop.prem
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public Long getPrem() {
        return prem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.prem
     *
     * @param prem the value for fri_policy_prop.prem
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setPrem(Long prem) {
        this.prem = prem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.useprop_code
     *
     * @return the value of fri_policy_prop.useprop_code
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getUsepropCode() {
        return usepropCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.useprop_code
     *
     * @param usepropCode the value for fri_policy_prop.useprop_code
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setUsepropCode(String usepropCode) {
        this.usepropCode = usepropCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.useprop_name
     *
     * @return the value of fri_policy_prop.useprop_name
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getUsepropName() {
        return usepropName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.useprop_name
     *
     * @param usepropName the value for fri_policy_prop.useprop_name
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setUsepropName(String usepropName) {
        this.usepropName = usepropName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.const_class
     *
     * @return the value of fri_policy_prop.const_class
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getConstClass() {
        return constClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.const_class
     *
     * @param constClass the value for fri_policy_prop.const_class
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setConstClass(String constClass) {
        this.constClass = constClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.limit_no
     *
     * @return the value of fri_policy_prop.limit_no
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getLimitNo() {
        return limitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.limit_no
     *
     * @param limitNo the value for fri_policy_prop.limit_no
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setLimitNo(String limitNo) {
        this.limitNo = limitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.spec_term
     *
     * @return the value of fri_policy_prop.spec_term
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getSpecTerm() {
        return specTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.spec_term
     *
     * @param specTerm the value for fri_policy_prop.spec_term
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setSpecTerm(String specTerm) {
        this.specTerm = specTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_policy_prop.ext_term
     *
     * @return the value of fri_policy_prop.ext_term
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public String getExtTerm() {
        return extTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_policy_prop.ext_term
     *
     * @param extTerm the value for fri_policy_prop.ext_term
     *
     * @mbg.generated Tue Nov 30 15:54:28 CST 2021
     */
    public void setExtTerm(String extTerm) {
        this.extTerm = extTerm;
    }
}