package com.asi.huanan.service.dao.mybatis.model;

import java.math.BigDecimal;

public class FriTreatyBroker extends FriTreatyBrokerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_treaty_broker.broker_sname
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    private String brokerSname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_treaty_broker.rin_com_sname
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    private String rinComSname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_treaty_broker.rin_com_share
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    private BigDecimal rinComShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_treaty_broker.rin_com_id_OLD
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    private String rinComIdOld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fri_treaty_broker.broker_id_OLD
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    private String brokerIdOld;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_treaty_broker.broker_sname
     *
     * @return the value of fri_treaty_broker.broker_sname
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public String getBrokerSname() {
        return brokerSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_treaty_broker.broker_sname
     *
     * @param brokerSname the value for fri_treaty_broker.broker_sname
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public void setBrokerSname(String brokerSname) {
        this.brokerSname = brokerSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_treaty_broker.rin_com_sname
     *
     * @return the value of fri_treaty_broker.rin_com_sname
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public String getRinComSname() {
        return rinComSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_treaty_broker.rin_com_sname
     *
     * @param rinComSname the value for fri_treaty_broker.rin_com_sname
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public void setRinComSname(String rinComSname) {
        this.rinComSname = rinComSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_treaty_broker.rin_com_share
     *
     * @return the value of fri_treaty_broker.rin_com_share
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public BigDecimal getRinComShare() {
        return rinComShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_treaty_broker.rin_com_share
     *
     * @param rinComShare the value for fri_treaty_broker.rin_com_share
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public void setRinComShare(BigDecimal rinComShare) {
        this.rinComShare = rinComShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_treaty_broker.rin_com_id_OLD
     *
     * @return the value of fri_treaty_broker.rin_com_id_OLD
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public String getRinComIdOld() {
        return rinComIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_treaty_broker.rin_com_id_OLD
     *
     * @param rinComIdOld the value for fri_treaty_broker.rin_com_id_OLD
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public void setRinComIdOld(String rinComIdOld) {
        this.rinComIdOld = rinComIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fri_treaty_broker.broker_id_OLD
     *
     * @return the value of fri_treaty_broker.broker_id_OLD
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public String getBrokerIdOld() {
        return brokerIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fri_treaty_broker.broker_id_OLD
     *
     * @param brokerIdOld the value for fri_treaty_broker.broker_id_OLD
     *
     * @mbg.generated Wed Nov 03 10:01:52 CST 2021
     */
    public void setBrokerIdOld(String brokerIdOld) {
        this.brokerIdOld = brokerIdOld;
    }
}