package com.asi.huanan.service.dao.mybatis.model;

public class UsedArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_area.area_code
     *
     * @mbg.generated Mon Nov 15 17:06:13 CST 2021
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_area.area_code
     *
     * @return the value of used_area.area_code
     *
     * @mbg.generated Mon Nov 15 17:06:13 CST 2021
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_area.area_code
     *
     * @param areaCode the value for used_area.area_code
     *
     * @mbg.generated Mon Nov 15 17:06:13 CST 2021
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }
}