package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.CodeMaster;
import com.asi.mechanism.service.dao.mybatis.model.CodeMasterExample;

public interface CodeMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    long countByExample(CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int deleteByExample(CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int deleteByPrimaryKey(Object uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int insert(CodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int insertSelective(CodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    List<CodeMaster> selectByExample(CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    CodeMaster selectByPrimaryKey(Object uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") CodeMaster record, @Param("example") CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByExample(@Param("record") CodeMaster record, @Param("example") CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByPrimaryKeySelective(CodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_MASTER
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByPrimaryKey(CodeMaster record);
}