package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.CodeSub;
import com.asi.mechanism.service.dao.mybatis.model.CodeSubExample;
import com.asi.mechanism.service.dao.mybatis.model.CodeSubKey;

public interface CodeSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    long countByExample(CodeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int deleteByExample(CodeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int deleteByPrimaryKey(CodeSubKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int insert(CodeSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int insertSelective(CodeSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    List<CodeSub> selectByExample(CodeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    CodeSub selectByPrimaryKey(CodeSubKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") CodeSub record, @Param("example") CodeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByExample(@Param("record") CodeSub record, @Param("example") CodeSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByPrimaryKeySelective(CodeSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_SUB
     *
     * @mbg.generated Tue Dec 01 10:59:53 CST 2020
     */
    int updateByPrimaryKey(CodeSub record);
}