package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SerialNumber;
import com.asi.mechanism.service.dao.mybatis.model.SerialNumberExample;

public interface SerialNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERIAL_NUMBER
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    long countByExample(SerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERIAL_NUMBER
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    int deleteByExample(SerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERIAL_NUMBER
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    int insert(SerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERIAL_NUMBER
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    int insertSelective(SerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERIAL_NUMBER
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    List<SerialNumber> selectByExample(SerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERIAL_NUMBER
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") SerialNumber record, @Param("example") SerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERIAL_NUMBER
     *
     * @mbg.generated Sat Feb 06 15:23:02 CST 2021
     */
    int updateByExample(@Param("record") SerialNumber record, @Param("example") SerialNumberExample example);
}