package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysAccessRecord;
import com.asi.mechanism.service.dao.mybatis.model.SysAccessRecordExample;

public interface SysAccessRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_record
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    long countByExample(SysAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_record
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByExample(SysAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_record
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insert(SysAccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_record
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insertSelective(SysAccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_record
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    List<SysAccessRecord> selectByExample(SysAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_record
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysAccessRecord record, @Param("example") SysAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_record
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExample(@Param("record") SysAccessRecord record, @Param("example") SysAccessRecordExample example);
}