package com.asi.mechanism.service.dao.mybatis.mapper;

import com.asi.mechanism.service.dao.mybatis.model.SysAccountRole;
import com.asi.mechanism.service.dao.mybatis.model.SysAccountRoleExample;
import com.asi.mechanism.service.dao.mybatis.model.SysAccountRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    long countByExample(SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByExample(SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByPrimaryKey(SysAccountRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insert(SysAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insertSelective(SysAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    List<SysAccountRole> selectByExample(SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    SysAccountRole selectByPrimaryKey(SysAccountRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") SysAccountRole record, @Param("example") SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExample(@Param("record") SysAccountRole record, @Param("example") SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKeySelective(SysAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKey(SysAccountRole record);
}