package com.asi.mechanism.service.dao.mybatis.mapper;

import com.asi.mechanism.service.dao.mybatis.model.SysAccount;
import com.asi.mechanism.service.dao.mybatis.model.SysAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    long countByExample(SysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int deleteByExample(SysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int deleteByPrimaryKey(String akaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int insert(SysAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int insertSelective(SysAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    List<SysAccount> selectByExample(SysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    SysAccount selectByPrimaryKey(String akaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int updateByExampleSelective(@Param("record") SysAccount record, @Param("example") SysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int updateByExample(@Param("record") SysAccount record, @Param("example") SysAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int updateByPrimaryKeySelective(SysAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Tue Mar 01 17:07:19 CST 2022
     */
    int updateByPrimaryKey(SysAccount record);
}