package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysAccountRole;
import com.asi.mechanism.service.dao.mybatis.model.SysAccountRoleExample;
import com.asi.mechanism.service.dao.mybatis.model.SysAccountRoleKey;

public interface SysAccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    long countByExample(SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int deleteByExample(SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int deleteByPrimaryKey(SysAccountRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int insert(SysAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int insertSelective(SysAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    List<SysAccountRole> selectByExample(SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    SysAccountRole selectByPrimaryKey(SysAccountRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysAccountRole record, @Param("example") SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int updateByExample(@Param("record") SysAccountRole record, @Param("example") SysAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int updateByPrimaryKeySelective(SysAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT_ROLE
     *
     * @mbg.generated Tue Jan 19 16:03:51 CST 2021
     */
    int updateByPrimaryKey(SysAccountRole record);
}