package com.asi.mechanism.service.dao.mybatis.mapper;

import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiFieldRole;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiFieldRoleExample;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiFieldRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFuncUiFieldRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    long countByExample(SysFuncUiFieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByExample(SysFuncUiFieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByPrimaryKey(SysFuncUiFieldRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insert(SysFuncUiFieldRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insertSelective(SysFuncUiFieldRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    List<SysFuncUiFieldRole> selectByExample(SysFuncUiFieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    SysFuncUiFieldRole selectByPrimaryKey(SysFuncUiFieldRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") SysFuncUiFieldRole record, @Param("example") SysFuncUiFieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExample(@Param("record") SysFuncUiFieldRole record, @Param("example") SysFuncUiFieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKeySelective(SysFuncUiFieldRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKey(SysFuncUiFieldRole record);
}