package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiButton;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiButtonExample;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiButtonKey;

public interface SysFuncUiButtonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    long countByExample(SysFuncUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByExample(SysFuncUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByPrimaryKey(SysFuncUiButtonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insert(SysFuncUiButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insertSelective(SysFuncUiButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    List<SysFuncUiButton> selectByExample(SysFuncUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    SysFuncUiButton selectByPrimaryKey(SysFuncUiButtonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysFuncUiButton record, @Param("example") SysFuncUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExample(@Param("record") SysFuncUiButton record, @Param("example") SysFuncUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByPrimaryKeySelective(SysFuncUiButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByPrimaryKey(SysFuncUiButton record);
}