package com.asi.mechanism.service.dao.mybatis.mapper;

import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiField;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiFieldExample;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiFieldKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFuncUiFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    long countByExample(SysFuncUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByExample(SysFuncUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByPrimaryKey(SysFuncUiFieldKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insert(SysFuncUiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insertSelective(SysFuncUiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    List<SysFuncUiField> selectByExample(SysFuncUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    SysFuncUiField selectByPrimaryKey(SysFuncUiFieldKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") SysFuncUiField record, @Param("example") SysFuncUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExample(@Param("record") SysFuncUiField record, @Param("example") SysFuncUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKeySelective(SysFuncUiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_field
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKey(SysFuncUiField record);
}