package com.asi.mechanism.service.dao.mybatis.mapper;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysFunctionUiButton;
import com.asi.mechanism.service.dao.mybatis.model.SysFunctionUiButtonExample;

public interface SysFunctionUiButtonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    long countByExample(SysFunctionUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int deleteByExample(SysFunctionUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal functionUiButtonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int insert(SysFunctionUiButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int insertSelective(SysFunctionUiButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    List<SysFunctionUiButton> selectByExample(SysFunctionUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    SysFunctionUiButton selectByPrimaryKey(BigDecimal functionUiButtonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysFunctionUiButton record, @Param("example") SysFunctionUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByExample(@Param("record") SysFunctionUiButton record, @Param("example") SysFunctionUiButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByPrimaryKeySelective(SysFunctionUiButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_BUTTON
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByPrimaryKey(SysFunctionUiButton record);
}