package com.asi.mechanism.service.dao.mybatis.mapper;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysFunctionUiField;
import com.asi.mechanism.service.dao.mybatis.model.SysFunctionUiFieldExample;

public interface SysFunctionUiFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    long countByExample(SysFunctionUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int deleteByExample(SysFunctionUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal functionUiFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int insert(SysFunctionUiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int insertSelective(SysFunctionUiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    List<SysFunctionUiField> selectByExample(SysFunctionUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    SysFunctionUiField selectByPrimaryKey(BigDecimal functionUiFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysFunctionUiField record, @Param("example") SysFunctionUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByExample(@Param("record") SysFunctionUiField record, @Param("example") SysFunctionUiFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByPrimaryKeySelective(SysFunctionUiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_FUNCTION_UI_FIELD
     *
     * @mbg.generated Wed Dec 23 15:38:55 CST 2020
     */
    int updateByPrimaryKey(SysFunctionUiField record);
}