package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiButtonRole;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiButtonRoleExample;
import com.asi.mechanism.service.dao.mybatis.model.SysFuncUiButtonRoleKey;

public interface SysFuncUiButtonRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    long countByExample(SysFuncUiButtonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByExample(SysFuncUiButtonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByPrimaryKey(SysFuncUiButtonRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insert(SysFuncUiButtonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insertSelective(SysFuncUiButtonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    List<SysFuncUiButtonRole> selectByExample(SysFuncUiButtonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    SysFuncUiButtonRole selectByPrimaryKey(SysFuncUiButtonRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysFuncUiButtonRole record, @Param("example") SysFuncUiButtonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExample(@Param("record") SysFuncUiButtonRole record, @Param("example") SysFuncUiButtonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByPrimaryKeySelective(SysFuncUiButtonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_func_ui_button_role
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByPrimaryKey(SysFuncUiButtonRole record);
}