package com.asi.mechanism.service.dao.mybatis.mapper;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysIndex;
import com.asi.mechanism.service.dao.mybatis.model.SysIndexExample;

public interface SysIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    long countByExample(SysIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByExample(SysIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByPrimaryKey(BigDecimal indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insert(SysIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insertSelective(SysIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    List<SysIndex> selectByExample(SysIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    SysIndex selectByPrimaryKey(BigDecimal indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysIndex record, @Param("example") SysIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExample(@Param("record") SysIndex record, @Param("example") SysIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByPrimaryKeySelective(SysIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByPrimaryKey(SysIndex record);
}