package com.asi.mechanism.service.dao.mybatis.mapper;

import com.asi.mechanism.service.dao.mybatis.model.SysIndexRole;
import com.asi.mechanism.service.dao.mybatis.model.SysIndexRoleExample;
import com.asi.mechanism.service.dao.mybatis.model.SysIndexRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysIndexRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    long countByExample(SysIndexRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByExample(SysIndexRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByPrimaryKey(SysIndexRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insert(SysIndexRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insertSelective(SysIndexRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    List<SysIndexRole> selectByExample(SysIndexRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    SysIndexRole selectByPrimaryKey(SysIndexRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") SysIndexRole record, @Param("example") SysIndexRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExample(@Param("record") SysIndexRole record, @Param("example") SysIndexRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKeySelective(SysIndexRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_index_role
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByPrimaryKey(SysIndexRole record);
}