package com.asi.mechanism.service.dao.mybatis.mapper;

import com.asi.mechanism.service.dao.mybatis.model.SysUserPersonal;
import com.asi.mechanism.service.dao.mybatis.model.SysUserPersonalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserPersonalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    long countByExample(SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int deleteByExample(SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insert(SysUserPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int insertSelective(SysUserPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    List<SysUserPersonal> selectByExample(SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") SysUserPersonal record, @Param("example") SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Thu Feb 24 17:16:45 CST 2022
     */
    int updateByExample(@Param("record") SysUserPersonal record, @Param("example") SysUserPersonalExample example);
}