package com.asi.mechanism.service.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.asi.mechanism.service.dao.mybatis.model.SysUserPersonal;
import com.asi.mechanism.service.dao.mybatis.model.SysUserPersonalExample;

public interface SysUserPersonalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    long countByExample(SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int deleteByExample(SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insert(SysUserPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int insertSelective(SysUserPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    List<SysUserPersonal> selectByExample(SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysUserPersonal record, @Param("example") SysUserPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_personal
     *
     * @mbg.generated Tue Jun 08 16:18:13 CST 2021
     */
    int updateByExample(@Param("record") SysUserPersonal record, @Param("example") SysUserPersonalExample example);
}