#格式中注意加入空白，{key}: 100，例:port: 9000
#如專案自行處理OAuth2流程，須將authorization內server>domain、authen、checktoken、refreshtoken均改為空
jwt:
   secret: 866ea38006e4aacc6410936ea2394591f2fdcec3
ldap:
  urls: ldap://192.168.5.209:389/
  base:
    dn: ou=Users_Java,dc=asgard,dc=test,dc=com
  factory: com.sun.jndi.ldap.LdapCtxFactory
spring:
#此用法為切分「不同部份的設定且分為個別檔案」，非「同部份但不同檔案」
#   profiles:#    include:#    - dev2
   output:
      ansi:
         enabled: ALWAYS
   thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      servlet:
        content-type: text/html
      mode: HTML5
   security:
      user: 
         password: 
   quartz:
      job-store-type: memory
#      jdbc:
#        initialize-schema: always #this will create schema to db, quartz have sql script
#reference offical
      properties:
         org:
            quartz:
               scheduler:
                  instanceName: Scheduler
               threadPool:
                  threadCount: 10
               jobStore:
                  class: org.quartz.simpl.RAMJobStore
   servlet:
    multipart:
      max-file-size: 30MB   web:    resources:      static-locations: classpath:/static,classpath:/templates, file:${path.url}, file:${path.staticAccessPath}
logging:
   pattern:
#      console: "\u001b[0;31m xxxx \u001b[m %n" #使用顏色碼 
#      console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){cyan} %-5level-%clr([%t]){cyan} %m %n' #自訂log4j pattern
      console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level-[%t] %m%n' #自訂log4j pattern
   file:  
      name: ../springboot_log-dev.log
   level:
      com:
         asi: DEBUG
         zaxxer:
            hikari: INFO
      org:
         springframework: DEBUG
         mybatis: DEBUG
mailServer:
   username: asiopenkm@gmail.com
   password: '!@#456QWErty'
   host: smtp.gmail.com
   port: 587
   auth: 'true'
   starttlsEnable: 'true'
path:
#   url: static/shigen/images/uploadFile/
   url: D:/uploadFile/images/
   staticAccessPath: D:/uploadFile/front/
